#+SETUPFILE: setup.org

#+begin_export latex
\begin{tabbing}
\hspace{11cm} \= Студент: \= Ярошевский Илья \\
  \> Группа: \> 1  \\
  \> Дата: \> \today
\end{tabbing}
\hrule
\vspace{1cm}
#+end_export


#+ATTR_LATEX: :options {1}
#+begin_manualtask org
#+end_manualtask
#+begin_proof org
Возьмем потенциал \(\varphi\) -- количество единиц в \(a\). Пусть \(n_s\) -- количество единиц в начале (с младших битов). Тогда количество итераций будет равно \(n_s + 1\) -- меняем каждую единицу на 0 и меняем последующий 0 на 1. Получается если до прибавления было \(\varphi_i = n_1\) единиц, то после прибавления станет \(\varphi_{i + 1} = n_1 - n_s + 1\). Тогда \(a_i = n_s + 1 + (n_1 - n_s + 1 - n_1) = 2 = \Theta(1)\). Посчитаем среднее время:
\[ \frac{\display \sum_{i = 0}^m \text{time}_i}{m} \le \Theta(1) + \frac{\varphi_0 - \varphi_m}{m} \le \Theta(1) + \frac{n}{m} \addtag \]
Тогда \(m\) операций будет выполнены не больше чем за
\[ m \cdot \Theta(1) + m \cdot \frac{n}{m} = \Theta(m + n) \addtag \]
То есть за \(\O(m + n)\).
#+end_proof

-----

#+ATTR_LATEX: :options {2}
#+begin_manualtask org
#+end_manualtask
#+begin_solution org
\-
#+begin_src cpp -n
  // Given:
  int a[n];
  query queries[m];

  int inc[n];
  for (int i = 0; i < m; ++i) { // $\Theta(m)$
    inc[queries[i].l] += queries[i].x;

    if (queries[i].r < n - 1) {
      inc[queries[i].r + 1] -= queries[i].x;
    }
  }

  int res[n];
  int cur_inc = 0;
  for (int i = 0; i < n; ++i) { // $\Theta(n)$
    cur_inc += inc[i];
    res[i] = a[i] + cur_inc; // $\label{2curinc}$
  }

  print(res);
#+end_src

Рассмотрим для каждого \(i\) чему равен элемент в =res=. Для этого рассмотрим чему равно на \(i\)-й итерации значение =cur_inc= на строчке \ref{2curinc}.
\begin{gather}
  \texttt{cur\_inc}_i = \sum_{j = 0}^i \texttt{inc}_j = \sum_{j = 0}^i \sum_{\substack{q \in \texttt{queries} \\ q_l = j}} q_x - \sum_{\substack{q \in \texttt{queries} \\ q_r + 1 = j}} q_x = \\
   =  \sum_{\substack{q \in \texttt{queries} \\ q_l \le i}} q_x - \sum_{\substack{q \in \texttt{queries} \\ q_r + 1 \le i}} q_x = \sum_{\substack{q \in \texttt{queries} \\ q_l \le i \land q_r + 1 > i}} q_x  = \sum_{\substack{q \in \texttt{queries} \\ q_l \le i \le q_r}} q_x 
\end{gather}
Тогда в качестве \(i\)-го элемента будет выведено
\[ \texttt{a}_i + \sum_{\substack{q \in \texttt{queries} \\ q_l \le i \le q_r}} q_x \addtag \]
что как раз и является суммой начального значения =a[i]= и всех \(x\) из запросов, включающих этот элемент.

Очевидно что циклы выполняются соответственно за \(\Theta(m)\) и \(\Theta(n)\). Значит итоговое время работы \(\Theta(m + n)\).
#+end_solution

-----

#+ATTR_LATEX: :options {3}
#+begin_manualtask org
#+end_manualtask
#+begin_solution org
\-
#+begin_src cpp -n
  // Given:
  int d;
  int a[n]; // Число, старшие разряды в начале
  int k;

  stack s;
  int kn = k;
  for (int i = 0; i < n - kn; ++i) { // $\O(n)$
    while (kn > 0 && s.top() < a[i]) { // $\label{3while}$
      s.pop();
      kn--;
    }
    s.push(a[i]);
  }

  int res[n - k];
  for (int i = 0; i < n - k; ++i) { // $\O(n - k)$
    res[n - k - i - 1] = s.top();
    s.pop();
  }

  print(res)
#+end_src
Покажем что первый цикл положит в стек ровно \(n - k\) элементов. Количество удаленных на \(i\)-той итерации элементов \(d_i = \texttt{k} - \texttt{kn}_i\). Тогда при условии что больше элементы не будут удаляться, в стеке окажется \((n - \texttt{kn}_i) - d_i = n - \texttt{kn}_i - k + \texttt{kn}_i = n - k\). Это условие выполняется для каждого \(i\).

Инвариант первого цикла: На стеке лежит максимальная подпоследовательность на префиксу числа, которую можно получить удалив \(d_i\) чисел. Если текущий элемент может увеличить подпоследовательность, то в цикле на строке \ref{3while} и последущем =push= увеличим подпоследователоьность, увеличив старший разряд. Если \(\texttt{nk} = 0\), то нельзя увеличить подпоследовательность, увеличив числа в старших разрядах. 

Покажем что первый цикл выполняется за \(\O(n)\): для каждого элемента числа может выполниться максимум 2 операции, работающих за \(\O(1)\): добавление в стек и удаление из стека. Второй цикл работает за \(\Theta(n - k)\). Значит общая сложность \(\O(n)\).
#+end_solution

-----

#+ATTR_LATEX: :options {5}
#+begin_manualtask org
#+end_manualtask
#+begin_solution org
\-
#+begin_src cpp -n
  // Given:
  string s;

  stack<pair<char, int>> b;
  int m = -1;
  int ml = -1, mr = -1;
  for (int i = 0; i < len(s); ++i) { // $\O(n)$
    if (s[i] == '(' || s[i] == '[' || s[i] == '{') {
      b.push({s[i], i}); // $\label{5open}$
    } else if (!b.empty() &&
               (s[i] == ')' && b.top() == '(' || s[i] == ']' && b.top() == '[' ||
                s[i] == '}' && b.top() == '{')) {
      auto [_, j] = b.top(); // $\label{5close}$
      b.pop();

      if (i - j + 1 > m) {
        m = i - j + 1;
        ml = i;
        mr = j;
      }
    } else {
      b.clear();
    }
  }

  print(ml, mr);
#+end_src
На каждой итерации цикла выполняется инвариант:
1. В стеке лежат открывающиеся скобки, для которых еще не было пары.
2. Между скобкой на вершине стека и текущей позицией находится ПСП.
3. В =m= лежит длина максимальной ПСП на префиксе строки.
Рассмотрим различные случаи:
- Если текущая скобка открывающая. В ветке на строке \ref{5open} положим на стек открывающую скобку.
  1. Для этой скобки еще не было пары, новых пар не появилось
  2. Между скобкой и текущей позицией пустая строка -- ПСП
  3. Т.к. новой ПСП не появилось, то в =m= все еще актуально
- Если текущая скобка закрывающая и на стеке лежит парная открывающая. В строке \ref{5close} достанем с вершины стека парную закрывающую скобку вместе с ее индексом =j=. Обновим максимумальную длину.
  1. Для каждой скобки существует только одна парная, достали из стека скобку для которой нашли парную. На стеке остались скобки без парных.
  2. Т.к. от той скобки, которую достали со стека и текущей позицией была ПСП, то эта подстрока обернутая в парные скобки также ПСП.
  3. Появилась ровно 1 ПСП на префиксе. Обновили максимум с учетом ее длины, значит все еще имеем максимум на префиксе
- Иначе очищаем стек
  1. Стек пустой
  2. На стеке нет скобок
  3. Все последующие ПСП не могут содержать текущий префикс строки, т.к. он содержит неправильную скобочную последовательность.

В цикле выполняет только операции за \(\O(1)\), значит общее вермя работы \(\O(n)\).
#+end_solution

-----

#+ATTR_LATEX: :options {6}
#+begin_manualtask org
#+end_manualtask
#+begin_solution org
\-
#+begin_src cpp -n
  // Given:
  int a[n];
  int R, L;

  int s[n + 1];
  s[0] = 0;
  for (int i = 1; i <= n; ++i) { // $\Theta(n)$
    s[i] = s[i - 1] + a[i - 1];
  }

  int m = -INF;
  int ml = -1, mr = -1;
  min_queue<pair<int, int>> q;
  q.push({s[0], 0});
  for (int i = L; i <= n; ++i) { // $\O(n)$
    if (s[i] - q.min().first > m) { // $\label{6if}$
      m = s[i] - q.min().first;
      ml = q.min().second;
      mr = i - 1;
    }

    q.push({s[i - L + 1], i - L + 1});
    if (i >= R) {
      q.pop({s[i - R], i - R});
    }
  }

  print(ml, mr);
#+end_src

Для начала строим массив частичных сумм =s=. Далее на каждой итерации поддерживаем инвариант:
1. В =m= хранится максимально возможная сумма для префикса \(a\).
2. В очереди с минимумом (например с лекции, на двух стеках) =q= хранятся частичные суммы на \([\max(i - R, 0); i - L]\).
Рассмотрим \(i\)-тую итерацию. Покажем чему равна максимальная сумма элементов на полуинтервалах \([i - R, i), [i - R + 1, i), \dots, [i - L, i)\):
\begin{gather}
  \max_{i - R \le l \le i - L} \sum_{l \le j < i} a_j = \max_{i - R \le l \le i - L} \sum_{0 \le j < i} a_j - \sum_{0 \le j < l} a_j = \max_{i - R \le l \le i - L} \texttt{s}_i - \texttt{s}_l = \\
  = \texttt{s}_i + \max_{i - R \le l \le i - L} - \texttt{s}_l = \texttt{s}_i - \min_{i - R \le l \le i - L} \texttt{s}_l
\end{gather}
Заметим что \(\min_{i - R \le l \le i - L} \texttt{s}_l\) это как раз тот минимум, который хранится в очереди =q=.
1. Заметим что все отрезки, правая граница которых \(< i\) уже рассмотрены, и максимальная сумма на них уже в =m=. Выше показали что можем найти максимальную сумму на всех возможных отрезках, правая граница которых равна \(i\). Обновляем =m= с учетом этого значения в строке \ref{6if}. Теперь =m= это максимум на всех отрезках с правой границей \(\le i\).
2. Добавляем в очередь элемент \(i - L + 1\) и убираем \(i - R\) (если \(> 0\)). Значит теперь в очереди хранятся элементы \((\max(i - R + 1, 0); i - L + 1]\), то есть \([\max((i + 1) - R, 0); (i + 1) - L]\).

Первый цикл работает за \(\Theta(n)\). Во втором используем только операции, которые работают за \(\O(1)\), а значит весь цикл работает за \(\O(n)\). Значить общая сложность \(\O(n)\).
#+end_solution

-----

#+ATTR_LATEX: :options {7}
#+begin_manualtask org
#+end_manualtask
#+begin_solution org
:(
#+end_solution


