#+SETUPFILE: setup.org

#+begin_export latex
\begin{tabbing}
\hspace{11cm} \= Студент: \= Ярошевский Илья \\
  \> Группа: \> 1  \\
  \> Дата: \> \today
\end{tabbing}
\hrule
\vspace{1cm}
#+end_export


#+ATTR_LATEX: :options {1}
#+begin_manualtask org
#+end_manualtask
#+begin_proof org
Возьмем потенциал \(\varphi\) -- количество единиц в \(a\). Пусть \(n_s\) -- количество единиц в начале (с младших битов). Тогда количество итераций будет равно \(n_s + 1\) -- меняем каждую единицу на 0 и меняем последующий 0 на 1. Получается если до прибавления было \(\varphi_i = n_1\) единиц, то после прибавления станет \(\varphi_{i + 1} = n_1 - n_s + 1\). Тогда \(a_i = n_s + 1 + (n_1 - n_s + 1 - n_1) = 2 = \Theta(1)\). Посчитаем среднее время:
\[ \frac{\display \sum_{i = 0}^m \text{time}_i}{m} \le \Theta(1) + \frac{\varphi_0 - \varphi_m}{m} \le \Theta(1) + \frac{n}{m} \addtag \]
Тогда \(m\) операций будет выполнены не больше чем за
\[ m \cdot \Theta(1) + m \cdot \frac{n}{m} = \Theta(m + n) \addtag \]
То есть за \(\O(m + n)\).
#+end_proof

-----

#+ATTR_LATEX: :options {2}
#+begin_manualtask org
#+end_manualtask
#+begin_solution org
\-
#+begin_src cpp -n
  // Given:
  int a[n];
  query queries[m];

  int inc[n];
  for (int i = 0; i < m; ++i) { // $\Theta(m)$
    inc[queries[i].l] += queries[i].x;

    if (queries[i].r < n - 1) {
      inc[queries[i].r + 1] -= queries[i].x;
    }
  }

  int res[n];
  int cur_inc = 0;
  for (int i = 0; i < n; ++i) { // $\Theta(n)$
    cur_inc += inc[i];
    res[i] = a[i] + cur_inc; // $\label{2curinc}$
  }

  print(res);
#+end_src

Рассмотрим для каждого \(i\) чему равен элемент в =res=. Для этого рассмотрим чему равно на \(i\)-й итерации значение =cur_inc= на строчке \ref{2curinc}.
\begin{gather}
  \texttt{cur\_inc}_i = \sum_{j = 0}^i \texttt{inc}_j = \sum_{j = 0}^i \sum_{\substack{q \in \texttt{queries} \\ q_l = j}} q_x - \sum_{\substack{q \in \texttt{queries} \\ q_r + 1 = j}} q_x = \\
   =  \sum_{\substack{q \in \texttt{queries} \\ q_l \le i}} q_x - \sum_{\substack{q \in \texttt{queries} \\ q_r + 1 \le i}} q_x = \sum_{\substack{q \in \texttt{queries} \\ q_l \le i \land q_r + 1 > i}} q_x  = \sum_{\substack{q \in \texttt{queries} \\ q_l \le i \le q_r}} q_x 
\end{gather}
Тогда в качестве \(i\)-го элемента будет выведено
\[ \texttt{a}_i + \sum_{\substack{q \in \texttt{queries} \\ q_l \le i \le q_r}} q_x \addtag \]
что как раз и является суммой начального значения =a[i]= и всех \(x\) из запросов, включающих этот элемент.

Очевидно что циклы выполняются соответственно за \(\Theta(m)\) и \(\Theta(n)\). Значит итоговое время работы \(\Theta(m + n)\).
#+end_solution

-----

#+ATTR_LATEX: :options {3}
#+begin_manualtask org
#+end_manualtask
#+begin_solution org
Общая идея: пытаемся жадно оставить в старших разрядах максимальное число
#+begin_src cpp -n
  // Given:
  int d;
  int a[n]; // Число, старшие разряды в начале
  int k;

  stack s;
  int kn = k;
  for (int i = 0; i < n; ++i) { // $\O(n)$
    while (kn > 0 && !s.empty() && s.top() < a[i]) { // $\leftarrow \label{3while}$
      s.pop();
      kn--;
    }
    s.push(a[i]);
  }

  for (int i = 0; i < kn; ++i) s.pop();

  int res[n - k];
  for (int i = 0; i < n - k; ++i) { // $\O(n - k)$
    res[n - k - i - 1] = s.top();
    s.pop();
  }

  print(res)
#+end_src
После завершения первух двух циклов на стеке останется ровно
\(\texttt{n} - \texttt{k}\) элементов. Пройдем \(\texttt{n}\)
итераций, т.е. положим \(\texttt{n}\) элементов на стек. При этом
удалим ровно \(\texttt{k}\) элементов со стека внутренним и вторым
циклом. На стеке будет лежать искомое число со старшими разрядами на
дне стека.

Покажем что это число максимальное: пусть существует другое большее число, значит что в разряде \(i\) мы взяли другой исходный разряд, при том что до этого выбранные числа совпадали (по индексу разряда, не по значению):
1. Взятый нами разряд больше по значению, значит это другое число не больше нашего. Противоречие
2. Взятый нами разряд равен по значению:
   1. Допустим мы удалили больше элементов до этого. Этого не может быть, т.к. это бы значило что есть несколько разрядов с одинаковым значением и мы заменили более старший разряд, младшим.
      Но этого не могло произойти, т.к. заменяем только если \(<\), но в этом случае значения равны. Противерочие
   2. Удалили одинаковое число элементов до этого. Это значит что этот разряд должен совпадать по индексу. Однако предположили что он отличный от выбранного нами. Противоречие
   3. Удалили меньшее число элементов до этого. "По индукции" можем получить это большее или равное число, т.к. больше выбор на удалении дальше. Противоречие
3. Взятый нами разряд меньше по значению:
   1. Допустим удалили больше элементов до этого. Но это значит что удалили больший по значению разряд и заменили его меньшим, чего не может быть. Противоречие
   2. Удалили одинакое число элементов до этого. Значит разряды равны по значению. Противоречие
   3. Удалили меньшее число элементов до этого. Но тогда разряд с большим значением должен был заменить его. Противоречие 
Покажем что первый цикл выполняется за \(\O(n)\): для каждого элемента числа может выполниться максимум 2 операции, работающих за \(\O(1)\): добавление в стек и удаление из стека. Второй цикл работает за \(\Theta(n - k)\). Значит общая сложность \(\O(n)\).
#+end_solution

-----

#+ATTR_LATEX: :options {4}
#+begin_manualtask org
#+end_manualtask
#+begin_solution org
\-
#+begin_src cpp -n
  // Given:
  string s;

  stack<pair<char, int>> b;
  b.push({-1, '\0'});
  int m = -1;
  int ml = -1, mr = -1;
  int l = -1;
  for (int i = 0; i < len(s); ++i) { // $\O(n)$
    if (s[i] == '(' || s[i] == '[' || s[i] == '{') {
      b.push({s[i], i}); // $\label{5open}$
    } else if (!b.empty() &&
               (s[i] == ')' && b.top() == '(' || s[i] == ']' && b.top() == '[' ||
                s[i] == '}' && b.top() == '{')) {
      b.pop();
      auto [_, j] = b.top(); // $\label{5close}$

      if (i - j > m) {
        m = i - j;
        ml = i;
        mr = j + 1;
      }
    } else {
      b.clear();
      b.push({i, '\0'});
    }
  }

  print(ml, mr);
#+end_src
На каждой итерации (в конце) цикла выполняется инвариант:
1. На дне стека лежит индекс начала потенциальной ПСП
   (т.е. позиция перед первой открывающей скобки), после этого лежат
   открывающиеся скобки, для которых еще не было пары.
2. Между индексом на вершине стека (не включая) и текущей позицией (включая) находится ПСП.
3. В =m= лежит длина максимальной ПСП на префиксе строки.
Рассмотрим различные случаи:
- Если текущая скобка открывающая. В ветке на строке \ref{5open} положим на стек открывающую скобку.
  1. Для этой скобки еще не было пары, новых пар не появилось, ничего со стека не удаляли
  2. Между скобкой и текущей позицией пустая строка --- ПСП
  3. Т.к. новой ПСП не появилось, то в =m= все еще актуально
- Если текущая скобка закрывающая и на стеке лежит парная
  открывающая. В строке \ref{5close} уберем с вершины стека парную
  закрывающую скобку.
  1. Удалили только соответствующую скобку, поэтому на стеке осталась
     либо открывающая скобка для которой еще нет парной, либо мы
     достигли дна и на вершине лежит индекс перед первой открывающей
     скобкой текущей ПСП.
  2. Между индексом на вершине стека и индексом удаленной открывающей скобки находилась ПСП.
     Конкатенация этой ПСП и новой (между удаленной скобкой и текущей) является ПСП.
  3. На вершине стека либо минимальный индекс, перед которым нет ПСП либо открывающая скобка для которой еще нет парной.
     То есть нельзя получить большую ПСП в которую входит текущая закрывающая скобка.
- Иначе очищаем стек
  1. На дне стека лежит только индекс последнего символа, который не входит ни в какую ПСП 
  2. Между индексом на вершине стека и текущей позицией пустая строка --- ПСП
  3. Все последующие ПСП не могут содержать текущий префикс строки, т.к. он содержит неправильную скобочную последовательность.

В цикле выполняет только операции за \(\O(1)\), значит общее вермя работы \(\O(n)\).
#+end_solution

-----

#+ATTR_LATEX: :options {6}
#+begin_manualtask org
#+end_manualtask
#+begin_solution org
\-
#+begin_src cpp -n
  // Given:
  int a[n];
  int R, L;

  int s[n + 1];
  s[0] = 0;
  for (int i = 1; i <= n; ++i) { // $\Theta(n)$
    s[i] = s[i - 1] + a[i - 1];
  }

  int m = -INF;
  int ml = -1, mr = -1;
  min_queue<pair<int, int>> q;
  q.push({s[0], 0});
  for (int i = L; i <= n; ++i) { // $\O(n)$
    if (s[i] - q.min().first > m) { // $\label{6if}$
      m = s[i] - q.min().first;
      ml = q.min().second;
      mr = i - 1;
    }

    q.push({s[i - L + 1], i - L + 1});
    if (i >= R) {
      q.pop({s[i - R], i - R});
    }
  }

  print(ml, mr);
#+end_src

Для начала строим массив частичных сумм =s=. Далее на каждой итерации поддерживаем инвариант:
1. В =m= хранится максимально возможная сумма для префикса \(a\).
2. В очереди с минимумом  =q= хранятся частичные суммы на \([\max(i - R, 0); i - L]\).
Рассмотрим \(i\)-тую итерацию. Покажем чему равна максимальная сумма элементов на полуинтервалах \([i - R, i), [i - R + 1, i), \dots, [i - L, i)\):
\begin{gather}
  \max_{i - R \le l \le i - L} \sum_{l \le j < i} a_j = \max_{i - R \le l \le i - L} \sum_{0 \le j < i} a_j - \sum_{0 \le j < l} a_j = \max_{i - R \le l \le i - L} \texttt{s}_i - \texttt{s}_l = \\
  = \texttt{s}_i + \max_{i - R \le l \le i - L} - \texttt{s}_l = \texttt{s}_i - \min_{i - R \le l \le i - L} \texttt{s}_l
\end{gather}
Заметим что \(\min_{i - R \le l \le i - L} \texttt{s}_l\) это как раз тот минимум, который хранится в очереди =q=.
1. Заметим что все отрезки, правая граница которых \(< i\) уже рассмотрены, и максимальная сумма на них уже в =m=. Выше показали что можем найти максимальную сумму на всех возможных отрезках, правая граница которых равна \(i\). Обновляем =m= с учетом этого значения в строке \ref{6if}. Теперь =m= это максимум на всех отрезках с правой границей \(\le i\).
2. Добавляем в очередь элемент \(i - L + 1\) и убираем \(i - R\) (если
   \(> 0\)). Значит теперь в очереди хранятся элементы \((\max(i - R, 0); i - L + 1]\), то есть \([\max((i + 1) - R, 0); (i + 1) -
   L]\).

Первый цикл работает за \(\Theta(n)\). Во втором используем только операции, которые работают за \(\O(1)\), а значит весь цикл работает за \(\O(n)\). Значить общая сложность \(\O(n)\).
#+end_solution

-----

#+ATTR_LATEX: :options {7}
#+begin_manualtask org
#+end_manualtask
#+begin_solution org
\-
#+begin_src cpp -n
  // Given:
  int a[n];
  int R, L, A, B;

  int s[n + 1];
  s[0] = 0;
  for (int i = 1; i <= n; ++i) { // $\Theta(n)$
    s[i] = s[i - 1] + a[i - 1];
  }

  int m = -INF;
  int ml = -1, mr = -1;
  min_queue<pair<int, int>> q;

  // Можно сделать массив размера $2n + 1$
  map<int, int> cnt;
  int c = 0;
  for (int i = 0, l = 0; i <= n; ++i) {
    if (!q.empty() && s[i] - q.min().first > m) {
      m = s[i] - q.min().first;
      ml = q.min().second;
      mr = i - 1;
    }

    if (i < n && ++cnt[a[i]] == 1) {
      c++;
    }
    while (l < i - R || (l <= i - L && c > B)) {
      if (--cnt[a[l]] == 0) {
        c--;
      }
      q.pop({s[l], l}); // Если не было, ничего не удалим
  	l++;
    }
    if (c >= A && l <= i - L) {
      q.push({s[i - L + 1], i - L + 1});
    }
  }

  print(ml, mr);
#+end_src
Аналогично построим массив частичных сумм. Инвариант:
1. Аналогично в =m= хранится максимально возможная сумма для префикса \(a\).
2. Аналогично только интервал \((l; i - L], l \ge i - R \), при этом
   если интервал не пустой то \(A \le \texttt{c} = \mathOp{\rm distinct}((l; i]) \le B\). 

Аналогично ищем минимум, однако не все минимумы подходят, но по прежнему имеем один интервал, т.к. \(\mathOp{\rm distinct}\) не убывающая при фиксированной правой границе.
1. Аналогично
2. Двигаем правую границу, обновляем =c=.
   Далее двигаем левую границу пока не станет верно что найдем такой минимальный \(l\), что \(l \ge i - R\) и \(\mathOp{\rm distinct}((l; i]) \le B \lor l = i + 1 - L\).

   Если \(l = i + 1 - L\), то интервал \((l = i + 1 - L; i + 1 - L]\) --- пустой. Это значит что очередь минимумов пустая (последний =if= не выполнится) и что интервалы по \(L, R\) и \(A, B\) не пересекаются, т.е. нет таких отрезков с правой границей \(i\) где от \(A\) до \(B\) различных чисел.

   Иначе \(\mathOp{\rm distinct}((l; i]) \le B\). И если при этом \(\mathOp{\rm distinct}((l; i)) \ge A\), то в очереди в конце цикла будут находится частичные суммы на интервале \(\)
   
#+end_solution
