#+LATEX_CLASS: general
#+TITLE: Лекция 6
#+AUTHOR: Ilya Yaroshevskiy


* Относительный экстремум
$f: E \subset \R^{m+ n} \rightarrow R$ \\
$\Phi: E \rightarrow \R^n\quad \Phi \in C^1$ \\
$a \in e\quad \Phi(a) = 0$ \\
$\rank \Phi'(a) = n\quad \det(\frac{\partial \Phi_i}{\partial x_j})_{i,j = 1\dots n} \neq 0$ \\
$a$ - относительный экстремум \\
Тогда $\exists (\lambda_1, \dots, \lambda_n) = \lambda$ \\
$f'(a) -\labmda \Phi'(a) = 0$ \\
#+begin_cases
f'(a) - \lambda\Phi'(a) = 0 \\
\Phi(a) = 0
#+end_cases
#+NAME: определение14
#+ATTR_LATEX: :options [О достаточном условии экстремума]
#+begin_theorem
Пусть выполнено условие для точки $a$ \\
$\forall h = (h_x, h_y) \in \R^{m + n}$: если $\Phi'(a)h = 0$($n$ уранений с $m + n$ неизвестными) \\
То можно выразить $h_y = \Psi(h_x)$(решим линейную систему) \\
Рассмторим квадратичную форму $Q(h_x) = d^2G(a, (h_x, \Psi(h_x)))$, где $G$ - функция Лагранжа \\
Q - это сужение $d^2G$ на касательное пространство $T_aM_\Phi$ \\
Тогда:
1. $Q$ - положительно опр. \Rightarrow $a$ - точка минимума
2. $Q$ - отрицательно опр. \Rightarrow $a$ - точка максимума
3. $Q$ - неопределена \Rightarrow нет экстремума
4. $Q \ge 0$ вырождена \Rightarrow информации недостаточно
#+end_theorem
#+begin_proof
$\begin{center}\begin{tikzpicture}
\draw (-2, -1) .. controls (-1, 0) and (1, 0) .. (2, -1) node[above right] {\(M_\Phi\)};
\draw (-3, -0.6) -- (2, 0);
\draw[color=red, very thick] (-1.5, -0.42) -- (-0.5, -0.3) node[above left] {\(a + \tilde{h}\)};
\draw[fill=black] (-0.5, -0.3) circle[radius=2pt] node[below right] {\(a\)};
\draw[fill=black] (-1.5, -0.65) circle[radius=2pt] node[below right] {\(a + h\)};
\end{tikzpicture}\end{center}$
$\underbrace{f(a + h)}_{a + h \in M_\Phi} - f(a) = G(a + h) - G(a) = \underbrace{dG(a, h)}_{0} + \frac{1}{2}d^2G(a, h) + o(|h|^2) = \frac{1}{2}d^2G(a, \tilde{h}) + o(|\tilde{h}|^2)> 0$ \\
Очень неточное доказательство
#+end_proof
#+begin_examp
$f = x^2z^2 + y^3 -12x - 9y - 4z$ \\
$\Phi(x, y, z) = xyz - 6$ \\
$a = (1, 2, 3)\quad \lambda = 1$ \\
Найдем тип экстремума
1. $a$ - подозрительная точка ? \\
   $G = x^2z^2 + y^3 -12x - 9y -4z -(xyz - 6)$ \\
   $G'_x = 0\quad 2xz^2 - 12 - yz = 0$ \\
   $G'_y = 0\quad 3y^2 - 9 - xz = 0$ \\
   $G'_z = 0\quad 2x^2z - 4 - xy = 0$ \\
2. $d^2 G = 2z^2dx^2 + 2x^2dz^2 + Gydy^2 + 2(4xz - y)dxdz - 2xdydz - 2zdxdy$ \\
   Подставим $a$ $d^2G(a) = 18dx^2 + 2dz^2 + 12dy^2 + 20dxdz - 2dydz - 6dxdy$ \\
   Нужно найти знак выражения $d^2G(a)$, если $(dx, dy, dz)$ удовлетворяет соотношению $d\Phi = 0$ \\
   $yzdx + xzdy + xydz = 0$ в точке $a\quad Gdx + 3dy + 2dz = 0$ \\
   $dz = -3dx - \frac{3}{2}dy$ \\
   $d^2G|_{d\Phi = 0} = 18dx^2 + 2(3dx + \frac{3}{2}dy)^2 + 12dy^2 - 10dx(6dx + 3dy) + dy(6dx + 3dy) - 6dxdy =$ \\
   $= -24dx^2 + 19.5dy^2 + \dots dxdy$ - Нет экстремума, т.к. форма не определена(при $dx = 1,\ dy = 0\quad d^2G < 0$, а при $dx = 0,\ dy = 1\quad d^2G>0$)
#+end_examp
** Вариационные исчесления(Оффтоп)
$f \in C^1([a, b])\quad \displaystyle{F(f) = \int_a^bxf(x)dx + f(a)} \to \max$
* Функциональные последовательности и ряды
$f_n \to f$ - поточечно на $E$ \quad $f,f_n: E\subset X \rightarrow R$ \\
$f_n \rightrightarrows f$ на $E$ \\
$\forall x \in E\ \forall \varepsilon > 0\ \exists N\ \forall n > N\quad |f_n(x) - f(x)| < \varepsilon$ \\
$M_n \displaystyle{\sup_{x \in E}|f_n - f| \xrightarrow[n \to +\infty]{} 0}$ \\
$\rho(f_n, f) = \displaystyle{\sup_{x \in E}|f_n(x) - f(x)}$ - метрика в $\mathcal{F} =\{f\vert E \rightarrow \R,\ f-\text{огр.}\}$, в $C([a, b])$ - непрерывные функции на $[a, b]$ \\
#+NAME: теорема23
#+ATTR_LATEX: :options [Стокса--Зайдля]
#+begin_theorem
$f_n, f: X \rightarrow \R$ ($X$ - метр. пр-во) \\
$x_0 \in X\quad f_n$ - непрерывно в $x_0$ \\
$f_n \underset{X}{\rightrightarrows} f$ \\
_Тогда_ $f$ - непрерывно в $x_0$
#+end_theorem
#+NAME: теорема23док
#+begin_proof
$|f(x) - f(x_0)| \le |f(x) - f_n(x)| + |f(x)-f_n(x_0)| + |f_n(x_0) - f(x_0)|$ (неравенство треугольника) - верно $\forall x\ \forall n$ \\
$f_n \underset{X}{\rightrightarrows} f: \forall \varepsilon > 0\ \exists N\ \forall n > N\ \displaystyle{\sup_X|f_n - f| < \frac{\varepsilon}{3}}$ \\
Берем $\forall \varepsilon > 0$, возьмем любой $n$, для которого выполнено предыдущее утверждение, тогда крайние модули из неравенства $< \frac{\varepsilon}{3}$ \\
Теперь для этого $n$ подберем $U(x_0):\ \forall x \in U(x_0)\quad |f_n(x) - f_n(x_0)| < \frac{\varepsilon}{3}$ \\
$|f(x) - f(x_0)| \le \frac{\varepsilon}{3} + \frac{\varepsilon}{3} + \frac{\varepsilon}{3} = \varepsilon$
#+end_proof
#+begin_remark
То же верно если $f_n, f: X \rightarrow Y$, где $Y$ - метрическое пространство(в частности $\R^m$)
#+end_remark
#+begin_remark
То же верно, если $X$ - топологическое пространство
#+end_remark
#+begin_corollary
$f_n\inC(X),\ f_n\underset{X}{\rightrightarrows}f\quad$ Тогда $f \in C(X)$
#+end_corollary
#+begin_remark
В теореме достаточно требовать $f_n \rightrightarrows f$ на некоторой окрестности $W(x_0)$ \\
В следствии достаточно требовать локальную равномерную сходимость \\
$\forall x \in X\ \exists W(x)\ f_n\rightrightarrows f$ на $W(x)$
#+end_remark
#+begin_examp
$f_n(x) = x^n\quad X = (0, 1)\quad f_n(x) \to 0$ поточечно на $X$ \\
$f_n \not\rightrightarrows 0$ \\
Но есть локальная равномерная сходимость \quad $\forall x \in (0, 1)\quad W(x) = (\alpha, \beta)$, где $0 < \alpha < x < \beta < 1$ \\
Тогда $f_n \rightrightarrows g$ на $(\alpha, \beta): \quad \displaystyle{\sup_{x \in (\alpha, \beta)}|f_n(x) - f(x)| = \sup_{x \in (\alpha, \beta)}x^n = \beta^n \xrightarrow[n \to +\infty]{} 0}$
и предельная функция непрерывна
#+end_examp
#+NAME: теорема24
#+begin_theorem
$X$ - компактное $\rho(f_1, f_2) = \displaystyle{\sup_{x \in X}}|f_1(x) - f_2(x)|$, где $f_1, f_2 \in C(X)$ \\
_Тогда_ пространство $C(X)$ - полное метрическое пространство \\
#+end_theorem
#+NAME: теорема24доп
#+begin_remark
$x_n \to a$ в ($X,\ \rho$) \Rightarrow $x_n$ - фунд. $\forall \varepsilon\ \exists N\ \forall n, m > M\quad \rho(x_n, x_m) < \varepsilon$ \\
$X$ - полное, если каждая фундаментальная последовательность сходится
#+end_remark
#+NAME: теорема24док
#+begin_proof
$f_n$ - фунд. в $C(X) \Rightarrow \forall x_0 \in X$ вещ. последовательность $(f_n(x_0))$ - фундаментальна \Rightarrow \\
\color{blue} $f_n$ - фунд. \Rightarrow \[ \forall \varepsilon > 0\ \exists N\ \forall n, m > N\ \forall x \in X\quad |f_n(x) - f_m(x)| < \varepsilon \addtag\label{241} \] \color{black}
$\Rightarrow \exists \displaystyle{\lim_{n \to +\infty}f_n(x) =: f(x_0)}\quad f$ - поточечный предел $f_n$ \\
Проверим: $f_n \rightrightarrows f,\ f \in C(X)$ \\
В $\eqref{241}$ перейдем к пределу при $m \to +\infty$ \\
$\forall \varepsilon > 0\ \exists N\ \forall n > N\ \forall x \in X\quad |f_n(x) - f(x)| \le \varepsilon$, т.е. $f_n \rightrightarrows f$ на $X$ и тогда $f \in C(X)$
#+end_proof
#+NAME: теорема24след
#+begin_corollary
$(\mathcal{F}, \rho)$ - полное
#+end_corollary
#+begin_remark
$(x_n)$ - последовательность в полном метричеком пространстве $X$, $x_n$ - сходится \Leftrightarrow $x_n$ - фундаментальна \\
$f: X \rightarrow Y$, $Y$ - полно, $f(x) \xrightarrow[x \to a]{} L \Leftrightarrow$ Критерий Больциано-Коши, т.е. \\
$\forall \varepsilon > 0\ \exists U(a)\ \forall x_1, x_2 \in \dot{U}(a)\quad \rho(f(x_1), f(x_2)) < \varepsilon$ \\
#+end_remark
#+begin_remark
(Критерий Коши для равномерной сходимости) \\
$B \subset C(X)\quad f_n \to f$, т.е. $f_n \rightrightarrows f$ на $X$ \Leftrightarrow фундаментальности: \\
$\forall \varepsilon > 0\ \exists N\ \forall n, m > N\ \forall x\quad |f_n(x) - f_m(x)| < \varepsilon$ (A) \\
$\displaystyle{\sup_{x \in X}|f_n - f| < \varepsilon}$ \\
(B) \Rightarrow (A), (A) \Rightarrow $\displaystyle{\sup_{x \in X}|f_n - f| \le \varepsilon}$ \\
(A) \Leftrightarrow (B) с оговоркой \\
#+end_remark
** Предельный переход под знаком интеграла
/Не теорема/ $f_n \rightarrow f \Rightarrow \displaystyle{\int_a^bf_n \rightarrow \int_a^bf}$
#+begin_examp
$[a, b] = [0, 1]\quad f_n(x) = nx^{n - 1}(1 - x^n) \xrightarrow[n \to +\infty]{} f(x) \equiv 0$ \\
\[ \int_a^Bf_n = \int_0^1nx^{n - 1}(1 - x^n)dx = \int_0^1(1 - y)dy = \frac{1}{2} \qquad \int_0^1f(x) = 0 \]
#+end_examp
#+NAME: теорема25
#+ATTR_LATEX: :options {2}
#+begin_manualtheorem
$f_n, f \in C([a, b])\quad f_n \rightrightarrows f$ на $[a, b]$ \\
_Тогда_ $\displaystyle{\int_a^bf_n \rightarrow \int_a^bf}$
#+end_manualtheorem
#+NAME: теорема25док
#+begin_proof
$\displaystyle{\left|\int_a^bf_n - \int_a^bf\right| \le \int_a^b|f_n - f| \le \sup_{[a, b]}|f_n - f|\cdot(b - a) = \rho(f_n, f)\cdot(b - a) \to 0}$
#+end_proof
#+NAME: теорема26
#+ATTR_LATEX: :options [Правило Лейбница]
#+begin_corollary
$f: \underbrace{[a, b]}_x \times \underbrace{[c, d]}_y \rightarrow \R\quad f, f'_y$ - непрерывна на $[a,b]\times[c,d]$ \\
$\Phi(y) = \displaystyle{\int_a^bf(x, y)dx\quad y \in [c, d]\quad}$ \\
_Тогда_ $\Phi$ - дифф. на $[c, d]$ и $\Phi'(y) = \displaystyle{\int_a^bf'_y(x, y)dx}$
#+end_corollary
#+NAME: теорема26док
#+begin_proof
$\frac{\Phi(y + \frac{1}{n}) - \Phi(y)}{\frac{1}{n}} = \displaystyle{\int_a^b\frac{f(x, y + \frac{1}{n}) - f(x, y)}{\frac{1}{n}}dx \overset{\text{т. Лагранжа}}{=} \int_a^b\underbrace{f'_y(x, y + \frac{\Theta}{n})}_{g_n(x, y)}dx}$ \\
/Утв./ $f_n(x, y) \underset{x \to +\infty}{\rightrightarrows} f'_y(x, y)$ на $x \in [a, b]$, а $y$ считаем фиксированным --- по теореме Кантора о равномерной непрерывности \\
$\forall \varepsilon > 0\ \exists N: \frac{1}{N} < \delta(\varepsilon) \text{--- из теоремы Кантора}\ \forall n > N\ \forall x \in [a, b]\ |f'_t(x, y + \frac{\delta}{n)} - f'_y(x, y)| < \varepsilon$ \\
Таким образом $\frac{\Phi(y + \frac{1}{n}) - \Phi(y)}{\frac{1}{n}} \to \displaystyle{\int_a^bf'_y(x, y)dx} = \Phi'(y)$
#+end_proof
#+NAME: теорема27
#+ATTR_LATEX: :options {3}[О предельном переходе под знаком производной]
#+begin_manualtheorem
$f_n \in C^1(\langle a, b \rangle),\quad f_n \to f$ поточечно, $f'_n \rightrightarrows \varphi$ на $\langle a, b\rangle$ \\
_Тогда_ $f\in C^1(\langle a, b\rangle)$ и $f' \equiv \varphi$ на $\langle a, b \rangle$ \\
$\begin{array}{ccc}
f_n & \xrightarrow[n \to +\infty]{} & f \\
D\downarrow & & \downarrow \\
f'_n & \rightrightarrows & \varphi
\end{array}$ \\
\[ \lim_{n\to+\infty}(f'_n(x)) = (\lim_{n\to+\infty}f_n(x))' \]
#+end_manualtheorem
#+NAME: теорема27док
#+begin_proof
$x_0, x_1 \in \langle a, b \rangle\quad f'_n \rightrightarrows \varphi$ на $[a, b]\ \xRightarrow{\text{Т.} 2}\displaystyle{\int_{x_0}^{x_1}f_n' \to \int_{x_0}^{x_1}\varphi}$, т.е. \\
$\begin{cases}
f_n(x_1) - f_n(x_0) \xrightarrow[n \to +\infty]{} \displaystyle{\int_{x_0}^{x_1}\varphi} \\
f_n(x_1) - f_n(x_0) \to f(x_1) - f(x_0)
\end{cases}$ \\
Итак $\forall x_0, x_1 \in \langle a, b \rangle\quad f(x_1) - f(x_0) = \displaystyle{\int_{x_0}^{x_1}\varphi}$ \\
$\underbrace{f_n'}_\text{непр} \righrightarrows \varphi \Rightarrow$
$\begin{rcases}
f - \text{первообразная}\ \varphi \\
\varphi - \text{непрерывная}
\end{rcases} \Rightarrow f' = \varphi$ \\
#+end_proof
** Равномерная сходимость функциональных рядов
#+begin_definition
$u_n: X \rightarrow \R(\R^m)\quad \sum u_n(x)$ *сходится поточечно(к сумме $S(x)$) на $X$* \\
$S_N(x) := \displaystyle{\sum_{n = 0}^{N}u_n(x)}\quad S_N(x) \to S(x)$ поточечно на $X$
#+end_definition 
#+NAME: определение17
#+begin_definition
$\displaystyle{\sum_{n = 1}^{+\infty}u_n(x)\quad \text{сходится к}\ S(x)\ \text{равномерно на }E \subset X:\quad S_N \underset{N \to +\infty}{\rightrightarrows} S\ \text{на}\ E}$ \\
#+end_definition
#+begin_remark
$\sum u_n(x)$ равномерно сходится \Rightarrow $\sum u_n(x)$ - поточечно сходится к той же сумме \\
$\displaystyle{\sup_{x \in E}|S_N - S| \xrightarrow[N \to +\infty]{} 0} \Rightarrow \forall x_0\in E:\ |S_N(x_0) - S(x_0)| \le \sup_{x \in E}|S_N - S| \to 0$
#+end_remark
#+begin_remark
Остаток ряда: $R_N(x) = \displaystyle{\sum_{n = N + 1}^{+\infty}u_n(x)\quad S(x) = S_N(x) + R_N(x)}$ \\
Ряд равномерно сходится на $E\Leftrightarrow R_N \rightrightarrows 0$ на $E$ \\
$\displaystyle{\sup_{x \in E}|S - S_N| = \sup_{x \in E}R_N}$
#+end_remark
#+begin_remark
(Необходимое условие равномерной сходимости) \\
$\sum u_n(x)$ - равномерно сходится на $E \Rightarrow u_n(x) \underset{n \to +\infty}{\rightrightarrows} 0$ \\
#+end_remark
#+begin_proof
$u_n = R_{n - 1} - R_n \rightrightarrows 0$
#+end_proof
#+begin_examp
$u_n(x) = \frac{1}{n}\quad u_n(x) \rightrightarrows 0\quad \sum \frac{1}{n}$ - расходится
#+end_examp
