#+TITLE: Дифференциальные уравнения

#+SETUPFILE: https://fniessen.github.io/org-html-themes/setup/theme-bigblow.setup

#+LaTeX_HEADER: \usepackage[utf8]{inputenc}
#+LaTeX_HEADER: \usepackage[russian]{babel}

* Дифференциальные уравнения
 Бабушкин Максим Владимирович
 [[mailto:mvbabushkin@itmo.ru][Send Mail]]
** Введение. Примеры
$F(x, y, y', y', y^{(n)}) = 0$ - дифф. ур-е
/Пример/:
Груз $m$ на пружине
\[x(t) = ?\]
\[mg = -k(0 - x_0)\]
\[mg = kx_0\]
\[F_{\sum} = ma\]
\[mg + (-k(x - x_0)) = mx\]
\[kx_0 - kx + kx_0 = mx\]
\[-kx = mx\]
Отв: $x(t) = A \cdot sin(t \sqrt{\frac{k}{m}} + \phi_0)$
$A, \phi_0$ - произвольные постоянные
** Ур-я 1-го порядка. Основные понятия
*** Ур-я 1-го порядка и его решения
$F(x, y, y') = 0$ - дифф. ур-е 1-го порядка (1)
/Опр./ Решением ур-я (1) на $(a, b)$
н-ся функция $\phi \in C(a,b)$
$F(x, \phi(x), \phi(x)') = 0$ на $(a, b)$
(/a/ и /b/ м.б. $\infty$) 
/Пример/ 
\[y' = x\]
\[y = \frac{x^2}{2} + C\]
\[\phi(x) = \frac{x^2}{2}\]
\[\phi(x) = \frac{x^2}{2} + 1\]
^~~~ Частичные решения
/Опр./ Общее решение 
Мн-во всех решений

$y = \frac{x^2}{2} + C$ - общее решение
/Опр./ Общий интеграл
соотношение вида $F(x, y, C) = 0$ которое при $\forall C$ - /решение/?

*** Форма записи ур-й 1-го порядка
/Опр./ $y' = f(x, y)$ - ур-е разрешенное относительно производной
/Пр./ 
\[y' = -\frac{x}{y}\]
\[y = \sqrt{1 - x^2}\]
Тест
^~~ - решение

/Опр./ $P(x, y)dx + Q(x, y)dy = 0$
ур-е в дифференциалах
/Опр./ Решением ^~~~ н-ся ф-ия $y(x) \in C(a, b)$
$P(x, y(x)) + Q(x, y(x))y'(x) \equiv 0$ на $(a, b)$
/Опр./ Параметризованное решение н-ся $\phi, \psi \in C(\alpha, \beta)$
1. $|\phi'(t)| + |\psi'(t)| = 0$
2. $P(\phi(t), \psi(t))\phi'(t) + Q(\phi(t), \psi(t))\psi'(t) \equiv 0$
на $(\alpha, \beta)$
*** Поле направлений и приближенное решение
\[y' = f(x, y)\]
\[f \in C\]
\[G - area\]
\[] \phi - solution\ on\ (a,b)\]
\[\phi'(x) = f(x, \phi(x)) \forall x\]
\[y_0 = \phi(x_0)\]
\phi'(x_0) = f(x_0, y_0)
$(1, f(x_0, y_0))$ - коллинеарный вектор

/Опр./ Ломаная Ейлера
$y' = f(x,y)$
$(x_0, y_0)$ - начальная точка
$\delta x$ - постоянный ???
*** Задача Коши
/Опр./ З. Коши (начальной задачей) 
для ур-я $y' = f(x,y)$ н-ют задачу отыскания его решения удовлетворяющего начальному условию
$y(x_0) = y_0$
$(x_0, y_0)$ - начальная точка
