#+setupfile: setup.org
#+TITLE: Практика 1
#+date: 5 сентября

#+begin_task org
Макс. кол-во королей, которые можно разместить на доске \(8 \times 8\), так чтобы они не били друг друга
#+end_task
#+begin_solution org
Ни в каком квадрате \(2 \times 2\) не может стоять два короля. По принципу Дирихле верхняя граница -- \( (\frac{8}{2})^2 = 16\)
#+end_solution
#+begin_answer org
\(16\)
#+end_answer

#+begin_task org
\todo
#+end_task
#+begin_solution org
Принцип Дирихле. Ящики -- кол-во матчей, которое сыграла одна команда:
\(0, \dots, n - 1\). Заметим, что "ящики" \(0\) и \(n -1\) не могут одновременно осдержать элементы, значит макс. число ящиков -- \(n - 1\), команд \(n\).
#+end_solution

#+begin_task org
\todo
#+end_task

#+begin_task org
\todo
#+end_task

#+begin_task org
\todo
#+end_task
#+begin_proof org
Контейнеры:
- \(\{1, 2, 4, \dots, 2^k\}\)
- \(\{3, 6, 12, \dots, 3\cdot 2^l\}\)
- \(\{5, 10, 20, \dots, 5\cdot 2^m\}\)
- \(\dots\)
Всего контейнеров -- кол-во нечетных чисел меньше \(2n + 1\),
т.е. \(n\). Всего чисел -- \(n + 1\). По принципу дирихле в каком-то
контейнере будет как минимум 2 числа, т.е. одно из них будет делиться
на другое.
#+end_proof

#+begin_task org
\todo
#+end_task

#+begin_task org
Доказать что
\[ 1^2 + 2^2 + \dots + n^2 = \frac{n (n + 1) (2n + 1)}{6} \]
#+end_task
#+begin_proof org
По индукции: \\
База: \(n = 1:\ 1^2 = \frac{1 \cdot 2 \cdot 3}{6} = 1\) \\
Индукционный переход: \(k \mapsto k + 1\).
\[ 1^2 + \dots + k^2 = \frac{1 (k + 1) (2k + 1)}{6} \]
Докажем что
\begin{align*}
\frac{1 (k + 2) (2k + 3)}{6} & = 1^2 + \dots + k^2 + (k + 1)^2 \xlongequal[\text{ИП}]{} \\
& = \frac{1 (k + 1) (2k + 1)}{6} + (k + 1) ^2 = \dots
\end{align*}
#+end_proof

#+begin_task org
\todo
#+end_task
#+begin_solution org
База:
- \(5: \{5\}, \{2, 3\}, \{1, 4\} \)
- \(6: \{1, 6\}, \{2, 5\}, \{3, 4\} \)
- \(8: \{8, 4\}, \{7, 5\}, \{1, 2, 3, 6\} \)
- \(9: \{9, 6\}, \{8, 7\}, \{1, 2, 3, 4, 5\} \)
Переход: \(k \mapsto k + 6\)
#+end_solution




