#+TITLE: Лекция 11
#+SETUPFILE: setup.org

#+NAME: Теорема о непрерывности сдвига_прим
#+begin_remark org
/Соглашение/: \(L^p[0, T],\ T \in \R\) --- это пространство можно понимать как пространство \(T\)-периодических функций
\[ \forall x f(x) = f(x + T) \]
- \(\tilde{f}\) --- представитель \(\tilde{f}_1\) --- еще один
- \(\tilde{f}(x) = \tilde{f}(x + T)\) почти везде
/Удобство/: \(\int_0^T f = \int_a^{a + T} f\) \\
\[C[a, b]\ \Vert f \Vert = \max_{x \in [a, b]}|f(x)|\]
\(\tilde{C}[0, T]\) --- непрерывные \(T\)-периодические функции
- \(f \in C[0, T],\ f \in \tilde{C}[0, T] \xRightarrow{\text{т. Кантора}} f\) --- равномерно непрерывна
- в \(L^p[0, T]\) функции из \(\tilde{C}\) образуют плотное множество
#+end_remark
#+begin_examp org
Линейная функция на \(L^p(X, \mu)\), \(\frac{1}{p} + \frac{1}{q} = 1\) \\
берем \(g \in L^q(X, \mu)\) и строим отображение \(L^p \to \R\)
\[ f \mapsto \int_X fg\,d\mu \quad \left|\int_X fg\right| \le \left(\int |f|^p\right)^{\frac{1}{p}} \left(\int_X |g|^p \right)^{\frac{1}{q}} \]
\[ |\alpha f_n - \alpha(f)| = \left|\int_X (f_n - f) g\right| \le \Vert f_n - f \Vert_p \cdot \Vert g \Vert_q  \]
#+end_examp
#+NAME: Сдвиг
#+begin_definition org
\-
- \(f: \R^m \to \R\)
- \(h \in \R^m\)
\(f_h(x) \coloneqq f(x + h)\) --- *Сдвиг*
#+end_definition
#+NAME: Теорема о непрерывности сдвига
#+ATTR_LATEX: :options [о непрерывности сдвига]
#+begin_theorem org
\-
1. \(f\) --- равномерно непрерывна. \\
   _Тогда_ \(\Vert f_h - f \Vert_\infty \xrightarrow[h \to 0]{} 0\), \\
   т.е. \(\sup_x |f(x + h) - f(x)| \to 0\)
2. <<nepr_11_2>>\(f \in L^p(\R^m),\ 1 \le p < +\infty\) \\
   _Тогда_ \(\Vert f_h - f\Vert_p  \xrightarrow[h \to 0]{} 0\)
3. \(f \in \tilde{C}[0, T]\) \\
   _Тогда_ \(\Vert f_h - f \Vert_\infty \xrightarrow[h \to 0]{} 0\)
4. <<nepr_11_4>>\(1 \le p < +\infty,\ f \in L^p[0, T]\) \\
   _Тогда_ \(\Vert f_h - f \Vert_p \xrightarrow[h \to 0]{} 0\)
#+end_theorem
#+begin_remark org
\-
1. Для \(L^\infty\) непрерывности сдвига нет
   \[ f = \X_{[0, 1]} \quad f_h = \X_{[-h, 1 - h]} \]
   \[ \esssup |f - f_n| = 1\]
2. Во всех упомянутых [[nepr_11_2]] и [[nepr_11_4]] \\
   \[ h \mapsto \norm{f_h - f}_p \]
   непрерывно в нуле \(\implies\) непрерывно всюду
   \[ \Vert f_h - f\Vert_p - \Vert f_{h_0} - f \Vert_p \le \Vert f_h - f_{h_0} \Vert_p = \Vert f_{h - h_0} - f \Vert_p \xrightarrow[h \to h_0]{} 0 \]
#+end_remark
#+NAME: Теорема о непрерывности сдвига_док
#+begin_proof org
\-
- 2), 4) :: \(\forall \varepsilon > 0\ \forall f \in L^p[0, T]\ \exists g\) --- непрерывная
  \[ \Vert f - g \Vert_p < \frac{\varepsilon}{3} \]
  Тогда \(g\) --- равномерно непрерывна
    \[ \Vert f_h - f \Vert_p \le \Vert f - g \Vert_p + \Vert g - g_h \Vert_p + \Vert g_h - f_h \Vert_p \le \frac{\varepsilon}{3} + \Vert g - g_h \Vert_p + \frac{\varepsilon}{3} \]
  - 4) ::   \[ \Vert g_h - g \Vert_p = \left(\int_0^T | g(x + h) - g(x)|^p\,dx\right)^{\frac{1}{p}} \le \left(\Vert g_h - g \Vert_\infty^p \cdot \int_0^T 1\,dx\right)^{\frac{1}{p}} = \]
    \[ = T^{\frac{1}{p}}\cdot \Vert g_h - g \Vert_\infty \color{gray} < \frac{\varepsilon}{3} \]
  - 2) :: \(g\) --- финитная, \(\sup g \in B(0, R)\) Пусть \(|h| < 1\)
        \[ \Vert g_h - g \Vert_p \le \Vert g_h - g \Vert_{L^p(B(0, R + 1), \lambda_m)} \le \Vert g_h - g \Vert_\infty (\lambda_m(B))^{\frac{1}{p}} \color{gray} < \frac{\varepsilon}{3} \]
#+end_proof
* Гильбертово пространство
- \(X\) --- линейное пространство над \(\R(\C)\)
- Скалярное произведение \(X \times X \to \R(\C)\)
  1. \(\langle x, x \rangle \ge 0\), \(\langle x, x \rangle = 0 \Leftrightarrow x = 0\)
  2. \(\pair{\alpha_1x_1 + \alpha_2x_2, \gamma} = \alpha_1 \pair{x, y} + \alpha_2 \pair{x, y}\)
  3. \(\pair{x, y} = \pair{y, x}\) (\(\pair{x, y} = \overline{\pair{y, x}}\))
  Неравенство Коши-Буняковского: \(|\pair{x, y}|^2 \le \pair{x, x}\pair{y, y}\)
  \[ \Vert x \Vert \xlongequal{\text{def}} \sqrt{\pair{x, x}} \]
#+NAME: Гильбертово пространство
#+begin_definition org
\(\mathcal{H}\) --- линейное пространство в котором задано скалярное произведение и соответствующая норма. Если при это \(\mathcal{H}\) --- полное (как метрическое пространство), то оно называется *Гильбертовым пространством*
#+end_definition
#+begin_examp org
\-
1. \(\R^m, \C^m\)
2. \(L^2(X, \mu)\) --- линейное пространство над \(\R(\C)\)
   \[ \pair{f, g} \coloneqq \int_X f(x)\overline{g(x)}\,d\mu(x) \]
   Корректное неравенство Коши-Буняковского для интеграла:
   \[ \left| \int_Xf\overline{g} \right| \le \left( \int_X |f|^2\right)^{\frac{1}{2}} \left(\int_X |\overline{g}|^2\right)^{\frac{1}{2}} \]
   Это скалярное произведение
   \[ \pair{g, f} = \int_X g\overline{f} = \overline{\left(\int_X fg\right)} \]
   \[ \Vert f \Vert = \left(\int_X |f|^2 \,d\mu\right)^{\frac{1}{2}} \]
   --- именно текущую норму в \(L^2\) мы и рассматривали с самого начала
   - \(L^2\) --- полно
   - \(L^2\) --- гильбертово
3. Антипример \(L^p, p \neq 2\) --- не Гильбертово
4. \(l^2 = \{(x_n)^{+\infty}_{n = 1},\ x_j \in \R(\C)\big| \sum|x_j|^2 < +\infty\}\)
      \[ \pair{x, y} \coloneqq \sum_j x_j\overline{y_j} \color{gray} = \int_\R x(j)\overline{y(j)} \,d\mu(j) \]
      \color{gray}\mu --- дискретная мера на \(\N\), \(\forall i \mu\{i\} = 1\ \mu(\R\setminus\N) = 0\) \color{black}
      \[ \Vert x \Vert = \sqrt{\sum|x_j|^2} \]
#+end_examp
#+NAME: Сходящийся ряд в гильбертовом пространстве
#+begin_definition org
Сходящийся ряд: \(\sum a_n,\ a_n \in \H\)
\[S_N = \sum_{1 \le n \le N} a_n\]
Если \(\exists S \in \H\ S_N \to S\) в \(\H\)
#+end_definition
#+NAME: ортогональность
#+begin_definition org
\(x, y \in \H\) *\(x\) ортогонально \(y\)* (\(x \perp y\)) если \(\pair{x, y} = 0\)
#+end_definition
#+begin_definition org
\(A \subset \H\) \(x \perp A: \forall a\in A\ \pair{x, a} = 0\)
#+end_definition
#+NAME: Ортогональный ряд
#+begin_definition org
Ряд \(\sum a_k\) --- *ортогональный*, если \(\forall k, l\ a_k \perp a_l\)
#+end_definition
#+begin_examp org
\(a_k \in l^2: (0, \dots, 0, \frac{1}{k}, 0, \dots)\), тогда \(\sum a_k\) --- ортогональный
\[ \sum a_k = S = (1, \frac{1}{2}, \frac{1}{3}, \dots) \in l^2 \]
#+end_examp
\beginproperty
#+NAME: Теорема о свойствах сходимости в гильбертовом пространстве_1
#+begin_property org
\(x_n \to x\), \(y_n \to y\) в \(\H\) \\
_Тогда_ \(\pair{x_n, y_n} \to \pair{x, y}\)
#+end_property
#+NAME: Теорема о свойствах сходимости в гильбертовом пространстве_1_док
#+begin_proof org
\[ | \pair{x_n, y_n} - \pair{x, y}| \le |\pair{x_n, y_n} - \pair{x, y_n}| + |\pair{x, y_n} - \pair{x, y}| \le \]
\[ \le \Vert x_n - x \Vert \cdot \Vert y_n \Vert + \Vert x \Vert \cdot \Vert y_n - y \Vert \to 0 \]
#+end_proof
#+NAME: Теорема о свойствах сходимости в гильбертовом пространстве_2
#+begin_property org
\(\sum x_k\) --- сходится \\
_Тогда_ \(\forall y \in \H\) \(\pair{\sum x_k, y} = \sum \pair{x_k, y}\)
#+end_property
#+NAME: Теорема о свойствах сходимости в гильбертовом пространстве_2_док
#+begin_proof org
\[ S_N = \sum_{k = 1}^N x_k \xrightarrow[N \to +\infty]{} S \]
\[ \pair{S_N, y} \to \pair{S, y} = \pair{\sum x_n, y} \]
\[ \pair{S_N, y} = \pair{\sum_{k = 1}^N x_k, y} = \sum \pair{x_k, y} \]
--- это частичные сумма ряда из правой части
#+end_proof
#+NAME: Теорема о свойствах сходимости в гильбертовом пространстве_3
#+begin_property org
\(\sum x_k\) --- ортогональный ряд \\
_Тогда_ \(\sum x_k\) --- сходится \Leftrightarrow \(\sum \Vert x_k \Vert^2\) --- сходится
#+end_property
#+NAME: Теорема о свойствах сходимости в гильбертовом пространстве_3_док
#+begin_proof org
\(S_n = \sum_{k = 1}^N x_k\)
\[ \Vert S_N \Vert^2 = \pair{\sum{k = 1}^N x_k, \sum{j = 1}^N x_j} = \sum_{k, j} \pair{x_k, x_j} = \sum_{k = 1}^N \pair{x_k, x_k} = \sum_{k = 1}^N \norm{x_k}^2\]
- \(\Rightarrow\) :: \(C_N\) --- фундаментальная \(\implies\) \(S_N\) --- фундаментальная в \(H\)
- \(\Leftarrow\) :: \(S_N\) --- сходится в \(\H\) 
#+end_proof
#+NAME: Ортогональная система (семейство) векторов
#+begin_definition org
\(\{e_k\} \subset \H\) --- *ортогональное семейство*. Если:
1. \(\forall k, l\ e_k \perp e_l\)
2. \(\forall k\ e_k \neq 0\)
Если потребовать
3. [@3] \(\norm{e_k} = 1\)
, то будет *ортонормированное семейство*
#+end_definition
#+begin_remark org
\(\{e_k\}\) --- О.С. \(\implies\) \(\left\{\frac{e_k}{\norm{e_k}}\right\}\) --- О.Н.С
#+end_remark
#+begin_examp org
\(l^2,\ e_k \coloneqq (0, \dots, 0, 1, 0, \dots)\) --- О.Н.С.
#+end_examp
#+begin_examp org
\(L^2[0, 2\pi]\ \{1, \cos t, \sin t, \cos 2t, \sin 2t, \dots\}\) --- О.Н.С.
\[ \int_0^{2\pi} \cos kt \cdot \cos lt = \frac{1}{2}\int_0^{s\pi} \cos(kt - lt) + \cos(kt + lt)\,dt = \left[\begin{array}{ll} 0 & k \neq l \\ \pi & k = l \end{array}\right. \]
\(\left\{\frac{1}{\sqrt{2\pi}}, \frac{\cos t}{\sqrt{\pi}}, \frac{\sin t}{\sqrt{\pi}}, \frac{\cos 2t}{\sqrt{\pi}}, \dots\right\}\) --- О.Н.С
#+end_examp
#+begin_examp org
\(L^2[0, 2\pi]\) над \(\C\)
\[ \left\{\frac{e^{ikt}}{\sqrt{2\pi}}\right\}_{k \in \mathbb{Z}}\text{ --- О.Н.С} \]
\[ \int_0^{2\pi} \frac{e^{ikt}}{\sqrt{2\pi}} \cdot \frac{e^{-ikt}}{\sqrt{2\pi}}\,dt = \frac{1}{2\pi}\int_0^{2\pi} e^{i(k - l)t}\,dt \xlongequal[k \neq l]{} \frac{1}{2\pi}\cdot \frac{1}{(k - l)i}e^{i(k - l)t}\bigg|_{t = 0}^{t = 2\pi} = 0\]
#+end_examp
#+begin_examp org
\(L^2[0, \pi]\)
\[ \left\{\frac{1}{\sqrt{\pi}}, \sqrt{\frac{2}{\pi}} \cos t, \sqrt{\frac{2}{\pi}}\cos 2t, \dots \right\}\text{ --- О.Н.С.} \]
#+end_examp
#+NAME: Теорема о коэффициентах разложения по ортогональной системе
#+begin_theorem org
\-
- \(\{e_k\}\) --- О.С. в \(\H\)
- \(x \in \H\)
- \(x = \sum_{k = 1}^\infty c_k e_k\), где \(c_k \in \R(\C)\)
_Тогда_
1. \(\{e_k\}\) --- Л.Н.З
2. \(c_k \coloneqq \frac{\pair{x, e_k}}{\norm{e_k}^2}\)
3. \(c_k e_k\) --- это проекция \(x\) на прямую \(\{t e_k,\ t \in \R(\C)\}\) \\
   \(x = c_k e_k + z,\ z \perp e_k\)
#+end_theorem
#+NAME: Теорема о коэффициентах разложения по ортогональной системе_док
#+begin_proof org
\-
1. \(\sum_{k = 1}^N \alpha_k e_k = 0\) \\
   \(\alpha_n \norm{e_k}^2 = 0 \implies \alpha_n = 0\)
2. \[\pair{x, e_k} = 2 \sum\pair{c_je_j, e_k} = c_k \cdot \norm{e_k}^2 \]
3. \[ \pair{z, e_k} = \pair{x, e_k} - \pair{c_k e_k, e_k} = 0 \]
#+end_proof
#+NAME: Коэффициенты Фурье
#+begin_definition org
\(\{e_k\}\) --- О.С. \(x \in \H\)
\[ c_k(x) \coloneqq \frac{\pair{x, e_k}}{\norm{e_k}^2} \]
--- называются *коэффициентами Фурье элемента \(x\) по системе \(\{e_k\}\)*
\[ \sum_{k = 1}^{+\infty} c_k(x) \cdot e_k \]
--- *ряд Фурье вектора \(x\) по системе \(e_k\)*
#+end_definition
#+begin_remark org
При замене ОС на ОНС \(\left\{\frac{e_k}{\norm{e_k}}\right\} = \tilde{e}_k\) ряд Фурье не изменится
\[ \frac{\pair{x, \tilde{e}_k}}{\norm{\tilde{e}_k}^2} = \pair{x, \frac{e_k}{\norm{e_k}}} = \frac{\pair{x, e_k}}{\norm{e_k}} \]
\[ \tilde{c}_k \cdot \tilde{e}_k = \frac{\pair{x, e_k}}{\norm{e_k}} \cdot \frac{e_k}{\norm{e_k}} = \frac{\pair{x, e_k}}{\norm{e_k}^2} \cdot e_k = c_k(x) \cdot e_k \]
#+end_remark
#+NAME: Теорема о свойствах частичных сумм ряда Фурье. Неравенство Бесселя
#+ATTR_LATEX: :options [о свойствах частичных сумм ряда Фурье]
#+begin_theorem org
\-
- \(\{e_k\}\) --- ОС в \(H\)
- \(x \in \H\)
- \(n \in \N\)
\[ S_n = \sum_{k = 1}^N c_k(x) e_k \in \mathcal{L}_n = \mathop{\rm Lin}(e_1, \dots, e_n)\] \\
_Тогда_
\beginproperty
#+end_theorem
#+NAME: Теорема о свойствах частичных сумм ряда Фурье. Неравенство Бесселя_1
#+begin_property org
\(S_n\) --- проекция \(x\) на \(\mathcal{L}_n\), т.е. \(x = S_n + z \implies z \perp \mathcal{L}_n\)
#+end_property
#+NAME: Теорема о свойствах частичных сумм ряда Фурье. Неравенство Бесселя_1_док
#+begin_proof org
\(k = 1,\dots,n\)
\[ \pair{z, e_k} = \pair{x - S_n, e_k} = \pair{x, e_k} - c_k(x)\norm{e_k}^2 = 0 \]
#+end_proof
#+NAME: Теорема о свойствах частичных сумм ряда Фурье. Неравенство Бесселя_2
#+begin_property org
\(S_n\) --- элемент наилучшего приближения для \(x\) в \(\mathcal{L}_n\)
\[ \norm{x - S_n} = \min_{y \in \mathcal{L}_n}\norm{x - y} \]
#+end_property
#+NAME: Теорема о свойствах частичных сумм ряда Фурье. Неравенство Бесселя_2_док
#+begin_proof org
\(x = S_n + z\)
\[ \norm{x - y}^2 = \Vert \underbrace{(S_n - y)}_{\in \mathcal{L}_n} + \underbrace{z}_{\perp \mathcal{L}_n} \Vert = \norm{S_n - y}^2 + \norm{z}^2 \ge \norm{z}^2 = \norm{x - S_n}^2\]
#+end_proof
#+NAME: Теорема о свойствах частичных сумм ряда Фурье. Неравенство Бесселя_3
#+begin_property org
\(\norm{S_n} \le \norm{x}\)
#+end_property
#+NAME: Теорема о свойствах частичных сумм ряда Фурье. Неравенство Бесселя_3_док
#+begin_proof org
\[ \norm{x}^2 = \norm{S_n}^2 + \norm{z}^2 \ge \norm{S_n}^2 \]
#+end_proof

