#+LATEX_CLASS: general
#+TITLE: Лекция 7
#+AUTHOR: Ilya Yaroshevskiy

#+begin_export latex
\newcommand{\X}{\chi}
\newcommand{\A}{\mathfrak{A}}
\newcommand{\B}{\mathfrak{B}}
\newcommand{\M}{\mathfrak{M}}
#+end_export

* Принцип Кавальери
1. \(C_x\) --- имзмерима при почти всех \(x\)
2. \(x \mapsto \nu C_x\) --- измерима*
3. \(mC = \int\limits_X \mathcal{X}_x d\mu\)
#+begin_corollary org
\(f: [a, b] \to \R\) --- непрерывная \\
_Тогда_ \(\int\limits_a^b f(x)\,dx = \int\limits_{[a, b]} f\,d\lambda_1\)
#+end_corollary
#+begin_proof org
\(f>0\ \text{ПГ}(f[a, b])\) --- измеримое множество в \(\R^2\). \(C_x = [0, f(x)]\ \lambda_1(C_x) = f(x)\)
\[ \int\limits_a^b f(x)\, dx = \lambda_2(\text{ПГ}) = \int\limits_{[a, b]} f d\lambda_1 \]
#+end_proof
#+NAME: remark_1_7
#+begin_remark org
\(\lambda_2\) можно продолжить на множество \(2^{\R^2}\) с сохранением свойства конечной аддитивности и это продолжение не единственно
#+end_remark
#+NAME: remark_2_7
#+begin_remark org
\(\lambda_m, m>2\) --- аналогичным образом продолжить невозможно. Парадокс Хаусдорфа-Банаха-Тарского
#+end_remark
#+begin_remark org
Для [[remark_1_7][замечания 1]] и [[remark_2_7][замечания 2]] требуется инвариантность меры относительно движения \(\R^m\)
#+end_remark

#+begin_definition org
\-
- \(C \subset X \times Y\)
- \(f: X \times T \to \Y\)
- \(\forall x \in X\ f_x\) --- это функция(сечение) \(f_x(y) = f(x, y)\), можно считать что она задана на \(C_x\)
- \(f^y\) --- аналогичное сечение
#+end_definition
#+begin_theorem org
\-
- \((X, \A, \mu)\)
- \((Y, \B, \nu)\)
- \(\mu, \nu\) --- \(\sigma\)-конечныемера, полные
- \(m = \mu x \nu\)
- \(f: X \times Y \to \overline{R}, f \ge 0\) --- измерима относительно \(A\otimes B\)
_Тогда_
1. при  почти всех \(x\) \(f_x\) --- измеримая на \(Y\) \color{blue}\(f^y\) --- измерима на \(X\) почти везде\color{black}
2. \(x \mapsto \varphi(x)=\int\limits_Y f_x d\nu = \int\limits_Y f(x, y) = d\nu(y)\) --- измеримая* на \(X\) \\
   \color{blue}\(y \mapsto \psi(y) = \int\limits_X f^y d\mu\) --- измеримая* на \(Y\)\color{black}
3. \(\int\limits_{X \times Y} d fm = \int\limits_X \varphi d\mu = \int\limits_X\left(\int\limits_Y f(x, y) d\nu(y)\right)d\mu(x)\) \\
   \color{blue}\(= \int\limits_Y \psi d\nu = \int\limits_Y\left(\int\limits_X f(x, y) d\mu(x)\right)d\nu(y)\)
#+end_theorem
#+begin_proof org
\todo
#+end_proof
#+begin_corllary org
\(C \subset X \times Y\) \(P_1(C)\) --- измеримо. \\
_Тогда_ \[ \int\limits_C f dm = \int\limits_{f_1(C)}\left(\int_{C_x} f(x, y) d\nu(y)\right)d\mu(x) \]
#+end_corllary
#+ATTR_LATEX: :options [Фубини]
#+begin_theorem org
\-
- \((X, \A, \mu)\)
- \(Y, B, \nu\)
- \(\nu, mu\) --- \(\sigma\)-конечные
- \(m = \nu \times \mu\)
- \(f\) --- суммируема на \(X \times Y\) относительно \(m\)
_Тогда_
1. \(f_x\) --- суммируема на \(Y\) при почти всех \(x\)
2. \(x \mapsto \varphi(x) = \int_Y fx\,d\nu = \int_Y f(x, y)\,d\nu(y)\) --- суммируема на \(Y\)
3. \(\int\limits_{X \times Y} f\,dm = \int\limits_X \varphi\,d\mu = \int_X \left(\int_Y f(x, y) d\nu(y)\right) d\mu(x)\)
#+end_theorem
#+begin_proof org
\color{green}Без доказательства\color{black}
#+end_proof
\todo
* Поверхностные интегралы
** Поверхностные интегралы I рода
#+begin_definition org
\(M \subset \R^3\) --- простое двумерное гладкое многообразие. \(\varphi: G \subset \R^2 \to \R^3\) --- параметризация. \(E \subset M\) --- измеримо по Лебегу, если \(\varphi^{-1}(E)\) измеримо в \(\R^2\) по Лебегу
#+end_definition
#+begin_symb org
\(\A_M = \{E \subset M | E\text{ --- измеримо}\} = \{\varphi(A) | A \in \M^2,\ A \subset G\}\)
#+end_symb
#+begin_definition org
Мера на \(\A_M\) \[S(E) := \iint\limits_{\varphi^{-1}(E)} | \varphi'_u \times \varphi'_v |\,dudv\]
Т.е. это взвешенный образ меры Лебега при отображении \(\varphi\)
#+end_definition
#+begin_remark org
\(\A_M\) --- \(\sigma\)-алгебра, \(S\) --- мера
#+end_remark
#+begin_remark org
\(E \subset M\) --- компактное \(\Rightarrow\ \varphi^{-1}(E)\) --- компактное \( \Rightarrow \) измеримое \( \Rightarrow \) замкнутые множества измеримы \( \Rightarrow \) (относительно) открытые множества измеримы
#+end_remark
#+begin_remark org
\(\A_M\) не зависит от \(\varphi\) по теореме о двух параметризациях
#+end_remark
#+begin_remark org
\(S\) не зависит от \(\varphi\)
\[ |\overline{\varphi'_s}\times\overline{\varphi'_v}| = |(\overline{\varphi'_s}\cdot u'_s + \overline{\varphi'_v}\cdot v'_s) \times (\overline{\varphi'_u}\cdot u'_t + \overline{\varphi'_v}\cdot v'_t)| = \]
\[ = | \overline{(\varphi'_u \times \varphi'_v)}\cdot(u'_s\cdot v'_t - v'_s\cdot u'_t)| = \todo \]
#+end_remark
#+begin_remark org
\-
- \(f: \M \to \overline{R} \) --- измеримая
\(M(f<a)\) --- измеримая \(\Leftrightarrow\) \(N(f\circ\varphi<a)\) --- измерима относително \(\M^2\) \\
\(f\) --- измерима относительно \(\A_M\) \(\Leftrightarrow\) \(f \circ \varphi\) --- измерима относительно \(\M^2\)
#+end_remark
#+ATTR_LATEX: :options [поверхностный интеграл I рода]
#+begin_definition org
\-
- \(M\) --- простое гладкое двумерное иногообразие в \(\R^3\)
- \(\varphi\) --- параметризация
- \(f: M \to \overline{R}\) --- суммируема по мере \(S\)
То \[ \iint\limits_M f\,ds = \iint\limits_M f(x, y, z)\,ds \]
называется *интегралом I рода от \(f\) по многообразию \(M\)*
#+end_definition
#+begin_remark org
По теореме об интегрировании по взвешенному образу меры
\[ \iint\limits_M f\,ds = \iint\limits_G f(\varphi(u, v)) |\varphi'_v \times \varphi'_v|\,dudv \]
\[ \varphi'_u \times \varphi'_v = \begin{pmatrix}
i & x'_u & x'_v \\
j & y'_u & y'_v \\
k & z'_u & z'_v
\end{pmatrix}\]
\[ |\varphi'_u \times \varphi'_v| = |\varphi'_u| \cdot |\varphi'_v|\sun\alpha = \sqrt{|\varphi'_u|^2 \cdot |varphi'_v|^2 \cdot (1 - \cos^2\alpha)} = \sqrt{EG - F^2} \]
\[ E = |\varphi'_u| = x'_u^2 + y'_u^2 + z'_u^2 \]
\[ F = \langle \varphi'_u, \varphi'_v \rangle = x'_ux'_v + y'_uy'_v + z'_u z'_v \quad F = |\varphi'_v|^2 \]
#+end_remark

