#+setupfile: setup.org
#+TITLE: Лекция 8
#+date: 25 октября

#+begin_definition org
... если при этом изменяется среднее значение другой случайной
величины, то зависимость называется *корреляционной*. Если среднее значение
увеличивается то --- /прямая корреляция/, а если уменьшается --- /обратная/
#+end_definition

* Кореляионное облако
Пусть в ходе эксперимента появились значения случайных величина
\((x_i, y_i)\), \(i \le i \le n\). Вынося эти точки на координатную
плоскость \(xOy\), получим *корреляционное облако*. По его виду можно
сделать предположение о зависимости.

#+begin_examp org
Если \(x, y\) имеют нормальное распределение с одинаковыми
параметрами. Если видимо /эллипс/, то скорее всего есть прямая корреляция
#+end_examp
* Кореляционная таблица
\((x_i, y_i\) представляем в виде таблицы. По горизонтали значения
\(y\), по вертикали --- \(x\). В каждой клетке количество появления
соответствующей точки.

Для большие наборов данные часто удобно строить интервальную корреляционную таблицу
* Критерий \(\chi^2\) для проверки независимости
\todo
- \(H_0\): \(X, Y\) --- независимы
- \(H_1\): \(X, Y\) --- зависимы
Согласно определению независимых случайных величин, если гипотеза
\(H_0\) верна, то вероятность попадания пары \(X, Y\) в любой
прямоугольник равна произведению теоретических вероятностей попасть в
эти интервалы. Т.е
\[ P_V = P(X \in [a_{i - 1}, a_i], Y \in [b_{j - 1}, b_j]) = P(X \in [a_{i - 1}, a_i])\cdot P(Y \in [b_{j - 1}, b_j]) = p_i \cdot p_j \]
По закону больших чисел, при \(n \to \infty\)
\[ \frac{V_i}{n} \xrightarrow{p} p_i,\ \frac{V_j}{n} \xrightarrow{p} p_j \quad \frac{V_{ij}}{n} \xrightarrow{p} p_{ij} \]
Основанием для отклонения гипотезы служит заметная разница между
\(\frac{V_{ij}}{n}\) и \(\frac{V_i}{n}\cdot\frac{V_j}{n}\), т.е. между
\(V_{ij}\) и \(\frac{V_i V_j}{n}\). В качестве статистики критерия
берется функция
\[ \todo \]
* Общая межгрупповая и внутригрупповая дисперсия
Для каждой выборки вычислим ее выборочное среднее и дисперсию:
\[ \todo \]
Объединив все данные в одну общую выборку, получим выборку объема \(n
= n_1 + n_2 + \dots + n_k\). Вычислим общее выборочное среднее. Вычислим
\[ \todo \]

#+begin_definition org
*Внутригрупповой* остаточной дисперсией называется среднее /групповых дисперсий/:

\[ \todo \]
#+end_definition

#+begin_definition org
*Межгрупповой* факторной дисперсией называется величина:
\[ \todo \]
#+end_definition

*Смысл*: внутригрупповая дисперсия показывает средний разбор внутри
выборки. Межгрупповая дисперсия показывает, насколько отличны
выборочные средние при различный уровня фактора. Таким образом ее
величина в общей сумме отражает влияние фактора

* Проверка гипотезы о влиянии фактора
Предположим, что случайная величина \(X\) имеет нормальное
распределение, и фактор \(Z\) может влиять только на ее математическое
ожидание, но не на дисперсию и не на распределение

\todo

