#+SETUPFILE: setup.org
#+TITLE: ДЗ 1

#+begin_task org
Из чисел от \(1\) до \(2n\) выбрано \(n + 1\) число. Докажите, что среди выбранных
чисел найдутся по крайней мере два взаимно простых числа.
#+end_task
#+NAME: gcd_seq_lemma
#+begin_lemma org
\(\forall n\ \text{НОД}(n, n + 1) = 1\)
#+end_lemma
#+begin_proof org
Пусть \(n = p_1 \cdot p_2 \cdot \dots \cdot p_k\), где p_i -- простое число. Тогда \(n + 1= p_1 \cdot p_2 \cdot \dots \cdot p_k + 1\) и \(\forall p_i\ (n + 1) \bmod p_i = 1\).
Получается, что \(n\) и \(n + 1\) не имеют общих простых делителей \(\implies\) \(\text{НОД}(n, n + 1) = 1\).
#+end_proof
#+begin_proof org
Разобъем множество \(\{1, 2, \dots, 2n\} = \bigsqcup_{1 \le i \le n} \{2i - 1, 2i\}\):
\[ \{1, 2\}, \{3, 4\}, \dots, \{2n - 1, 2n\} \]
получим \(n\) "ящиков". По принципу Дирихле из \(n + 1\) чисел хотя бы \(2\) попадут в один "ящик". Т.е. \(\exists k_1, k_2: k_1 + 1 = k_2\ \text{НОД}(k_1, k_2) = 1\) по [[gcd_seq_lemma][Лемме]].
#+end_proof

-----

#+begin_task org
Десять студентов за одно занятие решили 35 задач. Известно, что среди
студентов есть те, кто решил ровно одну задачу, ровно две задачи и ровно три задачи.
Докажите, что среди десяти студентов найдется хотя бы один студент, решивший как
минимум пять задач.
#+end_task
# #+begin_proof org
# Пусть все студенты решили меньше \(5\) задач. Тогда максимальное кол-во задач \(N\), которое могли решить \(10\) студентов:
# \[ N = 1 + 2 + 3 + (10 - 3) \cdot 4 = 34 \]
# Однако всего задач \(35\). _Противоречие_. Значит существует студент, который решил не меньше \(5\) задач.
# #+end_proof
#+begin_proof org
Известно что есть хотя бы по одному студенту, которые решили 1, 2, 3 задачи. Т.е. остальные 7 студентов решили \(35 - 1 - 2 - 3 = 29\) задач. По принципу Дирихле
в общем виде \(29 > 4 \cdot 7 = 28 \implies\) существует студент, решивший \(4 + 1 = 5\) задач. 
#+end_proof



-----

#+begin_task org
Узлы бесконечной клетчатой бумаги покрашены в два цвета. Докажите,
что существуют две горизонтальные и две вертикальные прямые, на пересечениях
которых лежат точки, покрашенные в один и тот же цвет
#+end_task
#+begin_proof org
Пусть \(C = 2\) -- количество цветов. Возьмем произвольные \(C + 1\) вертикальные прямые. Они определяют бесконечное множество из наборов точек размера \(C + 1\), по строкам. Всего вариантов раскрасок \(C + 1\) точек \(2^{C + 1}\). По принципу Дирихле (\(\infty > 2^{C + 1}\))
из бесконечного множества наборов найдутся хотя бы 2 одинаковых. Эти два набора определяют 2 искомые горизонтальные прямые. В этой раскраске набора точек по принципу Дирихле (\(C + 1 > C\))
найдутся 2 одинаково раскрашенные. Они задают 2 искомые вертикальные прямые.
#+end_proof


-----

#+begin_task org
Докажите, что в любой выборке из 52 положительных целых чисел найдутся хотя бы два, у которых либо их сумма, либо их разность делится на 100.
#+end_task
#+begin_proof org
Разобъем множество \(\N = \bigsqcup_{0 \le m \le 50} \{n \big| n \bmod 100 = m \lor n \bmod 100 = 100 - m\}\):
\[ \{1, 99, 101, 199, \dots\}, \{2, 98, 102, 198, \dots\}, \dots, \{49, 51, 149, 151, \dots\}, \{50, 150, 250, \dots\} \]
получим 51 "ящик". По принципу Дирихле из 52 чисел хотя бы 2 попадут в один "ящик". Т.е. \(\exists k_1, k_2\) и соответсвующее \(m\), такие что:
1. \(k_1 \bmod 100 = m, k_2 \bmod 100 = m\) или \(k_1 \bmod 100 = 100 - m, k_2 \bmod 100 = 100 - m\) и \(|k_1 - k_2| \bmod 100 = 0\)
2. \(k_1 \bmod 100 = m, k_2 \bmod 100 = 100 - m\) или \(k_1 \bmod 100 = 100 - m, k_2 \bmod 100 = m\) и \((k_1 + k_2) \bmod 100 = 0\)
Т.е. либо сумма либо разность делится на 100.
#+end_proof

-----

#+begin_task org
Футбольная команда за сезон отыграла 30 матчей и забила соперникам
в совокупности 53 гола. Известно, что в каждой игре команда забивала хотя бы
один гол. Докажите, что существует непрерывная последовательность игр, в течении
которой команда забила ровно шесть голов.
#+end_task
#+begin_proof org
Рассмотрим \(S_i\) -- сумма голов за первые \(i\) матчей. \(S_0 =0, S_{30} = 53\). При чем \(\forall i,j: i \neq j\ S_i \neq S_j\). Разобъем множество возможных значений \(S_i, S_i - 6\) \(\bigsqcup_{-6 \le i \le 53} \{i\}\):
\[ \{-6\}, \{-5\}, \dots, \{53\} \]
Получим \(53 - (-6) + 1 = 60\) "ящиков". По принципу Дирихле хотя бы 2 из 62 чисел \(\{S_i\}_i \cup \{S_i - 6\}_i\) попадут в один "ящик". Т.е. \(\exists i, j\ S_i = S_j - 6\). Тогда \(S_j - S_i = 6\). Т.е. сумма голов с \(i\)-й по \(j\)-ю игру равна 6.
#+end_proof

-----

#+begin_task org
(Неравенство Бернулли). Докажите, что \((1 + a)^n \ge 1 + na\) для любого вещественного \(a > - 1\) и для любого натурального \(n\).
#+end_task
#+begin_proof org
По индукции: \\
База: \(n = 1\)
\begin{align*}
(1 + a)^1 & \ge 1 + 1 \cdot a \\
1 + a & \ge 1 + a
\end{align*}
Переход: \(n \mapsto n + 1\)
\[ (1 + a)^n \ge 1 + na \]
Докажем что
\[ (1 + a)^{n + 1} & \ge^? 1 + (n + 1)a \]

\begin{align*}
(1 + a)^n & \ge 1 + na \qquad \cdot (1 + a) \\
(1 + a)^{n + 1} & \ge 1 + na + a + na^2 \ge \\
                & \ge 1 + na + a \qquad (na^2 \ge 0) \\
(1 + a)^{n + 1} & \ge 1 + (n + 1)a
\end{align*}
#+end_proof

---------

#+begin_task org
Докажите, что квадрат можно разрезать на \(n\) квадратов (не обязательно
одинаковых) для любого \(n \ge 6\).
#+end_task
#+begin_proof org
По индукции: \\
База:
#+begin_export latex
\begin{center}
\begin{array}{ccc}
\(n = 6\) & \(n = 7\) & \(n = 8\) \\

\begin{tikzpicture}
\draw (0, 0) rectangle (2, 2);
\draw (2, 0) rectangle (3, 1);
\draw (2, 1) rectangle (3, 2);
\draw (2, 2) rectangle (3, 3);
\draw (1, 2) rectangle (2, 3);
\draw (0, 2) rectangle (1, 3);
\end{tikzpicture} &

\begin{tikzpicture}
\draw (0, 0) rectangle (1, 1);
\draw (0, 1) rectangle (1, 2);
\draw (1, 0) rectangle (2, 1);
\draw (1, 1) rectangle (2, 2);
\draw (2, 0) rectangle (4, 2);
\draw (0, 2) rectangle (2, 4);
\draw (2, 2) rectangle (4, 4);
\end{tikzpicture} &

\begin{tikzpicture}
\draw (0, 0) rectangle (3, 3);
\draw (3, 0) rectangle (4, 1);
\draw (3, 1) rectangle (4, 2);
\draw (3, 2) rectangle (4, 3);
\draw (3, 3) rectangle (4, 4);
\draw (2, 3) rectangle (3, 4);
\draw (1, 3) rectangle (2, 4);
\draw (0, 3) rectangle (1, 4);
\end{tikzpicture}

\end{array}
\end{center}
#+end_export
Переход: \(n \mapsto n + 3\) \\
Разрежем один из квадратов в квадрате разрезанном на \(n\) квадратов таким образом:
#+begin_export latex
\begin{center}
\begin{tikzpicture}
\draw (0, 0) rectangle (2, 2);
\draw[dashed] (1, 0) -- (1, 2);
\draw[dashed] (0, 1) -- (2, 1);
\end{tikzpicture}
\end{center}
#+end_export
Получим квадрат, разрезанный на \(n - 1 + 4 = n + 3\) квадратов
 
#+end_proof

