#+SETUPFILE: setup.org
#+TITLE: ДЗ 3

#+begin_task org
Докажите комбинаторно, что для всех
целых \(n \ge m \ge k \ge 0\) справедливо равенство
\[ \binom{n}{m} \cdot \binom{m}{k} = \binom{n}{k} \cdot \binom{n - k}{m - k} \]
#+end_task
#+begin_solution org
Задача: Есть \(n\) белых шаров. Нужно покрасить k в красно-черный и \(m - k\) в черный.
1. Выберем из всех \(n\) шаров \(m\) и покрасим их в черный. Затем выберем из этих \(m\) шаров \(k\) штук и докрасим красным:
   \[ \binom{n}{m} \cdot \binom{m}{k} \]
2. Выберем \(k\) шаров и покрасим их красно-черным. Затем их оставшихся выберем \(m - k\) и покрасим в черный:
   \[ \binom{n}{k} \cdot \binom{n - k}{m - k} \]
#+end_solution

-----

#+begin_task org
Докажите комбинаторно следующее тождество:
\[ \multiset{n + 1}{k} = \sum_{i = 0}^k \multiset{n}{k - i} \]
#+end_task
#+begin_solution org
Задача: Есть \(k\) шаров и \(n + 1\) корзин. Нужно разложить шары по корзинам.
1. Выберем \(k\) корзин в которые положим шары. В корзину можно положить несколько шаров:
   \[ \multiset{n + 1}{k} \]
2. Зафиксируем одну корзину. Рассмотрим кол-во способов разложить шары по оставшимся \(n\) корзинам, не положив ни одного в зафиксированную, положив 1 в зафиксированную, \(\dots\), положив \(k\) в зафиксированную. Проссумируем их:
   \[ \sum_{i = 0}^k \multiset{n}{k - i} \]
#+end_solution

------

#+begin_task org
«Хромая ладья» может ходить только на одну клетку вверх или на одну клетку вправо. Изначально она стоит в нижнем левом углу
клетчатой доски размером \((2n + 1) \times (2m + 1)\) клеток
#+end_task

#+ATTR_LATEX: :options {a}
#+begin_manualtask org
Сколькими способами «хромая ладья» может дойти до правого верхнего угла доски?
#+end_manualtask
#+begin_solution org
Ладья должна сделать ровно \(2n + 1\) шагов по вертикали и \(2m + 1\) шагов по горизонтали. Можно представить как список из \(2n + 2m + 2\) элементов, где каждый элемент это либо шаг вверх либо вправо. Подсчитаем количество способов расставить \(2n + 1\) шагов вверх по \(2n + 2m + 2\) местам. Остальные места займут шаги вправо:
\[ \binom{2n + 2m + 2}{2n + 1} \]
#+end_solution
#+ATTR_LATEX: :options {b}
#+begin_manualtask org
Хулиган Вася вырезал из этой доски центральную клетку. Сколько способов теперь?
#+end_manualtask
#+begin_solution org
Нужно вычесть кол-во путей до центральной клетки из общего числа путей, тогда останутся только пути, которые не проходят через центральную клетку. По аналогии посчитаем это количество:
\[ \binom{n + m + 2}{n + 1} \]
Тогда ответом будет:
\[ \binom{2n + 2m + 2}{2n + 1} - \binom{n + m + 2}{n + 1} \]
#+end_solution

-----

#+begin_task org
Найдите количество упорядоченных размещений \(k\) различимых предметов
по n различимым ящикам, то есть таких размещений, в которых важен порядок
размещения предметов в каждом конкретном ящике.
#+end_task
#+begin_solution org
Для начала заметим что если известно сколько предметов в каждом ящике, то количество различных способов разложить предметы по ящикам с учетом порядка будет равно количеству перестановок всех предметов. Т.к. перестановка в этом случае однозачно определяет в каком ящике будет лежать предмет (раскладываем по порядку в ящики) и какой будет порядок в самих ящиках.

Теперь посчитаем количество способов разложить ``одинаковые`` предметы по ящикам, т.е. определить количество предметов в каждом ящике: \(\multiset{n}{k}\) -- выбираем ящик для каждого предмета. Теперь добавим порядок домножив на кол-во перестановок всех предметов:
\[ \multiset{n}{k} \cdot k! \]
#+end_solution


------


#+ATTR_LATEX: :options {6}
#+begin_manualtask org
Вспомним задачу про фитнес-клуб из прошлого ДЗ. Каким будет ответ,
если друзья заранее договорились, что не должно остаться группового занятия, на
которое не ходит ни один из них?
#+end_manualtask
#+begin_solution org
Нужно вычесть из общего числа вариантов количество вариантов, в которых на некоторые занятия никто не записался. Посчитаем такие варианты.
Пусть \(A_i\) -- никто не записался на занятие \(i\). Для любого \(i\) количество вариантов \(A_i\) будет равняться \((2^3 - 1)^6\) -- по аналогии с общим кол-вом, только выбрать можно на одно занятие меньше. Аналогично можно посчитать кол-во вариантов \(A_i \land A_j\), оно равно \((2^2 - 1)^6\). Для 3х не выбранных занятий \((2^1 - 1)^6\), для 4х \(0\).
Теперь можно посчитать кол-во вариантов \(A_1 \lor A_2 \lor A_3 \lor A_4\):
\begin{gather}
  \binom{4}{1} \cdot (2^3 - 1)^6 - \binom{4}{2} \cdot (2^2 - 1)^6 + \binom{4}{3} \cdot (2^1 - 1)^6 - \binom{4}{4} \cdot 0 = \\
  4 \cdot 117649  - 6 \cdot 729 + 4 \cdot 1 = 466226
\end{gather}
Возьмем общее число вариантов из предыдущего ДЗ:
\[ 11390625 - 466226 = 10924399 \]
#+end_solution





