#+LATEX_CLASS: general
#+TITLE: Лекция 6
#+AUTHOR: Ilya Yaroshevskiy

* Постановка задачи
1. 
   \( x^* = (x_1, x_2, \dots, x_n)^T,\ x_i \in U \subset E_n \), где \( U
   \) --- множество допустимых значений, \( E_n \) --- эвклидово
   пространство размера \(n\). \(f(x^*) = \min_{x \in U} f(x)\). Если
   ствится задача найти максимум, то млжно перейти к поиску минимума: \( f(x^*) = \max_{x\in U}f(x) = -\min_{x \in U}(-f(x))\)
2. \( f(x^*) = \text{extr}_{x \in U}f(x)\)
3. Если \(U\) задается ограничением на вектор \(x\), то задача поиска
   условного экстремума. Если \( U = E_n\) --- не имеет ограничений,
   то задача поиска безусловного экстремума
4. Решение задачи поиска экстремума --- пара \((x^*, f(x^*))\)
-----
Если \(\forall x \in U\ f(x^*) \le f(x)\) --- то \(x^*\) --- глобальный минимум. Локальный минимум \(x^* \in U\): если \(\exists \varepsilon > 0\), что \(\forall x \in U\) и \(\Vert x - x^* \Vert < \varepsilon\), то \(f(x^*) \le f(x)\)
#+begin_definition org
*Поверхностью уровня* функции \(f(x)\) называется множество точек, в которых функция принимает постоянные значения, т.е. \(f(x) = \const\)
#+end_definition
#+begin_definition org
*Градиентом* \nabla f(x) непрерывно жифференцируемой функции \(f(x)\) в x:
\[ \nabla f(x) = \left(\begin{array}{c} \frac{\partial f(x)}{\partial x_1} \\ \frac{\partial f(x)}{\partial x_2} \\ \vdots \\ \frac{\partial f(x)}{\partial x_n}\end{array}\right) \]
Градиент направлен по нормали к поверхности уровня, т.е. перпендикулярно к касательной плоскости в точке \(x\), проведенной в сторону наибольшего возрастания функции
#+end_definition
#+begin_definition org
*Матрицей Гессе* \(H(x)\) дважды непрерывно дифференцируемой в точке
\(x\) функции \(f(x)\) называется матрица частных производных второго
порядка, вычисленных в данной точке.
\[ H(x) = \left( \begin{array}{cccc} \frac{\partial^2 f(x)}{\partial x_1^2} & \frac{\partial^2 f(x)}{\partial x_1x_2} & \dots & \frac{\partial^2 f(x)}{\partial x_1x_n} \\ \vdots & \vdots & \ddots & \vdots \\ \frac{\partial^2 f(x)}{\partial x_nx_1} & \frac{\partial^2 f(x)}{\partial x_nx_2} & \dots & \frac{\partial^2 f(x)}{\partial x_n^2} \end{array}\right) \]
#+end_definition
1. \(H(x)\) --- симметричная, размер \(n \time n\)
2. Антиградиент: вектор, равный по модулю вектору градиента, но противоположный по направлению. Указывает в сторну наибольшего убывания функции \(f(x)\)
3. \[ \nabla f(x) = f(x + \Delta x) - f(x) = \nabla f(x)^T\Delta x + \frac{1}{2} \Delta x^T H(x)\Delta x + o(\Vert \Delta x \Vert^2) \]
   \(o(\Vert \Delta x \Vert^2)\) --- сумма всех членов разложения, имеющих порядок выше второго, \(\Delta x^T H(x) \Delta x\) --- квадратичная форма
** Свойства квадратичных форм
Квадратичная форма \(\Delta x^T H(x) \Delta x\) (и соответсвующая матрица \(H(x)\)) называется:
- положительно опрделенной \(H(x) > 0\), если \(\forall \Delta x \neq 0\ \Delta x^T H(x) \Delta x > 0\)
- отрицательно определенной \(H(x) < 0\), если \(\forall \Delta x \neq 0\ \Delta x^T H(x) \Delta x < 0\)
- положительно полуопределенной \(H(x) \ge 0\), если \(\forall \Delta x \neq 0\ \Delta x^T H(x) \Delta x \ge 0\)
  и имеется \(\Delta x \neq 0: \Delta x^T H(x) \Delta x = 0\)
- отрицательно полуопределенной \(H(x) \le 0\), если \(\forall \Delta x \neq 0\ \Delta x^T H(x) \Delta x \le 0\)
  и имеется \(\Delta x \neq 0: \Delta x^T H(x) \Delta x = 0\)
- неопределнной, если \(\exists \Delta x, \Delta \tilde{x}: \Delta x^T H(x) \Delta x > 0,\ \Delta \tilde{x}^T H(\tilde{x}) \Delta \tilde{x} < 0\)
- тождественно равной нулю \(H(x) \equiv 0\), если \(\forall \Delta x\ \Delta x^T H(x) \Delta x = 0\)
** Свойства выпуклых множеств и выпуклых функций
#+begin_definition org
Пусть \(x, y \in E_n\). Множество точек вида \(\{z\} \subset E_n: z = \alpha x + (1 - \alpha)y\), \( \alpha \in [0, 1]\), \(z\) --- отрезок, соединяющий \(x\) и \(y\).
#+end_definition
#+begin_examp org
\(E_n: n \le 3\): \(z\) --- отрезок(обычный)
#+end_examp
#+begin_definition org
\(U \subset E_n\) выпуклое, если вместе с точками \(x\) и (y \in U) оно содержит и весь отрезок \(z = \alpha x + (1 - \alpha)y, \alpha \in [0, 1]\)
#+end_definition
#+begin_definition org
Функция \(f(x)\), заданая на выпуклом \(U \subset E_n\) называется:
- выпуклой, если \(\forall x, y \in U\) и \(\forall \alpha [0, 1]\) выполняется \(f(\alpha x + (1 - \alpha)y) \le \alpha f(x) + (1- \alpha)f(y)\)
- строго выпуклой, если \(\forall \alpha \in (0, 1)\) выполняется \(f(\alpha x + (1 - \alpha)y) < \alpha f(x) + (1-\alpha)f(y)\)
- сильно выпуклой с константой \(l > 0\), если \(\forall x, y \in U\) и \(\forall \alpha \in [0, 1]\) выполняется \(f(\alpha x + (1 - \alpha)y) \le \alpha f(x) + (1- \alpha) f(y) - \frac{l}{2}\alpha(1 - \alpha)\Vert x - y \Vert^2\)
#+end_definition
/Свойства:/
1. Функция \(f(x)\) _выпуклая_, если ее грфик целиком лежит не выше отрезка, соединяющего две ее произвольные точки \\
   Функция \(f(x)\) _строго выпуклая_, если ее график лежит целиком ниже отрезка, соединяющего две ее произвольные, но не совпадающие точки
2. Если функция \(f(x)\) _сильно выпуклая_, то она одноверменно строго выпуклая и выпуклая \\
   Если функция \(f(x)\) _строго выпуклая_, то она одновременно выпуклая
3. Выпуклость функции можно определить по матрице Гессе \(H(x)\)
   - Если \(H(x) \ge 0\ \forall x \in E_n\), то \(f(x)\) выпуклая
   - Если \(H(x) > 0\ \forall x\in E_n\), то \(f(x)\) строго выпуклая
   - Если \(H(x)\ \ge lE\ \forall x \in E_n \), где \(E\) --- единичная матрица, то \(f(x)\) сильно выпуклая
/Свойства выпуклых функций:/
1. Если f(x) выпуклая функция на выпуклом множестве \(U\), то всякая точка локального минимума есть точка глобального минимума на \(U\)
2. Если выпуклая функция достигает своего минимума в двух различных точках, то она достигает миниума во всех точках отрезка, соединяющих это точки.
3. Если \(f(x)\) строго выпуклая функция множества \(U\), то она может достигать своего глобального минимума на \(U\) не более чем в одной точке
** Необходимое и достаточное условие безусловного экстремума
#+ATTR_LATEX: :options [Необходимое условие экстремума первого порядка]
#+begin_theorem org
Пусть \(x^* \in E_n\) --- локальный минимум или максимум \(f(x)\) на \(E_n\) и \(f(x)\) --- дифференцируема в точке \(x^*\) \\
_Тогда_ \(\nabla f(x)\) в точке \(x^*\) равен нулю \(\nabla f(x^*) = 0\), т.е.
\[ \frac{\partial f(x^*)}{\partial x_i} = 0,\ i = \overline{1, n} \]
#+end_theorem
#+begin_definition org
Точки \(x^*: \nabla f(x^*) = 0\) --- *стационарные*
#+end_definition
#+ATTR_LATEX: :options [Необходимое условие экстремума второго порядка]
#+begin_theorem org
Пусть \(x^* \in E_n\) --- точка локального минимума или максимума \(f(x)\) на \(E_n\) и \(f(x)\) --- дважды дииференцируемая в точке. \\
_Тогда_ \(H(x^*)\) --- является положительно или отрицательно(если максимум) полуопределенной, т.е. \(H(x^*) \ge 0\) или \(H(x^*) \le 0\)(если максимум)
#+end_theorem
#+ATTR_LATEX: :options [Достаточное условие экстремума]
#+begin_theorem org
Пусть \(f(x)\) в \(x^* \in E_n\) дважды дифференцируема, ее \(\nabla f(x) = 0\), а \(H(x^*) > 0\) или \(H(x^*) < 0\)(для максимума). \\
_Тогда_ \(x^*\) --- точка локального минимума(максимума) \(f(x)\) на \(E_n\)
#+end_theorem
*** Проверка выполнения условий
- вычисление угловых миноров \(H(x)\)
- вычисление главных миноров \(H(x)\) \\


1. Ислледование положительной или отрицательной определнности угловых и главных миноров 
2. Анализ собственных значений матрицы \(H(x)\)
