#+setupfile: setup.org
#+TITLE: Лекция 2
#+date: 17 февраля

* Полезность

#+begin_examp org
Рассмотри игру, похожую на покер. В данный момент есть две возможности -- играть или "спасовать". При игре сравниваются карты и в случае выигрыша мы получаем 90 рублей, в случае
проигрыша терям 60 рублей. Известно, что с вероятностью \(\frac{1}{3}\) мы выиграем. Альтернатива -- пасовать и потерять 20. Стоит ли играть?

Вычислим мат. ожидание:
\[ E = 90 \cdot \frac{1}{3} + (- 60) \cdot \farc{2}{3} = -10 > 20 \]
Хороший ли это критерий?
#+end_examp

#+begin_examp org
На выбор:
1. Получить 1 млн
2. Получить 2 млн с вероятностью \(\frac{1}{2}\)
\[ E(A) = E(B) \]
Действительно ли эти варианты эквивалентны?
#+end_examp

#+begin_examp org
Игра в рулетку
| Вероятность | \(\frac{1}{2}\) | \(\frac{1}{4}\) | \(\frac{1}{8}\) | \(\frac{1}{16}\) | \(\dots\) |
| Выигрыш     |               2 |               4 |               8 |               16 | \(\dots\) |

\[ E = \frac{1}{2} \cdot 2 + \frac{1}{4} \cdot 4 + \frac{1}{8} \cdot 8 + \dots = \sum_{i = 1}^\infty 1 = \infty \]
За возможность сыграть -- любые деньги?
#+end_examp

#+begin_rem org
Мат. ожидание -- плохой критерий.
#+end_rem

#+begin_definition org
*Полезность* -- мера удовлетворения агента.
#+end_definition

#+begin_rem org
Предположение -- для каждого агента существует функция полезности и он стремится максимизировать ее мат. ожидание.
#+end_rem

#+begin_definition org
\(X\) -- множество альтернатив (событий). \\
Операция:
\[ A, B \in X \implies \alpha A + (1 - \alpha) B \in X \]
Отношения:
\[ \succ, = \]
- \(A \succ B\): \(A\) предпочтительнее \(B\)
- \(A = B\): не имеет мести ни \(A \succ B\), ни \(B \succ A\)
У агента задано *отношение предпочтения*.
#+end_definition

#+begin_axiom org
*Аксиома полноты*. \(\forall A, B\) верно одно из трех:
- \(A \succ B\)
- \(B \succ A\)
- \(A = B\)
#+end_axiom

#+begin_axiom org
*Аксиома порядка (транзитивности)*.
\[ A \succ B, B \succ C \implies A \succ C \]
#+end_axiom


\(A \succ B \implies A\) имеет большую полезность, чем B. Как определить разницу этих событий? Вводится понятие риска
#+begin_definition org
Пусть \(A, B \in X, \alpha \in [0, 1]\)
\[ C = \alpha \cdot A + (1 - \alpha) \cdot B \]
\(C\) -- *лотерея*, которая имеет два исхода с определенными вероятностями
#+end_definition

#+begin_axiom org
*Аксиома непрерывности*. Пусть \(A, B, C \in X, A \succ B, B \succ C \implies)
\[ \exists \alpha \in (0, 1): (\alpha \cdot A + (1 - \alpha) \cdot C) \succ B \]
#+end_axiom

#+begin_axiom org
*Аксиома независимости от несущественных альтернатив (АННА)*. Если \(A \succ B \implies\)
\[ \forall C \alpha \cdot A + (1 - \alpha) \cdot C \succ \alpha B + (1 - \alpha) \cdot C \]
#+end_axiom


#+ATTR_LATEX: :options [Теорема об ожидаемой полезности (теорема фон Неймана)]
#+begin_theorem org
Если отношение предпочтения удовлетворяет аксиомам 1 - 4, тогда существует такая функция \(U\), что предпочтение задается ее математическим ожиданием.
При этом функция \(U\) определена с точностью до положительного аффинного преобразования:
\[ \forall x, y \in \Delta X, \exists U: \Delta X \to R: \quad x \succ y \Leftrightarrow EU(x) > EU(y) \]
, где \(\Delta X\) -- множество лотерей
#+end_theorem

#+begin_definition org
*Нормальная форма игры*
\[ G = \{N, \{X_i\}_{i \in N}, \{K_i\}_{i \in N}\} \]
- \(N\) -- конечное множество игроков
- \(X_i, i \in N\) -- множество стратегий игрока \(i \in N\)
- \(K_i: \prod_{i \in N} X_i \to R\) -- функция выигрыша игрока \(i \in N\)
#+end_definition

#+begin_definition org
или игры с противоположными интересами (с нулевой суммой) \\
или матричные игры

Конечная антагонистическая игра задается матрицей \(n \times m\)
\[ A = \begin{pmatrix} a_{11} & \dots & a_{1n} \\ \vdots & \ddots & \vdots \\ a_{m1} & \dots & a_{mn} \end{pmatrix} \]
- \(a_{ij} = K_1(i, j)\) -- выигрыш первого игрока
- \(X_1 = \{1, \dots, n\}\) -- стратегии первого игрока
- \(X_2 = \{1, \dots, m\}\) -- стратегии второго игрока
\[ K_1(i, j) + K_2(i, j) \equiv 0 \forall i \in X_1, j \in X_2 \]
#+end_definition


#+begin_examp org
Орел - решка
#+ATTR_LATEX: :align c|cc
| (I, II) | Орел      | Решка     |
|---------+-----------+-----------|
| Орел    | \(1, -1\) | \(-1, 1\) |
| Решка   | \(-1, 1\) | \(1, -1\) |
#+end_examp

#+begin_examp org
Камень-Ножницы-Бумага
#+ATTR_LATEX: :align c|ccc
| (I)     | Камень | Ножницы | Бумага |
|---------+--------+---------+--------|
| Камень  | \(0\)  | \(1\)   | \(-1\) |
| Ножницы | \(-1\) | \(0\)   | \(1\)  |
| Бумага  | \(1\)  | \(-1\)  | \(0\)  |
#+end_examp

#+begin_examp org
*Дилема заключенного*.

Два мошенника арестованы в связи с преступлением. Однако оказывается, что если никто из них не сознается, их осудят лишь за более мелкое правонарушение.
Поэтому полиция делает каждому из арестованных одно и то же предложение (но в разных комнатах, так что они не имеют возможность обсудить вопрос между собой):
если вы сознаетесь, что вы вдвоем совершили серьезное преступление, а ваш приятель не сознается, то вас освободят, а ваш напарник будет заключен в тюрьму на 6 лет;
если вы оба сознаетесь, то оба получите по 4 года; если ни один из вас не сознается, то вы оба проведете в тюрьме 2 года за совершение более мелкого преступления.


#+ATTR_LATEX: :align c|ccc
| (I, II)      | Сознаться | Не сознаться |
|--------------+-----------+--------------|
| Сознатья     | \(-4, 4\) | \(0, 6\)     |
| Не сознаться | \(-6, 0\) | \(-2, 2\)    |
#+end_examp

#+begin_definition org
*Осторожные стратегии*. Выбираем стратегию так, чтобы минимизировать свой возможный проигрыш.

\[ \max_i \min_j a_{ij} \le \min_j \max_i a_{ij} \]
- \(\alpha = \max_i \min_j a_{ij}\) -- нижная цена игры
- \(\beta = \min_j \max_i a_{ij}\) -- верхная цена игры

Если \(\max_i \min_j a_{ij} = \min_j \max_i a_{ij} = v\), то есть седловая точка, а \(v\) -- цена игры
#+end_definition
#+begin_examp org
\[ A = \begin{pmatrix} 1 & 2 & 0 & -3 \\ 2 & -1 & -1 & -1 \\ -2 & 0 & 0 & 1 \\ 4 & 1 & 0 & -2 \end{pmatrix} \]
Первый в строке, второй в столбце. Для первого лучшая 2 для второго 3 (т.к. с минусом).
#+end_examp
#+begin_examp org
\[ A = \begin{pmatrix} 3 & 2 & 1 & 4 \\ 10 & 4 & 3 & 10 \\ -2 & 4 & 1 & 2 \end{pmatrix} \]
\[ \max_i \min_j a_{ij} = \max \{1, 3, -2\} = 3 \quad \min_j \max_i a_{ij} = \min \{10, 4, 3, 10\} = 3 \]
Цена игры -- \(3\)
#+end_examp


** Доминирование стратегий
#+begin_examp org
\[ A = \begin{pmatrix} 2 & 1 & 1 & 0 \\ 2 & 3 & 1 & 3 \\ 3 & 1 & 2 & 0 \\ 0 & 3 & 0 & 6  \end{pmatrix} \]
Стратегия 2 доминирует стратегию 1. Какую бы стратегий не выбрал второй игрок, выигрышь в стратегии 2 всегда не меньше выигрыша стратегии 1
#+end_examp
#+begin_definition org
Говорят, что стратегия \(x'\) доминирует стратегию \(x''\) игрока 1 в \((m \times n)\)-игре \(G_A\), если для всех чистых стратегий \(j \in \{1, \dots, n\}\)
игрока 2 выполняются неравенства
\[ x' a^j \ge x'' a^j \]
Аналогично для 2 игрока:
\[ a_i y' \le a_i y'' \]
Стратегии эквивалентны, если \(x' a^j = x'' a^j\). Если \(x' \sim x''\), то \(K(x', y) = K(x'', y)\)
#+end_definition
#+begin_definition org
Стратегия \(s_1\) строго доминируется стратегией \(s_2\) того же игрока (или \(s_2\) строго доминирует \(s_1\)),
если для этого игрока всегда выгоднее применть стратегию \(s_2\), как бы не поступил оппонент.
\[ K_1(s_2, r) > K_1(s_1, r) \quad \forall r \in X_2, s_1, s_2 \in X_1 \]
#+end_definition
#+ATTR_LATEX: :options [о доминировании]
#+begin_theorem org
Если \(i\)-я стратегия доминируема, то \(i\)-я строка может быть вычеркнута из матрицы, при этом цена игры не изменяется, а оптимальная стратегия может быть
получена из новой оптимальной стратегии расширением на \(i\)-м месте

Если \(x = (\xi_1, \xi_2, \dots, \xi_m) \in X, i = \overline{1, m + 1}\), то расширением стратегии \(x\) на \(i\)-м месте будут называться вектор \(x_i = (\xi_1, \dots, \xi_{i - 1}, 0, \xi_{i + 1}, \dots, \xi_m) \in \R^{m + 1}\)
#+end_theorem


*** Метод исключения доминируемых стратегий
Все игроки разумны! Принцип всеобщего признания разумности
#+ATTR_LATEX: :align c|ccc
|   | 1    | 2    | 3    |
|---+------+------+------|
| 1 | 5, 0 | 5, 4 | 0, 3 |
| 2 | 0, 4 | 0, 3 | 5, 2 |

Вторая стратегия второго игрока доминирует третью
#+ATTR_LATEX: :align c|cc
|   | 1    | 2    |
|---+------+------+
| 1 | 5, 0 | 5, 4 |
| 2 | 0, 4 | 0, 3 |

Первая стратегия первого игрока доминирует вторую
#+ATTR_LATEX: :align c|cc
|   | 1    | 2    |
|---+------+------+
| 1 | 5, 0 | 5, 4 |

Вторая стратегия второго игрока доминирует первую
#+ATTR_LATEX: :align c|c
|   | 2    |
|---+------+
| 1 | 5, 4 |


Недостатки:
- Доминируемые стратегия не всегда есть

** Оптимальность по Парето
Ситуация \(x = (x_1, \dots, x_n)\) в игре \(G\) называется опимальной по Парето, если не существует такой ситуации \(y = (y_1, \dots, y_n)\), в которой
\[ K_i(y) \ge K_i(x) \quad \forall i \in N \]
и хотя бы для одного игрока это неравенство строго

#+begin_theorem org
В конечной бескоалиционной игре существуют оптимальные по Парето ситуации
#+end_theorem

#+begin_examp org
Дилема заключенного. Оптимальность по Парето

Профиль (не сознаться, не сознаться) эффективный (или оптимальный по Парето), если не существует другого исхода, который увеличил бы платеж
одного игрока, не ухудшив платеж другого


#+ATTR_LATEX: :align c|cc
| (I, II)      | Сознаться | Не сознаться         |
|--------------+-----------+----------------------|
| Сознаться    | -4, -4    | 0, -6                |
| Не сознаться | -6, 0     | \color{green} -2, -2 |
#+end_examp

Недостатки:
- *Множество* Парето оптимальных точек

** Равновесия по Нэшу
#+begin_definition org
\((x_1^*, x_2^*)\) -- равновесия по Нэшу, если
\[ K_1(x_1^*, x_2^*) \ge K_1 (x_1, x_2^*) \quad \forall x_1 \in X_1 \]
\[ K_2(x_1^*, x_2^*) \ge K_2 (x_1^*, x_2) \quad \forall x_2 \in X_2 \]

Ни один не может улучшить ситуацию для себя
#+end_definition

#+begin_examp org
Дилема заключенного:
#+ATTR_LATEX: :align c|cc
| (I, II)      | Сознаться          | Не сознаться |
|--------------+--------------------+--------------|
| Сознаться    | \color{red} -4, -4 | 0, -6        |
| Не сознаться | -6, 0              | -2, -2       |
\((-4, -4)\) -- ситуация равновесия.
#+end_examp


** Смешанные стратегии
#+begin_definition org
Смешанные стратегии -- вероятностное распределение на множестве его чистых стратегий
\[ x = \begin{pmatrix} x_1 \\ \vdots \\ x_m \end{pmatrix} , x_i \ge 0, \sum_{i = 1}^m x_i = 1 \]
Ожидаемый выигрыш 1 игрока
\[ K_1(x, y) = x^T A y = \sum_{i = 1}^m \sum_{j = 1}^n a_{ij} x_i y_j \]
#+end_definition

#+ATTR_LATEX: :options [о минимаксе, фон Нейман]
#+begin_theorem org
\-
\[ \max_x \min_y x^T A y = \min_y \max_x x^T A y \]
#+end_theorem

** Поиск равновесия по Нешу
#+ATTR_LATEX: :options [о равенстве платежей]
#+begin_lemma org
Пусть \(\sigma_R^* = (p^*, 1 - p^*)\) и \(\sigma_C^* = (q^*, 1 - q^*)\) задают ситуацию в игру двух игроков с двумя возможными стратегиями \(s_R^1, s_R^2\) и \(S_C^1, S_C^2\).
1. Если \(0 < p^* < 1\), то \(\sigma_R^*\) является лучшим ответом на \(\sigma_C^*\), т.е.
   \[ \forall \sigma_R\ K_R(\sigma_R^*, \sigma_C^*) \ge K_R(\sigma_R, \sigma_C^*) \Leftrightarrow K_R(s_R^1, \sigma_C^*) = K_R(s_R^2, \sigma_C^*) \]
   и, следовательно,
   \[ \forall \sigma_R K_R(\sigma_R^*, \sigma_C^*) = K_R(s_R^1, \sigma_C^*) = K_R(S_R^2, \sigma_C^*) = K_R(\sigma_R, \sigma_C^*) \]
2. Если \(0 < 1^* < 1\), то \(\sigma_C^*\) является лучшим ответом на \(\sigma_R^*\), т.е.
   \[ \forall \sigma_C\ K_C(\sigma_R^*, \sigma_C^*) \ge K_C(\sigma_R^*, \sigma_C) \Leftrightarrow K_C(\sigma_R^*, S_C^1) = K_C(\sigma_R^*, S_C^2) \]
   и, следовательно,
   \[ \forall \sigma_C K_C(\sigma_R^*, \sigma_C^*) = K_C(\sigma_R^*, S_C^1) = K_C(\sigma_R^*, S_C^2) = K_C(\sigma_R^*, \sigma_C) \]
3. Если \(0 < p^* < 1\) и \(0 < q^* < 1\), то \((\sigma_R^*, \sigma_C^*)\) является равновесием по Нэшу ттогда, когда
   \[ K_R(s_R^1, \sigma_C^*) = K_R(s_R^2, \sigma_C^*) \]
   и
   \[ K_C(\sigma_R^*, S_C^1) = K_C(\sigma_R^*, S_C^2) \]
   Выполняются одновременно
#+end_lemma

#+begin_examp org
Игра "Семейный спор". Муж и жена обсуждают, как провести свободный вечер. Они хотели бы провести его вместе, но муж хотел бы пойти в театр на балет, а жена на футбол.

Стоимость событий:
- "быть вместе" - 2 единицы
- "провести вечер по своему вкусу" - 1 единица

#+ATTR_LATEX: :align c|cc
| Муж / Жена | Футбол | Балет  |
|------------+--------+--------|
| Футбол     | (2, 3) | (0, 0) |
| Балет      | (1, 1) | (3, 2) |

\(\sigma_H^* = (p, 1 - p); \sigma_W^* = (q, 1 - q)\)
\[ A_H = \begin{pmatrix} 2 & 0 \\ 1 & 3  \end{pmatrix} A_W = \begin{pmatrix} 3 & 0 \\ 1 & 2  \end{pmatrix} \]
\todo
#+end_examp




