#+LATEX_CLASS: general
#+TITLE: Практика 5
#+AUTHOR: Ilya Yaroshevskiy

#+begin_task org
Брак при изготовлении детали состовляет 20%. Найти веротяность того что из 10 деталей не менее 3х годные.
#+end_task
#+begin_solution org
\[ n = 10;\ p = 0.8;\ q = 0.2;\ 3 \le k \le 10 \]
\[ P_{10}(3 \le j \le 10) = 1 - P_{10}(k < 3) = 1 - (P_{10}(0) + P_{10}(1) + P_{10}(2)) \approx 1 - (q^{10} + C^1_{10}\cdot p^1\cdot q^9 + C^2_{10}\cdot p^2\cdot q^8) = \]
\[ = 1 - (0.2^8 + 10\cdot0.8\cdot0.2^9 + 45\cdot0.8^2\cdot0.2^8) \approx 0.999 \]
#+end_solution
#+begin_task org
Найти вероятность того что при 180 бросаниях кости шестерка выпала 27 раз
#+end_task
#+begin_solution org
\[ P_{180}(27) = C^{27}_{180} p^{27} q^{180 - 27} = C^{27}_{180} \left(\frac{1}{6}\right)^{27}\cdot\left(\frac{5}{6}\right)^{180 - 27} \approx 0.069 \]
\[ P_{180}(27) = \frac{1}{\sqrt{180 \cdot \frac{1}{6}\cdot\frac{5}{6}}} \cdot \varphi\left(\frac{27 - 180\cdot \frac{1}{6}}{\sqrt{180\cdot\frac{1}{6}\cdot\frac{5}{6}}}\right) \approx 0.0666\]
#+end_solution
#+begin_task org
Брак составляет 20%. Найти вероятность того, что из 900
деталей бракованных будет от 170 до 200
#+end_task
#+begin_solution org
\[ x_1 = \frac{170 - 900\cdot0.2}{\sqrt{900\cdot0.2\cdot0.8}} \approx -0.83 \]
\[ x_2 = \frac{200 - 900\cdot0.2}{\sqrt{900\cdot0.2\cdot0.8}} \approx 1.67 \]
\[ P_{900}{170 \le k \le 200} \approx \Phi(x_1) - \Phi(x_2) \approx 0.4515 + 0.2967 = 0.7482\]
#+end_solution
* Формула Пуассона(формула редких событий)
Применяем при \( p < \frac{1}{10} \) или \( n \ge 100 \)
\[ P_n(k) \approx \frac{\lambda^k}{k!}e^{-\lambda} \], где \( \lambda = np \)
#+begin_examp org
Вероятность звонка в службу поддержки --- 0.2.  Найти вероятность
того, что из 100 человек в службу поддержки позвонили от 1 до 3
человек.
\[ n= 100;\ p = 0.02;\ \lambda = np = 100\cdot0.02 = 2;\ 1 \le x \le 3 \]
\[ P_{100}(1 \le k \le 3) = P_{100}(1) + P_{100}(2) + P_{100}(3) = \frac{2^1}{1!}e^{-2} + \frac{2^2}{2!}e^{-2} + \frac{2^3}{3!}e^{-2} = (2 + 2 + \frac{4}{3})e^{-2} \approx 0.7218 \]
#+end_examp
#+begin_task org
Вероятность клика по банеру на одной странице --- 0.005. Найти
вероятность того что на 1000 страниц будет 7 кликов по банеру
#+end_task
#+begin_solution org
\[ n = 1000;\ p = 0.005;\ k = 7;\ \lambda = np = 1000\cdot 0.005 = 5 \]
\[ P_{1000}(7) \approx \frac{5^7}{7!}e^{-5} \approx 0.1044 \]
#+end_solution
#+begin_task org
Прибор состоит из 100 элементов. Вероятность отказа каждого элемента
--- \( \frac{1}{100} \). Найти вероятность отказа больше 2 элемнтов
#+end_task
#+begin_solution org
\[ n = 100;\ p = 0.01;\ \lambda = np = 100\cdot0.01 = 1 \]
\[ P_{100}(k > 2) = 1 - P_{100}(k \le 2) = 1 - (P_{100}(0) + P_{100}(1) + P_{100}(2)) = \]
\[ = 1 - (q^{100} + C^1_{100}\cdot p \cdot q^{99} + C^2_{100}\cdot p^2 \cdot q^{98}) \approx 0.07937 \]
\[ = 1 - \left(\frac{1^0}{0!} + \frac{1^1}{1!} + \frac{1^2}{2!}\right)\cdot e^{-1} \approx 0.0803 \]
#+end_solution
* ДЗ
#+begin_task org
Вероятность потери посылки на почте --- 0.1. Найти веротяность того
что из 10 посылок будут потеряны не болле 2х.
#+end_task
#+begin_task org
Вероятность попадания стрелка в цель --- 0.7. Найти веротяность того,
что из 1000 выстрелов точными будут 710.
#+end_task
#+begin_task org
Найти вероятность того что при 10000 бросаниях монеты герб выпадет от 4980 до 5020 раз.
#+end_task
#+begin_task org
Вероятность опечатки на одной странице --- 0.025. Найти вероятность
того что в книге из 1000 страниц будет 3 опечатки.
#+end_task

