#+LATEX_CLASS: general
#+TITLE: Практика 6
#+AUTHOR: Ilya Yaroshevskiy

#+begin_task org
На \(m\) студентов имеются \(m\) билетов на экзамене. Студент выучил
один билет. Каким по очереди нужно идти на экзамен, чтобы вероятность
его сдать была наибольшей.
#+end_task
#+begin_solution org
\-
- \(A_k\) --- выбран нужный билет, \(k\)-тый в очереди
\[ P(A_{k + 1}) = \frac{C^k_{m - 1}}{C^k_m}\cdot\frac{1}{m - k} = \frac{(m - 1)!\cdot k! (m - k)!}{k!(m - 1 - k)!\cdot(m!)} \cdot \frac{1}{m - k} = \frac{m - k}{m}\cdot\frac{1}{m - k} = \frac{1}{m}\]
#+end_solution

#+begin_task org
Вероятность бракованной детали \(\frac{1}{100}\). Имеется 5 партий по
100 деталей. Какова вероятность того, что в двух партиях будет ровно
по 2 бранованных деталей.
#+end_task
#+begin_solution org
\-
- \(p = 0.001\)
- \(n = 100\)
- \(\lambda = np = 1\)
Формула Пуассона:
\[ P_100(2) = \frac{\lambda^2}{2!}e^{-\lambda} = \frac{1}{2}e^{-1} = 0.1839 \]
- \(p = 0.1839\)
- \(n = 5\)
- \(q = 0.8161\)
Формула Бернулли:
\[ P_5(2) = C^2_5p^2q^3 = 0.1837 \]
#+end_solution
#+begin_task org
Три орудия производят стрельбу по трем целям. Каждое орудие выбирает
себе цель случайным образом и независимо от других. Цель, обстрелянная
одним орудием, поражается с вероятностью \(p\). Найти вероятность
того, что из трех целей две будут поражены, а третья нет.
#+end_task
#+begin_solution org
\-
- \(H_1\) --- выбрана одна цель
- \(H_2\) --- две цели
- \(H_3\) --- три цели
- \(p = \frac{1}{3}\)
- \(q = 1 - p\)
По формуле полной вероятности:
\[ P(A|H_1) =  0 \]
\[ P(A|H_2) =  \]
\[ P(A|H_3) = C^2_3 p^2 q \]

\[ P(H_1) = C^1_3 \cdot p^3 \]
\[ P(H_2) = C^2_3 \cdot2\cdot2 \cdot p^3 \]
\[ P(H_3) = 3! \cdot p^3 \]

#+end_solution

