#+LATEX_CLASS: general
#+TITLE: Лекция 1
#+AUTHOR: Ilya Yaroshevskiy

* Статистическая вероятность
$n$ --- чсло экспериментов \\
$n_A$ --- число выполнения события $A$
#+begin_defintion org
Отношение $\frac{n_A}{n}$ --- частота события $A$ \\
$P(A) \approx \frac{n_A}{n},\ n\to+\infty$
#+end_defintion
** Пространство элементарных исходов. Случайные события
#+begin_definition org
*Пространством элементарных исходов* называется множество
содержащее все возможные результаты данного эксперимента из которых при
испытании происходит ровно один. Элементы этого множества называются *элементарными исходами*
#+end_definition
#+begin_symb org
\-
- Пространство элементарных исходов --- $\Omega$
- Элементарный исход $w \in \Omega$
#+end_symb
#+begin_definition org
*Случайными событиями* называются подмножества $A \subset \Omega$. Событие $A$ *наступило* если в ходе эксперимента
произошел один из элементарных исходов $w \in A$. $w$ --- благоприятный к $A$
#+end_definition
#+begin_examp org
Бросаем один раз монету. $\Omega = \{H, T\}$. \\
\color{gray}
$H$ --- Head(орел), $T$ --- Tail(решка)
#+end_examp
#+begin_examp org
Бросаем кубик. $\Oemga = \{1, 2, 3, 4, 5, 6\}$ \\
Выпало четное число очков. $A = \{2, 4, 6\}$
#+end_examp
#+begin_examp org
Монета бросается дважды
- Учитываем порядок. $\Omega = \{HH, HT, TH, TT\}$
- Не учитываем порядок. $\Omega = \{HH, HT, TT\}$
#+end_examp
#+begin_examp org
Бросается дважды кубик. Учитывем порядок. \\
Число очков кратно $3$. $A = \{ (1, 2), (2, 1), (1, 5), (5, 1), \dots \}$ 
#+end_examp
#+begin_examp org
Монета бросается до выпадения герба. $\Omega = \{ (H), (T, H), (T, T, H), \dots \}$ --- счетное число исходов
#+end_examp
#+begin_examp org
Монета бросается на плоскость. $\Omega = \{(x, y) \big\vert x, y \in \R\}$ --- нечетное число исходов
#+end_examp

** Операции над событиями
#+begin_definition org
$\Omega$ --- универсальное событие, достоверное, наступает всегда, т.к. содержит все элементарные исходы \\
$\emptyset$ --- невозможное событие, никогда не выполняется, т.к. не одержит элементарных исходов
#+end_definition
#+begin_definition org
*Суммой событий* $A + B$ называется событие $A \cup B$ --- событие
 состоящее в том что произошло событие $A$ или событие $B$, т.е. хотя
 бы одно из них
#+end_definition
#+begin_definition org
*Произведением* $A \cdot B$ называется событие $A \cap B$ --- событие состоящее в том что произошло событие $A$ и событие $B$, т.е. оба из них
#+end_definition
#+begin_definition org
*Противоположным* к $A$ называется событие $\overline{A}$ --- состоящее в том событие $A$ не произошло
#+end_definition
#+begin_export latex
\begin{center}
\begin{tikzpicture}
\draw[pattern=north east lines, pattern color=red] (4, 2) rectangle (-4, -2);
\draw[fill=white] (-1, 0) circle[radius=1cm] node {$A$};
\node[below] at (0, -2) {$\overline{A}$};
\node[above right] at (4, 2) {$\Omega$};
\end{tikzpicture}
\end{center}
#+end_export
#+begin_definition org
*Дополнение*
#+end_definition
#+begin_definition org
События $A$ и $B$ называются *несовместными* если $A\cdot B = \emptyset$, т.е. в ходе эксперимента может наступить только одно из них
#+end_definition
#+begin_definition org
Событие $A$ *влечет* событие $B$, если $A \subset B$
#+end_definition
#+begin_definition org
$P(A) \le 1$ --- вероятность наступления события $A$
#+end_definition
** Классическое определение вероятности
Пусть $\Omega$ содержит конечное число исходов, при чем их можно считать равновозможным.
Тогда применимо классическое определение вероятности
#+begin_definition org
Вероятность события $A$ $P(A) = \frac{|A|}{|\Omega|} = \frac{m}{n}$, где $n$ --- число всех возможных элеметарных
исходов, $m$ --- число элементарных исходов благоприятных событию $A$. В частности, если $|\Omega| = n$, а $A$ --- элементарный исход, то $P(A) = \frac{1}{n}$
#+end_definition
#+begin_remark org
Cвойства:
1. $0 \le P(A) \le 1$
4. [@4] Если события $A$ и $B$ несовместны то вероятность $P(A + B) = P(A) + P(B)$
   #+begin_proof org
   $] |A| = m_1, |B| = m_2, |A\cup B| = m_1 + m_2$ \\
   $P(A + B) = \frac{m_1 + m_2}{n} = \frac{m_1}{n} + \frac{m_2}{n} = P(A) + P(B)$
   #+end_proof
#+end_remark
#+begin_examp org
Найти вероятность того, что при бросании кости выпадет четное число очков \\
$\Omega = \{1, 2, 3, 4, 5, 6\},\ A = \{ 2, 4, 5\},\ P(A) = \frac{3}{6} = \frac{1}{2}$ 
#+end_examp
#+begin_examp org
В ящике 3 белых и два черных шара. Вынули 3 шара, найти вероятность того что из них 2 белых и 1 черных
#+begin_export latex
\begin{center}
\begin{tikzpicture}
\draw (4, 2) rectangle (-4, -2);
\draw (0, 2) -- (0, -2);
\node at (-2, 0) {$3\text{ б.}$};
\node at (2, 0) {$2\text{ ч.}$};
\draw[->] (-2, -1.5) -- (-2, -2.5) node[below] {$2$};
\draw[->] (2, -1.5) -- (2, -2.5) node[below] {$1$};
\draw[->] (-0.5, 2.5) node[left] {$5$} -> (4.5, 2.5) node[right] {$3$};
\end{tikzpicture}
\end{center}
#+end_export

\[ n = C^3_5 = 10 \]
\[ m = C^2_3\cdot C^1_2 = 6 \]
\[ P(A) = \frac{6}{10} \]
#+end_examp
** Геометрическое понятие вероятности
Пусть $\Omega \subset \R^n$  --- замкнутая ограниченая область \\
$\mu(\Omega)$ --- конечная мера множества $\Omega$ (например мера Римана, т.е длина, площадь, объем) 
В эту область /наугад/ бросаем точку. Термин /наугад/ означает, что вероятность попадания в область $A$
зависит только от меры этой области, но не зависит от ее положения. Вероятности попадания в любые точки равновозможны.
Тогда применимо геометрическое определение вероятности.
#+begin_definition org
$P(A) = \frac{\mu(A)}{\mu(\Omega)}$, где $\mu(\Omega)$ --- мера $\Omega$, $\mu(A)$ --- мера благоприятной области $A$
#+end_definition
#+begin_remark org
Заметим что по этому определению, мера точки равна $0$ и веротяность попадания в конкретную точку равна $0$, хотя это событие не является невозможным.
#+end_remark
#+begin_examp org
Игра. Монета диаметром 6 сантиметров бросается на пол, вымощенный
квадратной плиткой со стороной 20 сантиметров. Найти вероятность того
что монета целиком окажется на одной плитке
#+begin_export latex
\begin{center}
\begin{tikzpicture}
\draw (4, 4) rectangle (-4, -4);
\draw (3, 3) rectangle (-3, -3);
\draw[<->] (-3, -1) -- (-4, -1);
\draw[<->] (-1, -3) -- (-1, -4);
\node at (0, 0) {$A$};
\node[left] at (-4, 0) {$20$};
\node[below] at (0, -4) {$20$};
\node[above] at (-3.5, -1) {$3$};
\node[right] at(-1, -3.5) {$3$};
\end{tikzpicture}
\end{center}
#+end_export

\[ S(\Omega) = 20^2 = 400 \]
\[ S(A) = 14^2 = 196 \]
\[ P(A) = \frac{196}{400} = 0.49 \]
#+end_examp
#+begin_task org
Пол выложен ламинатом. На пол бросается игла длиной равной ширине
доски. Найти вероятность того что она пересечет стык
#+end_task
#+begin_solution org
$2l$ --- длина иглы, $x$ --- расстояние от центра иглы до ближайшего края, $\varphi$ --- угол к ближайшему краю \\
Игла пересечет край если $x \le |AB|$, $|AB| = l\sin\varphi$ \\
Можно считать что положение от центра и угол, независимы друг от друга. $x \in [0, l]. \varphi \in [0, \pi]$
#+begin_export latex
\begin{center}
\begin{tikzpicture}
\draw[->] (-0.5, 0) -- (5, 0) node[below] {$\varphi$};
\draw[->] (0, -0.5) -- (0, 4) node[left] {$x$};
\node[below left] at (0, 0) {$0$};
\draw[thick] (-0.1, 3) node[left] {$l$} -- ++ (0.2, 0);
\draw[thick] (4, -0.1) node[below] {$\pi$} -- ++ (0, 0.2);
\draw[thick] (2, -0.1) node[below] {$\frac{\pi}{2}$} -- ++ (0, 0.2);
\draw[dashed] (0, 3) -- (4, 3);
\draw[dashed] (4, 0) -- (4, 3);
\draw (0, 0) parabola bend (2, 3) (4, 0);
\node[above] at (2, 3) {$x = l\sin\varphi$};
\node at (2, 1.5) {$A$};
\end{tikzpicture}
\end{center}
#+end_export

\[ A: x \le l\sin\varphi \]
\[ S(\Omega) = \pi\cdot l \]
\[ S(A) = \int^\pi_0 l\sin\varphi d\varphi = 2l \]
\[ P(A) = \frac{S(A)}{S(\Omega)} = \frac{2l}{\pi l} = \frac{2}{\pi} \]

#+end_solution
