#+LATEX_CLASS: general
#+TITLE: Лекция 3
#+AUTHOR: Ilya Yaroshevskiy


#+ATTR_LATEX: :options [Баеса]
#+begin_theorem org
$] H1, H2, \dots, H_n ,\dots$ --- полн. у. соб. \\
_Тогда_ \[ P(H_k|A) = \frac{P(H_k)P(A|H_k)}{\sum_{i = 1}^{\infty}P(H_i)P(A|H_i)} \]
#+end_theorem
#+begin_examp org
В первой коробке 4 белых и два черных шара, во второй й белый и два
черных. Из первой коробки во вторую переложили два шара, затем из
второй коробке доставли шар. Найти вероятность того что он оказался белый
#+end_examp
#+begin_solution org
- $] H_1$ --- переложили 2 белых
- $] H_2$ --- переложили 2 черных
- $] H_3$ --- переложили 1 черный и 1 белый
- $] A$ --- из второй коробки достали белый
\[ P(H_1) = \frac{4}{6}\cdot\frac{3}{5} =  \frac{6}{15} \]
\[ P(H_2) = \frac{2}{6}\cdot\frac{1}{5} = \frac{1}{15} \]
\[ P(H_3) = \frac{4}{6}\cdot\frac{2}{5} + \frac{2}{6}\cdot\frac{4}{5} = \frac{8}{15} \]
\[ \sum P(H_i) = 1\text{ --- верно} \]
\[ P(A|H_1) = \frac{3}{5} \]
\[ P(A|H_2) = \frac{1}{5} \]
\[ P(A|H_3) = \frac{2}{5} \]
По формуле полной вероятности:
\[ P(A) = P(H_1)\cdotP(A|H_1) + P(H_2)\cdotP(A|H_2) + P(H_3)\cdotP(A|H_3) = \frac{6}{15}\cdot\frac{3}{5} + \frac{1}{15}\cdot\frac{1}{5} + \frac{8}{15}\cdot\frac{2}{5} = \frac{7}{15}\]

#+end_solution
#+begin_examp org
По статистике 1% населения болен раком. Тест дает правильный результат
в 99% случаев. Тест оказался положительным. Найти веротяность того что
человек болен.
#+end_examp
#+begin_solution org
#+begin_export latex
$]$ \left.\begin{array}{l}
$H_1$ --- болен \\
$H_2$ --- здоров
\end{array}\right\}
#+end_export
, $A$ --- тест положительный
- $P(H_1) = 0.01$
- $P(H_2) = 0.99$
- $P(A|H_1) = 0.99$
- $P(A|H_2) = 0.01$
  \[ P(H_1|A) = \frac{P(H_1)P(A|H_1)}{P(H_1)P(A|H_1) + P(H_2)P(A|H_2)} = \frac{1}{2} \]
Сделаем второй тест:
- $P(H_1) = 0.01$
- $P(H_2) = 0.99$
- $P(AA|H_1) = 0.99^2$
- $P(AA|H_2) = 0.01^2$
\[ P(H_1|AA) = \frac{0.99}{0.99 + 0.01} = 0.99 \]
#+end_solution
