#+LATEX_CLASS: general
#+TITLE: Лекция 3
#+AUTHOR: Ilya Yaroshevskiy

* Условная вероятность
#+begin_symb org
\(P(A | B)\) --- вероятность наступления события \(A\), вычисленная в предположении, что событие \(B\) уже произошло
#+end_symb
#+begin_examp org
Кубик подбрасывается один раз. Известно что выпало больше трех очков. Найти вероятность того, что выпало четное число очков.
- \(A\) --- четное число очков
- \(B\) --- больше 3 очков
Тогда:
- \(n = 3\) \((4, 5, 6)\)
- \(m = 2\) \((4, 6)\)
\[ P(A|B) = \frac{2}{3} = \frac{\frac{2}{6}}{\frac{3}{6}} = \frac{P(A\cdot B)}{P(B)}\]
#+end_examp
\noindentПри интерпретация с геометрическим определением вероятностей также получаем формулу \(P(A|B) = \frac{P(A\cdot B)}{P(B)}\)
#+begin_definition org
*Условной вероятностью* события \(A\) при условии того что имело место событие \(B\) называется величина:
\[ P(A|B) = \frac{P(A \cdot B)}{P(B)} \] --- *формула условной вероятности*

#+end_definition
** Формула умножения вероятности
Как следствие формулы условной вероятности получаем:
\[ P(AB) = P(B) \cdot P(A|B)  \text{ или } P(AB) = P(A)\cdot P(B | A)\]
#+begin_theorem org
\[ P(A_1 A_2 \dots A_n) = P(A_1) \cdot P(A_2 | A_1) \cdot P(A_3 | A_1 A_2) \dots P(A_n | A_1\dots A_{n - 1})\]
#+end_theorem
#+begin_proof org
По индукции
#+end_proof
#+begin_remark org
\(P(A) \neq 0\) и поэтому формула умножения удовлетворяет
\[ P(A_1 A_2 \dots A_n) \neq 0\]
#+end_remark
#+begin_remark org
\[ P(A|B) = P(A) \Leftrightarrow P(AB) = P(A) \cdot P(B) \]
#+end_remark
#+begin_proof org
Очевидно
#+end_proof
#+begin_task org
В коробке 3 красных крандаша и 2 синих. Вынули 3 карандаша. Найти вероятность того что первые два красные а третий синий.
#+end_task
#+begin_solution org
\-
- \(A_1\) --- 1-й красный
- \(A_2\) --- 2-й красный
- \(A_3\) --- 3-й синий
\[ P(A_1 A_2 A_3) = P(A_1) \cdot P(A_2 | A_1) \cdot P(A_3 | A_2 A_1) = \frac{3}{5} \cdot \frac{2}{4} \cdot \frac{2}{3} = \frac{1}{5} = 0.2\]
#+end_solution
#+begin_remark org
Прменяем когда учитывается порядок
#+end_remark
** Полная группа событий
#+begin_definition org
События \(H_1, H_2, \dots, H_n, \dots\) образуюти полную группу событий если они попарно несовместны, и содержат все элементарные исходы:
- \(P(H_i H_j) = \emptyset\ \forall i \neq j\)
- \(\sum\limits_{i = 1}^\infty H_i = \Omega\)
#+end_definition
#+begin_remark org
Часто события из полной группы называются гипотезами
#+end_remark
** Формула полной вероятности
#+ATTR_LATEX: :options [Баеса]
#+begin_theorem org
$] H_1, H_2, \dots, H_n ,\dots$ --- полная группа событий \\
_Тогда_ \[ P(H_k|A) = \frac{P(H_k)P(A|H_k)}{\sum_{i = 1}^{\infty}P(H_i)P(A|H_i)} \]
#+end_theorem
#+begin_examp org
В первой коробке 4 белых и два черных шара, во второй 1 белый и два
черных. Из первой коробки во вторую переложили два шара, затем из
второй коробки достали шар. Найти вероятность того что он оказался белый
#+end_examp
#+begin_solution org
\-
- $] H_1$ --- переложили 2 белых
- $] H_2$ --- переложили 2 черных
- $] H_3$ --- переложили 1 черный и 1 белый
- $] A$ --- из второй коробки достали белый
\[ P(H_1) = \frac{4}{6}\cdot\frac{3}{5} =  \frac{6}{15} \]
\[ P(H_2) = \frac{2}{6}\cdot\frac{1}{5} = \frac{1}{15} \]
\[ P(H_3) = \frac{4}{6}\cdot\frac{2}{5} + \frac{2}{6}\cdot\frac{4}{5} = \frac{8}{15} \]
\[ \sum P(H_i) = 1\text{ --- верно} \]
\[ P(A|H_1) = \frac{3}{5} \]
\[ P(A|H_2) = \frac{1}{5} \]
\[ P(A|H_3) = \frac{2}{5} \]
По формуле полной вероятности:
\[ P(A) = P(H_1)\cdotP(A|H_1) + P(H_2)\cdotP(A|H_2) + P(H_3)\cdotP(A|H_3) = \frac{6}{15}\cdot\frac{3}{5} + \frac{1}{15}\cdot\frac{1}{5} + \frac{8}{15}\cdot\frac{2}{5} = \frac{7}{15}\]

#+end_solution
#+begin_task org
По статистике 1% населения болен раком. Тест дает правильный результат
в 99% случаев. Тест оказался положительным. Найти веротяность того что
человек болен.
#+end_task
#+begin_solution org
#+begin_export latex
$]$ \left.\begin{array}{l}
$H_1$ --- болен \\
$H_2$ --- здоров
\end{array}\right\}
#+end_export
, $A$ --- тест положительный
- $P(H_1) = 0.01$
- $P(H_2) = 0.99$
- $P(A|H_1) = 0.99$
- $P(A|H_2) = 0.01$
  \[ P(H_1|A) = \frac{P(H_1)P(A|H_1)}{P(H_1)P(A|H_1) + P(H_2)P(A|H_2)} = \frac{1}{2} \]
Сделаем второй тест:
- $P(H_1) = 0.01$
- $P(H_2) = 0.99$
- $P(AA|H_1) = 0.99^2$
- $P(AA|H_2) = 0.01^2$
\[ P(H_1|AA) = \frac{0.99}{0.99 + 0.01} = 0.99 \]
#+end_solution
