#+LATEX_CLASS: general
#+TITLE: Лекция 9
#+AUTHOR: Ilya Yaroshevskiy

* Сингулярное распределение
#+begin_definition org
Случайная величина \(\xi\) имеет *сингулярное распределение*, если существует Борелевское множество \(B \in \mathfrak{B}\), с нулевой мерой Лебега \(\lambda B = 0\), такое что \(p(\xi \in B) = 1\), но \(\forall x \in B\ p(\xi = x) = 0\) 
#+end_definition
#+begin_remark org
\[ \forall x \in B\ p(\xi = x) = 0 \implies p(\xi \in B) = 0 \]
Иными словами, при сингулярном распределении, случайная величина распределена на несчетном множестве меры 0
#+end_remark
#+begin_remark org
Функция распределения --- непрерывная функция, по свойству 7 функии распределения.
#+end_remark
#+begin_examp org
Случайная величина \(\xi\), задана функция распределения, которая --- лестница Кантора
\todo
#+end_examp
#+ATTR_LATEX: :options [Лебега]
#+begin_theorem org
Пусть \(F_\xi(x)\) --- функция распределения произвольной случайной величины \(\xi\) \\
_Тогда_
\[ F_\xi(x) = p_1F_1(x) + p_2F_2(x) + p_3F_3(x) \quad p_1 + p_2 + p_3 = 1\]
, где \(F_1(x)\) --- фунция дискретного распределения, \(F_2(x)\) --- функция абсолютно непрерывного распределения, \(F_3(x)\) --- функция сингулярного распределения. Т.е. все распределения делятся на дискретные, абсолютно непрерывные, сингуряные и их смеси
#+end_theorem
* Общий взгляд на математическое ожидание
Пусть случайная величина \(\xi\) задана на вероятностном пространстве \((\Omega, \mathcal{F}, p)\). Математическим ожиданием случайной величины \(\xi\) называется интеграл Лебега:
\[ E\xi = \int_\Omega \xi(\omega) dp(\omega) \addtag\label{int_1_9} \], при условии, что данный интеграл существует. Использую интеграл Стилтьеса, эту формулу можно записать в виде:
\[ E\xi = \int_{-\infty}^{\infty} x dF_\xi(x) \addtag\label{int_2_9} \]
Из определения интеграла Стилтьеса можно получить геометрическую интерпретацию математического ожидания

Рассмотрим две ситуации:
1. Вероятностное пространство \((\Omega, \mathcal{F}, p)\) --- дискретное вероятностное пространство, т.е. \(\Omega\) состоит из н.б.ч.с числа точек. Тогда из \ref{int_1_9} получаем:
   \[ E\xi = \sum_{i = 1}^\infty \xi(\omega_i) p(\omega_i) \]
   #+begin_examp org
   \todo
   #+end_examp
2. \((\Omega, \mathcal{F}, p)\) --- непрерывное вероятностное пространство. например \(\Omega \subset \R^m\), \(\omega = (x_1, x_2, \dots, x_m)\), тогда из \ref{int_2_9} получаем:
   \[ E\xi = \iint\dots\int_\Omega \xi(x_1, x_2, \dots, x_m)\cdot p(x_1, x_2, \dots, x_m) dx_1 dx_2\dots dx_m \]
   #+begin_examp org
   В круг радиуса 3 наугад бросается точка, случайная величина \(\xi\), расстояния от центра круга до данной точки. Найти мат. ожидание \(\xi\).
   \[ \Omega = \{(x, y) \Big| x^2 + y^2 \le 9\} \]
   \[ \xi = \sqrt{x^2 + y^2} \]
   \[ p(x, y) = p = \const \]
   Из условия нормировки:
   \[ \int_\Omega \alpha p(\omega) = 1 \text{ или } \iint_\Omega p\,dx\,dy = 1 \implies \frac{1}{9 \pi} \]
   \[ E\xi = \iint_\Omega \xi(x, y)\cdot p dx dy = \iint_\Omega \sqrt{x^2 + y^2} \frac{1}{9 \pi} dx dy = \]
   \[ = \frac{1}{9\pi} \int_0^\pi d\varphi \int_0^3 \rho \cdot \rho d\rho = \frac{1}{9\pi}\cdot\pi\cdot\frac{\rho^3}{3} \bigg|_0^3 = 2 \]
   \fixme
   #+end_examp
* Преобразование случайных величин
\(\xi\) --- случайная величина на \((\Omega, \mathcal{F}, p)\), \(g: \R \to \R\). Тогда функция \(g(\xi)\)
#+begin_definition org
Функция \(g(x): \R \to \R\) --- Борелевская функция, если \(\forall B \in mathfrak{B}\), \(g^{-1}(B) \in \mathfrak{B}\)
#+end_definition
#+begin_theorem org
Если \(g(x)\) --- Борелевская функция и \(\xi\) --- случайная величина на \((\Omega, \mathcal{F}, p)\), то \(g(\xi)\) --- случайная величина на \((\Omega, \mathcal{F}, p)\)
#+end_theorem
#+begin_proof org
\todo
#+end_proof
#+begin_remark org
Если \(\xi\) --- дискретная случайная величина, то ее закон распределения находится просто из определения, поэтому в дальнейшем будем считать, что \(\xi\) имеет абсолютно непрерывное распределние
#+end_remark
** Стандартизация случайной величины
#+begin_definition org
Пусть имеется случайная величина \(\xi\) с соответствующей ей стандортной величиной:
\[ \eta = \frac{\xi - E\xi}{\sigma} \]
#+end_definition
\beginproperty
#+begin_property org
\(E\eta = 0\), \(D\eta = 1\)
#+end_property
#+begin_proof org
\todo
#+end_proof
#+begin_remark org
При стандартизации тип распределения не всегда сохраняется
#+end_remark
** Линейное преобразование
#+begin_theorem org
Пусть случайная величина \(\xi\) имеет плотность \(f_\xi(x)\) \\
_Тогда_ случайная величина \(\eta = a\xi + b,\ a \neq 0\) имеет плотность:
\[ f_\eta(x) = \frac{1}{|a|}\cdot f_\xi \left(\frac{x - b}{a}\right) \]
#+end_theorem
#+begin_proof org
\-
1. \(a > 0\), тогда:
   \[ F_\eta(x) = p(a\xi + b < x) = p(\xi < \frac{x - b}{a}) = \int_{-\infty}^{\frac{x - b}{a}} f_\xi(t) dt \]
   \[ = \left[\begin{matrix} t = \frac{y - b}{a} & dt = \frac{1}{a}dy & y = at + b \\ y(-\infty) = -\infty & y \left(\frac{x - b}{a}\right) = x &  \end{matrix}\right. = \int \]
\todo
#+end_proof
\beginproperty
#+begin_property org
Если \(\xi \in N(0, 1)\), то \(\eta = \sigma \xi + a \in N(a, \sigma^{-1})\)
#+end_property
#+begin_proof org
\todo
#+end_proof
#+begin_property org
Если \(\eta \in N(a, \sigma^2)\), то \(\xi = \frac{\eta - a}{\sigma} \in N(0, 1)\)
#+end_property
#+begin_property org
Если \(\eta \in N(a, \sigma^2)\), то \(\xi = \gamma\eta + b \in N(a\gamma + b, \gamma^2\sigma^2)\)
#+end_property
#+begin_property org
Если \(\xi \in U(0, 1)\), то \(\eta = a \xi + b \in U(b, a + b)\) при \(a > 0\)
#+end_property
#+begin_property org
Если \(\xi \in E_\alpha\), то \(\eta = \alpha \xi \in E_1\)
#+end_property

#+begin_theorem org
Пусть \(f_\xi(x)\) --- плотность случайной величины \(\xi\) и функция \(\g(x)\) --- монотонная. Тогда существует обратная \(h(t) = g^{-1}(x)\) и случайная величина \(\eta = g(\xi)\) имеет плотность:
\[ f_\eta(x) = \frac{1}{|f'_ \xi(x)|} f _\xi()  \fixme \]
#+end_theorem
** Квантильное преобразование
#+begin_theorem org
Пусть функция распределения \(F(x)\) случайной величины \(\xi\) --- непрерывная, тогда случайная величина \(\eta = F(\xi) \in U(0, 1)\) --- имеет стандартное равномерное распределение
#+end_theorem
#+begin_proof org
Ясно, что \(0 \le \eta \le 1\)
1. Предположим сначала, что \(F(x)\) --- строго возрастающая функция. Тогда она имеет обратную функцию \(F^{-1}(x)\) и
   \[ F_\eta(x) = p(F(\xi) < x) = p(\xi < F^{-1}(x)) = \begin{cases}
   0 & x < 0 \\
   F(F^{-1}(x)) = x & 0 \le x \le 1 \\
   1 & x > 1
   \end{cases} \implies \]
   \(\implies \eta \in U(0, 1)\)
2. Пусть функция не является строго возрастающей, т.е. у нее есть интервалы постоянства, в этом случае через \(F^{-1}(x)\) обозначим, самую левую точку такого интервала:
   \[ F^{-1}(x) = \min_t\{t \Big| F(t) = x)\} \]
   --- корректно, т.к. \(F(x)\) непрерывна слева. Тогда снова будет верна цепочка:
   \[ F_\eta(x) = p(F(\xi) < x) = p(\xi < F^{-1}(x)) = F(F^{-1}(x)) = x\quad 0 \le x \le 1\]
#+end_proof
Сформулируем теперь обратную теорему: \\
Пусть \(F(x)\) --- функция распределения случаайной величины \(\xi\), при чем не обязательно непрерывная. Обозначим через \(F^{-1}(x) = \inf\{t \Big| F(t) \ge x\}\)
#+begin_theorem org
Пусть \(\eta \in U(0, 1)\), \(F(x)\) --- произвольная функция распределения. \\
_Тогда_ случайная величина \(\xi = F^{-1}(\eta)\) имеет функцию распределения \(F(x)\)
#+end_theorem
#+begin_remark org
\(F^{-1}(\eta)\) называется квантильным преобразованием над случайной величиной \(\eta\)
#+end_remark
#+begin_corollary org
Датчики случайных чисел обычно имеют стандартное равномерное распределение. Из теоремы следует, что при помощи датчика случайных числе и квантильного преобразования, мы можем смоделировать любое желаемое распределение, в том числе дискретное.
#+end_corollary
#+begin_examp org
\(E_\alpha\):
\[ F(x) = \begin{cases}
0 & x < 0 \\
1 - e^{-\alpha x} & x \ge 0
\end{cases}\]
\[ \eta = 1 - e^{-\alpha x} \implies x = -\frac{1}{\alpha}\ln(1 - \eta) \]
Если \(\eta \in U(0, 1)\), то \(\xi = \frac{1}{\alpha} \ln(1 - \eta) \in E_\alpha\)
#+end_examp
#+begin_examp org
\(N(0, 1)\):
\[ \Phi_0(x) = \frac{1}{\sqrt{2 \pi}} \int_{-\infty}^x  e^{-\frac{z^2}{2}} dz\]
\[ \Phi^{-1}_0 \in N(0, 1) \]
#+end_examp


