jobs:
  publish:
    stage: publish
    do:
      type: script
      env:
        INPUT: ${project.repos.conspects.path}
        HAKYLL_DESTINATION: ${project.data_path}/hakyll/conspects
        HAKYLL_STORE: ${project.data_path}/hakyll/conspects-store
        BUILDER: ${project.repos.main.path}/builder
        BUILDER_PROFILE: ${project.data_path}/builder-conspects

        ASSETS_ROOT: https://iliay.ar
        MATOMO_HOST: matomo.iliay.ar
      script: |
        set -e
        . /etc/profile
        nix build $BUILDER#conspects --profile $BUILDER_PROFILE --no-link

        mkdir -p $HAKYLL_DESTINATION
        mkdir -p $HAKYLL_STORE

        cd $INPUT
        $BUILDER_PROFILE/bin/site build

stages:
  publish:
    on_overlap: cancel

integrations:
  github:
    token: ${project.secrets.github_token}
    repo: 'iliayar/ITMO'
    rev: ${project.repos.conspects.rev}
    ui_url: 'https://uci.iliay.ar'
    jobs_to_report:
      - publish
