bind:
  enabled: true
  zones:
    'ilyay.space':
      cnames:
        - 'conspects'

    'iliay.ar':
      cnames:
        - 'conspects'
        - 'new-conspects'

caddy:
  hostnames:
    'conspects.ilyay.space': |
      redir https://conspects.iliay.ar{uri}

    'conspects.iliay.ar': |
      file_server
      root * ${project.data_path}/gen-conspects
  
      route / {
          redir https://conspects.iliay.ar/README.html
      }
  
      handle_errors {
          @404 expression `{err.status_code} in [404]`
          handle @404 {
              redir https://github.com/iliayar/ITMO/tree/master{uri}
          }
      }

    'new-conspects.iliay.ar': |
      file_server
      root * ${project.data_path}/hakyll/conspects
  
      route / {
          redir https://new-conspects.iliay.ar/README.html
      }
  
      handle_errors {
          @404 expression `{err.status_code} in [404]`
          handle @404 {
              redir https://github.com/iliayar/ITMO/tree/master{uri}
          }
      }

docker:
  volumes:
    conspects-org-publish-cache: {}

actions: ${${load(./actions.yaml)}.actions}

pipelines:
  publish-conspects: ${load(./publish_pipeline.yaml)}
  hakyll-conspects: ${load(./hakyll_pipeline.yaml)}
