bind:
  enabled: true
  zones:
    'iliay.ar':
      cnames:
        - 'conspects'

caddy:
  hostnames:
    'conspects.iliay.ar': |
      file_server
      root * ${project.data_path}/hakyll/conspects
  
      route /favicon.ico {
          redir https://iliay.ar/favicon.ico
      }

      route / {
          redir https://conspects.iliay.ar/README.html
      }
  
      handle_errors {
          @404 expression `{err.status_code} in [404]`
          handle @404 {
              redir https://github.com/iliayar/ITMO/tree/master{uri}
          }
      }

actions: ${${load(./actions.yaml)}.actions}

pipelines:
  hakyll-conspects: ${load(./hakyll_pipeline.yaml)}
