bind:
  enabled: false
  zones:
    'ilyay.space':
      cnames:
        - 'conspects'

caddy:
  hostnames:
    'conspects.ilyay.space': |
      file_server
      root * ${project.data_path}/gen-conspects
  
      route / {
          redir https://conspects.ilyay.space/README.html
      }
  
      handle_errors {
          @404 expression `{err.status_code} in [404]`
          handle @404 {
              redir https://github.com/iliayar/ITMO/tree/master{uri}
          }
      }

docker:
  volumes:
    conspects-org-publish-cache: {}

actions: ${load(./actions.yaml)}

pipelines:
  publish-conspects: ${load(./publish_pipeline.yaml)}
