jobs:
  build-image:
    enabled: ${params.build-org-publish-image}
    do:
      type: build
      image: conspects-org-publish
      path: ${project.repos.main.path}/org-publish

  # FIXME: redunant?
  _init_gen_dir:
    do:
      type: script
      env:
        DATA_DIR: ${project.data_path}/gen-conspects
      script: |
        mkdir -p ${DATA_DIR} || echo "Already exists"

  clean_caches:
    enabled: ${params.clean-html-caches}
    needs:
      - _init_gen_dir
    do:
      type: script
      image: alpine:latest
      interpreter: ['/bin/sh', '-c']
      volumes:
        '/timestamps': conspects-org-publish-cache
      script: |
        set -e

        files="/timestamps/org-conspects.cache /timestamps/static-conspects.cache"
        echo "Removing files:\n$files"
        rm $files

  publish:
    stage: publish
    needs:
      - build-image
      - _init_gen_dir
    do:
      type: script
      image: conspects-org-publish
      interpreter: ['/bin/sh', '-c']
      volumes:
        '/root/.org-timestamps': conspects-org-publish-cache
        '/publish/input': ${project.repos.conspects.path}
        '/publish/config': ${project.repos.main.path}/org-publish/config
        '/publish/output': ${project.data_path}/gen-conspects
      env:
        "CONSPECTS_BASE_URL": "https://conspects.iliay.ar"
        "CONSPECTS_RES_BASE_URL": "https://iliay.ar"
        "CONSPECTS_HOSTNAME": "conspects.iliay.ar"
        "CONSPECTS_MATOMO_HOST": "matomo.iliay.ar"
      script: |
        set -e

        # Remove lock files
        rm -Rf /root/.org-timestamps/.#*

        emacs --batch -l /publish/config/init.el --eval '(org-publish-project "conspects")'

stages:
  publish:
    on_overlap: cancel

integrations:
  github:
    token: ${project.secrets.github_token}
    repo: 'iliayar/ITMO'
    rev: ${project.repos.conspects.rev}
    ui_url: 'https://uci.iliay.ar'
    jobs_to_report:
      - publish
