jobs:
  build-image:
    type: build
    image: conspects-org-publish
    path: ${project.repos.main.path}/org-publish
    enabled: ${params.build-org-publish-image}

  # FIXME: redunant?
  _init_gen_dir:
    type: script
    env:
      DATA_DIR: ${project.data.path}/gen-conspects
    script: |
      mkdir -p ${DATA_DIR} || echo "Already exists"

  publish:
    needs:
      - build-image
      - _init_gen_dir
    stage: publish

    type: script
    image: conspects-org-publish
    interpreter: ['/bin/sh', '-c']
    volumes:
      '/root/.org-timestamps': conspects-org-publish-cache
      '/publish/input': ${project.repos.conspects.path}
      '/publish/config': ${project.repos.main.path}/org-publish/config
      '/publish/output': ${project.data.path}/gen-conspects
    script: |
      set -e

      # Remove lock files
      rm -Rf /root/.org-timestamps/.#*

      emacs --batch -l /publish/config/init.el --eval '(org-publish-project "conspects")'

stages:
  publish:
    on_overlap: cancel

integrations:
  github:
    token: ${project.secrets.github_token}
    repo: 'iliayar/ITMO'
    rev: ${project.repos.conspects.rev}
    ui_url: 'https://uci.ilyay.space'
    jobs_to_report:
      - publish
