#+LATEX_CLASS: general
#+TITLE: Холодная война
#+AUTHOR: Ilya Yaroshevskiy

* Конференция
Внедряется вопрос о ядерном оружиии - важная деталь при переговорах \\
Основные страны - США, Гремания, СССР? \\
Манэтанский проект \\
* Появления ядерного оружия
Китай - 60е года \\
Великобритания - 1952

США должны были вывести войска из Европы, но не выполнили договор \\
Железный занавес - установление социалистического режима в странах
Европы, там куда дошла советская армия

* Холодная война
1946-1956 гг.

В локальных конфликтах между СССР и США погибло 7 млн.

Красная армия освобождает евпропейские государства

Итальянская комунитсическая партия Французская ком. партия получила
46% на выборах Формирования ком. режимов под действием СССР
популярность ее в некоторых транах уменьшилась

В Польше настроения были анти российские

Навязывание одной политической позиции и не отступление от нее,
благодарность сменилась на негатив

Когда СССР начал преживать кризисы, в социалистических странах такой
режим разрушается \\
Народные востания в Венгрии, Чехословакии(1968) - попытки реформирования социализма
