#+setupfile: setup.org
#+TITLE: Лекция 1
#+date: 10 февраля

* Введение
Игра -- конфликт интересов.

Пути решения конфликтов:
- Конкуренция
  - _Правила_
  - Ограничения
  - Естественное развитие
- Кооперация
  - Создание договора
  - Общая стратегия развития

#+begin_examp org
*Задач о лайнере* \\
На круизном лайнере работают три бара. В барах есть единственный вариант выпивки: ром.
Все бары продают один и тот же ром, и цену устанавливают на него самостоятельно.

Один бар немного снизил целы. Остальные бары тоже снимают. И т.д. Все игроки в одинаково плохих условиях.
Могут скооперироваться и вместе повысить цену -- монополия.
#+end_examp

** Свободная конкуренция
Пункты \(A, B\). Две дороги: через \(C\) и через \(D\).
#+begin_export latex
\begin{center}
\begin{tikzpicture}
\begin{scope}[every node/.style={circle,draw}]
  \node (A) at (0, 0) {\(A\)};
  \node (B) at (4, 0) {\(B\)};
  \node (C) at (2, 2) {\(C\)};
  \node (D) at (2, -2) {\(D\)};
\end{scope}
\draw (A) -- node[above] {\(2\)} (C);
\draw (C) -- node[above] {\(1 + x\)} (B);
\draw (B) -- node[below] {\(2\)} (D);
\draw (A) -- node[below] {\(1 + y\)} (D);
\draw[dashed] (C) -- node[left] {\(0\)} (D);
\end{tikzpicture}
\end{center}
#+end_export

\(x, y \in [0, 1]\) -- зависит от загруженности. \(t_{ACB} \simeq t_{ADB} \simeq 3.5\)

Добавили \(CD\). \(t_{ADCB} = 4\)

** История развития
#+begin_examp org
Допустим, умирает муж, у которого было три жены. Оставляет состояние в 400 зуз.
Ктуба одной из жен предусматривала 100 зуз, второй -- 200 зуз, третей -- 300 зуз.
#+end_examp

#+begin_sol org
Нужно разделить:
- 50
- 125
- 225

Нужно разделить так, чтобы никакие две не могли объединиться против третьей.
| Коалиция     | Гарантия | Талмуд  | Выигрыш |
|--------------+----------+---------+---------|
| \(\{1\}\)    | \(0\)    | \(50\)  | \(50\)  |
| \(\{2\}\)    | \(0\)    | \(125\) | \(125\) |
| \(\{3\}\)    | \(100\)  | \(225\) | \(125\) |
| \(\{1, 2\}\) | \(100\)  | \(175\) | \(75\)  |
| \(\{1, 3\}\) | \(200\)  | \(275\) | \(75\)  |
| \(\{2, 3\}\) | \(300\)  | \(350\) | \(50\)  |
#+end_sol

