#+SETUPFILE: setup.org
#+TITLE: ДЗ 2

#+begin_task org
В алфавите племени Дюжина ровно 12 букв. Словом в этом языке является
любая последовательность не более чем из 6 букв, в которой любые две соседние
буквы различны. Сколько слов в языке племени?
#+end_task
#+begin_solution org
Есть 12 вариантов выбрать первую букву. Следующая не может той же что и первая, поэтому вариантов выбрать вторую букву 11. Аналогично для последующих.
Значит что есть \(12 \cdot 11^n\) вариантов составить слово длины \(n + 1\). Слов длиной не больше чем \(6\):
\[ \sum_{0 \le i \le 6} 12 \cdot 11^i = 2125872 \]
#+end_solution
#+begin_answer org
\(2125872\)
#+end_answer


-----

#+begin_task org
Шесть друзей купили абонементы в фитнес-клуб. В их абонементы входит
возможность посещения групповых занятий по плаванию, боксу, йоге и кроссфиту
(можно записаться хоть во все четыре группы)? Каким количеством способов друзья
могут выбрать себе занятия, если известно, что каждый из них записался хотя бы в
одну группу?
#+end_task
#+begin_solution org
Каждый может выбрать или не выбрать каждую группу. То есть всего возможных вариантов \(2^4 = 16\), но при один из этих вариантов, в котором не выбрана ни одна группа, не возможен по условию.
Значит для каждого есть \(16 - 1 = 15\) вариантов. Значит для 6 человек возможных вариантов \(15^6 = 11390625\).
#+end_solution
#+begin_answer org
\(11390625\)
#+end_answer


-----

#+begin_task org
Сколькими способами можно поставить на шахматную доску так, чтобы
они не били друг друга, двух белых ферзей?
#+end_task
#+begin_solution org
Покажем для начала сколько клеток по диагоналям бъет ферзь в зависимости от положения:
\-
#+begin_export latex
\begin{center}
\begin{tikzpicture}[x=6mm,y=6mm]
\draw[fill=black!30,even odd rule] (0,0) 
foreach \n in {1,2,3,4} { -- ++ (8,0) -- ++ (0,1) -- ++ (-8,0) -- ++ (0,1) } -- (8,8)

foreach \n in {1,2,3,4} { -- ++ (0,-8) -- ++ (-1,0) -- ++ (0,8) -- ++ (-1,0) } -- cycle

foreach[count=\n] \m in {a,b,...,h} { (-0.4,\n-0.5) node {\n} (\n-0.5,-0.5) node {\m} };
\node at (0.5, 7.5) {\(7\)};
\node at (7.5, 0.5) {\(7\)};

\node at (6.5, 1.5) {\(9\)};
\node at (1.5, 6.5) {\(9\)};

\node at (2.5, 5.5) {\(11\)};
\node at (5.5, 2.5) {\(11\)};

\node at (3.5, 4.5) {\(13\)};
\node at (4.5, 3.5) {\(13\)};
\end{tikzpicture}
\end{center}
#+end_export
Заметим что доска делится на 4 "окружности". В \(i\)-той окружности всего \((8 - 2i) \cdot 2 + (8 - 2i - 2) \cdot 2 = 28 - 8i\) клеток. Поставив ферзя на клетку на \(i\)-той окружности получим,
что он бъет по 7 клеток по вертикали и по горизонтали и \(7 + 2i\) по диагоналям, т.е. \(21 + 2i\) клеток. Получается что остается \(64 - (21 + 2i) - 1 = 42 - 2i\) клеток куда можно поставить второго. Также заметим что результат получится в два раза больше, т.к. при таком рассуждении различаем ферзей:
\[ \frac{\sum_{0 \le i \le 3} (28 - 8i) \cdot (42 - 2i)}{2} = 1288 \]
#+end_solution
#+begin_answer org
\(1288\)
#+end_answer


------

#+begin_task org
Вася нарисовал таблицу 7 × 7 и хочет поставить в нее 11 крестиков так,
чтобы получилась центрально-симметричная конфигурация. Сколькими способами
Вася может это сделать?
#+end_task
#+begin_solution org
Заметим что один крестик всегда должен быть в центре, т.к. 11 нечетное. Остается расставить 10 крестиков. Также заметим что на центральной
горизонтали и вертикали может стоять либо 2, либо 6 крестиков, чтобы оставшееся число крестиков было кратно 4. Способов расставить \(n\) крестиков на центральные диагональ и вертикаль \(\binom{6}{n / 2}\) (всего 3 по горизонтали и 3 по вертикали). Способов расставить \(n\) крестиков не по центральной горизонтали и вертикали \(\binom{9}{n / 4}\) (квадрат \(3 \times 3\)).
    \[ \sum_{i \in \{2, 6\}} \binom{6}{i / 2} \cdot \binom{9}{(10 - i) / 4} = \binom{6}{1} \cdot \binom{9}{2} + \binom{6}{3} \cdot \binom{9}{1} = 396 \]
#+end_solution
#+begin_answer org
\(396\)
#+end_answer

-------

#+begin_task org
Вася вновь нарисовал таблицу, только теперь размера \(4 \times 4\), и хочет заполнить ее цифрами \(1, 2, 3\) и \(4\) так, чтобы в каждой строчке и в каждом столбце
никакая цифра не повторялась. Сколькими способами Вася может это сделать?
#+end_task
#+begin_solution org
Расставим числа в \(0\)-ю строчку. Всего будет \(4!\) варинатов это сделать. Обозначим проставленные числа символами \(a, b, c, d\):
#+begin_export latex
\begin{center}
\begin{tikzpicture}[x=6mm,y=6mm]
\draw (0,0) 
foreach \n in {1,2} { -- ++ (4,0) -- ++ (0,1) -- ++ (-4,0) -- ++ (0,1) } -- (4,4)
foreach \n in {1,2} { -- ++ (0,-4) -- ++ (-1,0) -- ++ (0,4) -- ++ (-1,0) } -- cycle

\node at (0.5, 4.5) {\(0\)};
\node at (-0.5, 3.5) {\(0\)};

\node at (0.5, 3.5) {\(a\)};
\node at (1.5, 3.5) {\(b\)};
\node at (2.5, 3.5) {\(c\)};
\node at (3.5, 3.5) {\(d\)};

\end{tikzpicture}
\end{center}
#+end_export

Далее покажем что есть два варианта, как могут быть расставлены символы на \(1\)-й строке. В первом варианте есть две пары столбцов с одинаковым набором символов: \(\substack{ABCD\\BADC}\). В другом нет столбцов в одинаковым набором символов: \(\substack{ABCD\\BCDA}\). Заглавные буквы -- мета-символы для символов. Получается что в первом случае есть 4 варианта заполнить 2-ю строчку: \(CDBA, CDAB, DCBA, DCAB\). Во втором случае всего 2: \(CDAB, DABC\). Посчитаем, сколько получается расстоновок в 1-й строчке, соответствующих первому варианту: \(badc, cdab, dcba\). Остальных вариантов 6: \(bcda, bdac, cadb, cdba, dabc, dcab\).
Последняя строчка расставляется однозначно. Тогда можем посчитать общее количество:
\[ 4! \cdot (3 \cdot 4 + 6 \cdot 2) = 576 \]
#+end_solution
#+begin_answer org
\(576\)
#+end_answer

--------------


#+begin_task org
Сколько существует шестизначных чисел, кратных шести и не содержащих
в своей десятичной записи шестёрку?
#+end_task
#+begin_solution org
Обозначим за \(N^r_k\) -- количество различных сумм из \(k\) однозначных чисел, таких что в остатке при делении на 3 дают \(r\). Пусть \(D^r_k\) -- общее число сумм длины \(k\), кратных \(r\). Чтобы посчитать \(N^r_{k + 1}\) вычтем из \(D^r_{k + 1}\) количество сумм с 1, 2, \dots, k + 1 шестерками. Заметим что шестерка в сумме не меняет остаток \(r\).
\[ N^r_k = D^k_n - \sum_{1 \le i \le k} \binom{k}{i} \cdot N^r_{k - i} \]
Т.к. число должно быть также кратно 3, то последняя цифра должна быть \(0, 2, 4, 8\). И первая цифра должна быть не равна 0 и 6. Получается что всего таких чисел:
\begin{align}
  & N^1_4 + N^2_4 + N^0_4 + N^1_4 + N^2_4 + N^1_4 + N^2_4 + N^0_4 + \\
  & + N^0_4 + N^1_4 + N^2_4 + N^0_4 + N^1_4 + N^0_4 + N^1_4 + N^2_4 + \\
  & + N^2_4 + N^0_4 + N^1_4 + N^2_4 + N^0_4 + N^2_4 + N^0_4 + N^1_4 + \\
  & + N^0_4 + N^1_4 + N^2_4 + N^0_4 + N^1_4 + N^0_4 + N^1_4 + N^2_4 = \\
  & = 11 N^0_4 + 11 N^1_4 + 10 N^2_4
\end{align}
Посчитаем \(D^r_k\). Сумма размера \(r\) -- это сумма размера \(k - 1\) с дополнительным числом. С учетом остатка:
\[ D^r_k = 4 \cdot D^r_{k - 1} + 3 \cdot D^{r + 1 \bmod 3}_{k - 1} + 3 \cdot D^{r + 2 \bmod 3}_{k - 1} \]
\[ D^0_0 = 1 \quad D^1_0 = D^2_0 = 0 \]
\[ D^0_1 = 4 \quad D^1_1 = D^2_1 = 3 \]
\[ D^0_2 = 4 \cdot 4 + 3 \cdot 3 + 3 \cdot 3 = 34 \quad D^1_2 = D^2_2 = 4 \cdot 3 + 3 \cdot 4 + 3 \cdot 3 = 33 \]
\[ D^0_3 = 4 \cdot 34 + 3 \cdot 33 + 3 \cdot 33 = 334 \quad D^1_3 = D^3 = 4 \cdot 33 + 3 \cdot 34 + 3 \cdot 33 = 333 \]
\[ D^0_3 = 4 \cdot 334 + 3 \cdot 333 + 3 \cdot 333 = 3334 \quad D^1_3 = D^3 = 4 \cdot 333 + 3 \cdot 334 + 3 \cdot 333 = 3333 \]

Посчитаем \(N^r_k\):
\[ N^0_0 = 1 \quad N^1_0 = N^2_0 = 0 \]
\[ N^0_1 = N^1_1 = N^2_1 = 3 \]
\[ N^0_2 = 34 - 2 \cdot 3 - 1 = 27 \quad N^1_2 = N^2_2 = 33 - 2 \cdot 3 = 27 \]
\[ N^0_3 = 334 - 3 \cdot N^0_2 - 3 \cdot N^0_1 - N^0_0 = 243 \]
\[ N^1_3 = N^2_3 = 333 - 3 \cdot N^1_2 - 3 \cdot N^1_1 - N^1_0 = 243 \]
\[ N^0_4 = N^1_4 = N^2_4 = 3334 - 4 \cdot N^0_3 - 6 \cdot N^0_2 - 4 \cdot N^0_1 - N^0_0 = 2187 \]
\[ 11 N^0_4 + 11 N^1_4 + 10 N^2_4 = 32 \cdot N^0_4 = 69984 \]
#+end_solution
#+begin_answer org
69984
#+end_answer

