#+title: HW 6

* Statements
Составьте запросы в терминах языков Datalog и SQL для базы данных «Университет», позволяющие получать

1. Информацию о студентах
   1. С заданным ФИО (StudentId, StudentName, GroupId по :StudentName).
   2. Учащихся в заданной группе (StudentId, StudentName, GroupId по :GroupName).
   3. C заданной оценкой по дисциплине, заданной идентификатором (StudentId, StudentName, GroupId по :Mark, :CourseId).
   4. C заданной оценкой по дисциплине, заданной названием (StudentId, StudentName, GroupId по :Mark, :CourseName).
2. Полную информацию о студентах
   1. Для всех студентов (StudentId, StudentName, GroupName).
   2. Студентов, не имеющих оценки по дисциплине, заданной идентификатором (StudentId, StudentName, GroupName по :CourseId).
   3. Студентов, не имеющих оценки по дисциплине, заданной названием (StudentId, StudentName, GroupName по :CourseName).
   4. Студентов, не имеющих оценки по дисциплине, у которых есть эта дисциплина (StudentId, StudentName, GroupName по :CourseId).
   5. Студентов, не имеющих оценки по дисциплине, у которых есть эта дисциплина (StudentId, StudentName, GroupName по :CourseName).
3. Студенты и дисциплины, такие что у студента была дисциплина (по плану или есть оценка)
   1. Идентификаторы (StudentId, CourseId).
   2. Имя и название (StudentName, CourseName).
4. Студенты и дисциплины, такие что дисциплина есть в его плане, и у студента долг по этой дисциплине
   1. Долгом считается отсутствие оценки (StudentName, CourseName).
   2. Долгом считается оценка не выше 2 (StudentName, CourseName).
   3. Долгом считается отсутствие оценки или оценка не выше 2 (StudentName, CourseName).
5. Идентификаторы студентов по преподавателю
   1. Имеющих хотя бы одну оценку у преподавателя (StudentId по :LecturerName).
   2. Не имеющих ни одной оценки у преподавателя (StudentId по :LecturerName).
   3. Имеющих оценки по всем дисциплинам преподавателя (StudentId по :LecturerName).
   4. Имеющих оценки по всем дисциплинам преподавателя, которые он вёл у этого студента (StudentId по :LecturerName).
6. Группы и дисциплины, такие что все студенты группы имеют оценку по предмету
   1. Идентификаторы (GroupId, CourseId).
   2. Названия (GroupName, CourseName).

* Comments
- 1.1
- 1.2
- 1.3
- 1.4
- 2.1
- 2.2
- 2.3
- 2.4
  - SQL: Слишком много декартовых произведений: 4
- 2.5
  - SQL: Слишком много декартовых произведений: 6
- 3.1
- 3.2
- 4.1
  - SQL: Слишком много декартовых произведений: 3
- 4.2
  - SQL: Слишком много декартовых произведений: 4
- 4.3
  - SQL: Слишком много декартовых произведений: 4
- 5.1
  - SQL: Слишком много декартовых произведений: 3
- 5.2
  - SQL: Слишком много декартовых произведений: 3
- 5.3
  - SQL: Слишком много декартовых произведений: 2
  - SQL: Использование операций над множествами: 2
- 5.3
  - SQL: Слишком много декартовых произведений: 2
  - SQL: Использование операций над множествами: 2
- 6.1
  - SQL: Слишком много декартовых произведений: 3
  - SQL: Слишком много подзапросов: 4
  - SQL: Использование операций над множествами: 2
- 6.2
  - SQL: Слишком много декартовых произведений: 5
  - SQL: Слишком много подзапросов: 5
  - SQL: Использование операций над множествами: 2
