#+setupfile: setup.org
#+TITLE: Лекция 2
#+date: 8 сентября


* Декодирование
#+begin_definition org
Критерий минильного расстояния \(X = Y\). Декодер ищет кодово слово
\[ c = \argmin_{c \in \Co} d(c, y) \]
#+end_definition

#+begin_definition org
Алгоритм называется алгоритмом полного декодирования по критерию \(K\), если он способен найти решение соответствующуй оптимизационной задачи для любого возможного принятого сигнала
#+end_definition

* Метрики
#+begin_definition org
Функция \(d(x, y)\) называется метрикой, если:
- \(d(x, y) \ge 0, d(x, y) = 0 \Leftrightarrow x = y\)
- \(d(x, y) = d(y, x)\)
- Неравенстно треугольника \(d(x, y) + d(y, z) \ge d(x, z)\)
#+end_definition

#+begin_definition org
Метрическое пространство -- множество \(X\) с определенной на нем метрикой
#+end_definition

#+begin_examp org
Расстояние Хемминга \(d_H (x, y) = |\{i|x_i \neq y_i\}|\). Двоичный симметричный канал \((p < 0.5, X = Y = \{0, 1\}\):
\[ \hat{c} = \argmax_{x \in \Co} \prod_{i = 1}^n P\{y_i|c_i\} = \dots = \argmin_{c \in \Co} \sum_{i = 1}^na |y_i - c_i| \]
#+end_examp

#+begin_examp org
Расстояние Евклида \(d_E(x, y) = \sqrt{\sum_{i = 1}^n (x_i - y_i)^2}\). Аддитивный Гауссовский канал с амплитудно-импульсной модуляцией \((Y = \R^n)\).
#+end_examp

#+begin_examp org
Расстояние Ли \((A = GF(q)^n): d_L(x, y) = \sum_{i = 1} \min(|x_i - y_i|, q - |x_i - y_i|)\). Аддитивный Гауссовский канал с \(q\)-ичной фазовой модуляцией
#+end_examp

#+begin_examp org
Ранговое расстояние \((A = GF(q)^{n \times m}): d_R (x, y) = \rank(x - y)\). Сетевые коды
#+end_examp



* Кодирование
Операция канального кодирования вносит в информационную
последовательность избыточность, необходимую для последующего
исправления возможных ошибок

Блоковые коды преобразуют блок из \(k\) символов в блок из \(n\) символов. Преобразование отдельных блоков выполняется независимо

Сверточные коды преобразуют блок из \(k\) символов в блок из \(n\) символов. Преобразование зависит от предыдущих блоков.

** Блоковые коды
\(n\) -- длина коды \(\Co\). Для исправления ошибок требуется, чтобы не
все \(|X|^n\) последовательностей были кодовыми словами. Мощность кода
(число различных кодовых слов) \(M = |C|\).

#+begin_rem org
Скорость кода: \(R = \frac{\log_{|X|}M}{n} \).
#+end_rem

#+begin_definition org
Минимальным расстоянием кода называется минимальное расстояние Хемминга между его различными кодовыми словами
#+end_definition
#+begin_examp org
Пример \(C = \{000, 111\}, d_{m \times n}(C) = 3\)
#+end_examp

#+begin_rem org
Хеммингов шар радиуса \(d_\min - 1\), описанный вокруг кодового слова \(c \in C\), не содержит никаких других кодовых слов
#+end_rem

#+begin_statement org
Код с минимальныи расстоянием Хемминга \(d\) способен исправить \(\left\llbracket \frac{d - 1}{2} \right\rrbracket\)
#+end_statement

** Линейный код
#+begin_definition org
*Линейным \((n, k)\) (длины \(n\) размерностью \(k\)) кодом* \(C\) называется \(k\)-мерное линейное подпространство \(n\)-мерного линейного пространства над полем \(GF(q)\).
#+end_definition

#+begin_rem org
Число кодовых слов равно \(q^k\)
#+end_rem

#+begin_definition org
Порождающая \(k \times n\) матрица полного ранга \(G: C = \{y = xG|x \in GF(q)^k\}\)
#+end_definition
#+begin_definition org
Проверочная матрица \(r \times n\), \(H: C = \{y \in GF(q)^n|yH^T = 0\}\), \(r \ge n - k = \rank(H)\)
\[ GH^T = 0 \]
#+end_definition

#+begin_rem org
С помощью линейных операций над стоками и перестановок столбцов порождающая матрица может быть приведена к виду \(G = (I | A)\). \\
*NB* Вообще говоря перестановкой столбцов получаеи порождающую матрицу другого коды, поэтому перестановка столбцов в порождающей матрице должна быть согласована с перестановкой в проверочной
#+end_rem

#+begin_rem org
Систематическое кодирование \(xG = (x | xA)\) -- информационный вектор является подвектором кодого слова. Применение систематического кодирования упрощает декодирование
\[ H = (A^T|-I) \]
#+end_rem

#+begin_statement org
Минимальное расстояние линейного блокового кода \(\Co\) равно \(d = \min_{\substack{c' \neq c'' \\ c', c'' \in \Co}} d(c', c'') = \min_{c \in \Co \setminus \{0\}} wt(c)\), где \(wt(c)\) -- вес вектора (количество единиц)
#+end_statement
#+begin_proof org
Расстояние между двумя векторами -- число позиций в которых они отличаются
#+begin_export latex
\begin{center}
\begin{align*}
  d(c', c'') = \sum_{i = 0}^n d(x, y) = \sum_{i = 0}^n d(0, x - y) = d(0, c' - c'')
\end{align*}
\end{center}
#+end_export
Так как код образует линейное подпространство, значит он группа по сложение, значит \(c' - c''\) -- кодовое слово. \(wt(c)\) -- вес Хемминга
#+end_proof

#+begin_statement org
Если \(H\) -- проверочная матица кода длины \(n\), то код имеет размерность \(n - r\) \(\Leftrightarrow\) существуют \(r\) линейно независимых столбцов матрицы \(H\), а любые \(r + 1\) столбцов линейно независимы
#+end_statement

#+begin_statement org
Если \(H\) -- проверочная матрица кода длины \(n\), то код имеет минимальное расстояние \(d\) \(\Leftrightarrow\) любые \(1, 2, \dots, d - 1\) столбцов \(H\) линейно независимы, но существуют \(d\) линейно зависимых столбцов матрицы \(H\)
#+end_statement

#+begin_rem org
Принадлежность коду \(yH^T = 0\) эквивалентна ЛЗ столбцов
#+end_rem

#+begin_statement org
Граница Синглтона (верхняя): для любого \((n, k, d)\) линейного кода \(n - k \ge d - 1\)
#+end_statement
#+begin_corollary org
Ранг матрицы \(H\) (максимальное число ЛНЗ столбцов) не может превосходить \(n - k\)
#+end_corollary

#+begin_definition org
Граница Синглтона для произовльных кодов \(A_q(n, d) \le q^{n - d + 1}\)
#+end_definition

#+begin_definition org
Коды с \(n - k = d - 1\) называются *разделимыми* кодами с максимальным достижимым расстоянием
#+end_definition

    
** Простейшие коды
#+begin_examp org
Пусть \(G\) -- обратимая \(n \times n\) матрица. Она порождает код \((n, n, 1)\).
#+end_examp

#+begin_examp org
\((n, 1, n)\) код с \(n\)-кратным повторением: \(G' = (11\dots 1)\),
#+begin_export latex
\begin{center}
\begin{align*}
H' = \begin{pmatrix}
  1 & 0 & 0 & \dots & 0 & 1 \\
  0 & 1 & 0 & \dots & 0 & 1 \\
  0 & 0 & 1 & \dots & 0 & 1 \\
  \vdots & \vdots & \vdots & \ddots & \vdots & \vdots \\
  0 & 0 & 0 & \dots & 1 & 1
\end{pmatrix}
\end{align*}
\end{center}
#+end_export
#+end_examp

#+begin_examp org
\((n, n - 1, 2)\) код с проверкой на четность:
#+begin_export latex
\begin{center}
\begin{align*}
G'' = \begin{pmatrix}
  1 & 0 & 0 & \dots & 0 & 1 \\
  0 & 1 & 0 & \dots & 0 & 1 \\
  0 & 0 & 1 & \dots & 0 & 1 \\
  \vdots & \vdots & \vdots & \ddots & \vdots & \vdots \\
  0 & 0 & 0 & \dots & 1 & 1
\end{pmatrix}, 
H'' = \begin{pmatrix} 1 & 1 & \dots & 1 \end{pmatrix}
\end{align*}
\end{center}
#+end_export

#+end_examp
