#+setupfile: setup.org
#+TITLE: Лекция 7
#+date: 20 октября

* Функция переходных вероятностей канала
Канал без памяти с входныи алфавитом \(\mathcal{X\} = \{0, 1\}\). Дискретный выходной алфавит \(\matchal{Y}\).

#+begin_definition org
\(W(y | c)\)  -- вероятность наблюдения на выходе канала \(y \in \mathcal{Y}\) при условии подачи на его вход \(c \in \mathcal{X}\)
#+end_definition

#+begin_examp org
Двоичный симметричный канал: \(\mathcal{Y} = \mathcal{X}, W(y | c) = \begin{cases} p & , y \neq x \\ 1 - p & , y = x \end{cases}\)
#+end_examp
#+begin_examp org
Двоичный стирающий канал \(\mathcal{Y} = \{0, 1, \varepsilon\}\): \(W(y|c) = \begin{cases} p & , y = \varepsilon \\ 1 - p & , y = x \in \{0, 1\} \end{cases} \)
#+end_examp
#+begin_examp org
Двоичный симметричный канал со стираниями \(\mathcal{Y} = \{0, 1, \varepsilon, W (y|c) = \begin{cases} 1 - p - s & , y= x \\ s & , y=\varepsilon \\ p &, y = 1 - x \end{cases} \)
#+end_examp
Непрервыный выходной алфавит \(\mathcal{Y}\). \(W(y | c)\) -- плотность распределения выходного символа канала при подаче \(c\) на его вход. Аддитивный науссовский канал: \\
\(\mathcal{Y} = \R, y= (-1)^c + \eta, \eta \sim \mathcal{N}(0, \sigma^2), W(y|c) = \frac{1}{\sqrt{2\pi \sigma^2}} e^{-\frac{|y-(-1)^c|^2}{2\sigma^2}}\)
Для простоты, будем считать \(\mathcal{Y}\) дискретным

* Параметр Бхаттачарьи
Рассмотрим приемник по максимуму прадоподобия \(\tilde{c} = \argmax_{c \in {0, 1}} W(y |c )\). Передаваемые символы рановероятны. Вероятность ошибки
#+begin_export latex
\begin{center}
\begin{align*}
P_c & = P\{c=0\}P\{err | e =0\} + P\{c = 1\} P\{err | c = 1\} = \\
& = \frac{1}{2} \sum_{y: W(y | 0) < W(y | 1)} W(y | 0) + \frac{1}{2} \sum_{y: W(y | 1) < W(y | 0)} W(y|1) = \\
& = \frac{1}{2} \sum_{y: \frac{W(y|1)}{W(y|0)} > 1} W(y|0) + \frac{1}{2} \sum_{y: \frac{W(y|0)}{W(y | 1)} > 1} W(y | 1) =
& = \frac{1}{2} \sum_{y \in \mathcal{Y}} \sum_{c \in \{0, 1\}} \left( W(y|c) \chi\left(\frac{W(y | 1 - c)}{W(y | c)}\right)\right)
\end{align*}
\end{center}
#+end_export

Индикаторная фунукция \(\chi(z) = \begin{cases} 1 & , z \ge 1 \\ 0 & , z < 1 \end{cases}\)
\[ P_c \le \frac{1}{2} \sum_{y \in \mathcal{Y}} \sum_{c \in \{0, 1\}} \left( W(y|c) \chi\left(\frac{W(y | 1 - c)}{W(y | c)}\right)\right) = \sum_{y\in\mathcal{Y}} \sqrt{W(y|0)W(y | 1)} = Z(W) \]

#+begin_examp org
Двоичный стирающий канал
\[ Z(BEC(p)) = \sqrt{W(0 | 0) W(0 | 1)} + \sqrt{W(1 | 0) W(1 | 1)} + \sqrt{W(\varepsilon|0)W(\varepsilon | 1)} = p \]
#+end_examp

#+begin_examp org
Аддитивный гауссовский канал:
\[ Z(\mathcal{G}(\sigma)) = \int_{-\infty}^\infty \sqrt{W(y | 0) W(y | 1)} dy = \frac{1}{\sqrt{2 \pi \sigma^2}} \int_{-\infty}^\infty e^{-\frac{(y - 1)^2 + (y + 1)^2}{2\sigma^2}} dy = \frac{e^{-\frac{1}{2\sigma^2}}}{\sqrt{2\pi\sigma^2}} \int_{-\infty}^\infty e ^{-\frac{y^2}{2 \sigma^2}} dy = e ^{-\frac{1}{2\sigma^2}} \]
#+end_examp


* Пропускная способность канала
\[ I(W) = \max_{\{p(x)\}}\sum_{x \in \mathcal{X}} \sum_{y \in \mathcal{Y}} W(y | x) P\{x\} \log \frac{W(y | x)}{W(y)} \]
Сущесутвуют методы сколь угодно надежной передачи данных со скоростью \(R < I(W)\). При передаче данных со скоростью \(R > I(W)\) вероятность ошибки ограничена снизу положительной величиной. Для многих каналов оптимальным распределением символов на входе \(P\{x\}\) является равномерное

* Поляризация канала
Рассмотрим линейное преобразование, задаваемое \todo (Картинка)
\[ \begin{pmatrix} c_0 & c_1 \end{pmatrix} = \begin{pmatrix} u_0 & u_1 \end{pmatrix} \begin{pmatrix} 1 & 0 \\ 1 & 1 \end{pmatrix} \]
Двоичный стирающий канал: \(y = \begin{cases} c_i & , \text{с вероятностью } 1 - p \\ e & , \text{с вероятностью } p \end{cases}\)

- \(u_0\) не может быть восстановлен из \(y_0, y_1\) с вероятностью \(1 - (1 - p)^2 = 2p - p^2 \ge p\)
- \(u_1\) не может быть восстановлен из \(u_0, y_0, y_1\) с вероятностью \(p^2 \le p\)

* Битовые подканалы
Пусть \(A_m = \begin{pmatrix} 1 & 0 u 1 & 1 \end{pmatrix} ^{\otimes m}\), где \(\otimes m\) обозначает \(m\)-кратное произведение Кронекерера матрица с собой. Пусть \(n = 2^m\).
#+begin_definition org
Кратная запись подвекторов \(y_a^b = (y_a, y_{a + 1}, \dots, y_b)\)
#+end_definition
\[ W_m(y_0^{n - 1} | c_0^{n - 1}) = \prod_{i_0}^{n - 1}W(y_i | c_i) \]
Синтетические битовые подканалы
#+begin_export latex
\begin{center}
\begin{align*}
W_m^{(i)} (y_0^{n - 1}, u_0^{i - 1} | u_i) & = \frac{W_m^{(i)} (y_0^{n - 1}, u_0^i)}{P\{u_i\}} = 2 \sum_{u_{i+1}^{n - 1} \in \mathbb{F}_2^{n - 1}} W_m^{(n - 1)} (y_0^{n - 1} | u_0^{n - 1}) P\{u_0^{n - 1}\} = \\
& = \frac{2}{2} \sum_{?} W_m (y_0^{n - 1} | u_0^{n - 1} A_m) = 2 ^{-n + 1} \sum_{?} \prod_{?}^{n - 1} W(y_j | (u_0^{n - 1}A_m)) \fixme
\end{align*}
\end{center}
#+end_export

* Функция переходных вероятностей битовых подканалов
\[ W_1^{(0)} (y_0, y_1 | u_0) = \frac{1}{2} \sum_{u_1 = 0} ^ 1 W(y_0 | u_0 + u_1) W(y_1 | u_1) \]
\[ W_1(y_0, y_1, u_0 | u_1) = \frac{1}{2} W(y_0 | u_0 + u_1) W(y_1 | u_1) \]


* Рекурсивное определение подканалов
#+begin_export latex
\begin{center}
\begin{equation*}
W_\lambda^{2i} (y^{2^\lambda - 1}, u_0^{2i - 1} | u_{2i}) = \frac{1}{2} \sum_{u_{2i + 1 = 0}}^1 W_{\lambda - 1}^{(i)} (y_{0,{\rm even}}^{2^\lambda - 1}, u_{0, {\rm even}}^{2i - 1} + u_{0, {\rm odd}}^{2i - 1} | u_{2i} + u_{2i + 1}) W_{\lambda - 1}^{(i)} (y_{0, {\rm odd}}^{2^\lambda - 1}, u_{0, {\rm odd}}^{2i - 1} | u_{2i + 1}) \\
W_{\lambda}^{(2i + 1)} (y_0^{2^\lambda - 1}, u_0^{2i} | u_{2i + 1}) = \frac{1}{2} W_{\lambda - 1}^{(i)} (y_{0,{\rm even}}^{2^\lambda - 1}, u_{0, {\rm even}}^{2i - 1} + u_{0, {\rm odd}}^{2i - 1} | u_{2i} + u_{2i + 1}) W_{\lambda - 1}^{(i)} (y_{0, {\rm odd}}^{2^\lambda - 1}, u_{0, {\rm odd}}^{2i - 1} | u_{2i + 1})
\end{equation*}
\end{center}
#+end_export

\todo Картинка ez

* Параметры подканалов
#+begin_definition org
*Параметры Бхаттачарьи* битовых подканалов \(Z_{m, i} = Z(W_m^{(i)})\)
\[ Z_{m, 2i + 1} \le Z{m, 2i} \le 2 Z_{m-1, i} - Z_{m-1, i}^2 \]
\[ Z_{m, 2i + 1} = Z_{m - 1, i}^2 \]
Строгое равенство в случае двоичного стирающего канала
#+end_definition

Пропускные способности битовых подканалов \(I_{m, i}  = I(W_m^{(i)})\)
\[ I_{m ,2i} + I_{m, 2i + 1} = 2 I_{m - 1, i} \]
\[ I_{m, 2i} \le I_{m, 2i + 1} \]
\[ \sqrt{1 - Z(W)^2} \ge I(W) \ge \log \frac{2}{1 + Z(W)} \]

Для любого \(\delta \in (0, 1)\) при \(m \to \infty\) доля подканалов с \(I(W_m^{(i)} \in (1 - \delta, 1]\) стермиться к \(I(W_0^{(0)} - I(W)\), а доля подканалов с \(I(W_m^{(i)} \in [0, \delta)\) стремится к \(1 - I(W)\)

Поляризация каналов:
\todo Картинка
# https://youtu.be/TV7berfUX4c?list=PLd7QXkfmSY7YEom7j8DGk8EBw5O5SZDQs&t=394
- Доля недополяризованных подканалов убывает с увеличением \(m\)
- Число недополяризованных подканалов растет с увеличением \(m\)

* Полярный код и алгоритм последовательного исключения
Передавать предопределенные значения (например, 0) по плохим подканалам. Кодирование \(c_0^{n - 1} = u_0^{n - 1}A_m, u_i = 0, i \in \mathcal{F}\), где \(\mathcal{F}\) -- множество номером плохих подканалов (замороженных символов). Линейный блоковый код \((2^m, 2^m + |\mathcal{F}|)\)

#+begin_export latex
\begin{enalgo}[H]
\caption{Алгоритм последовательного исключения}
\begin{algorithmic}[1]
\FOR{\(i = 0, 1, \dots, 2^m - 1\)}
  \STATE \(\hat{u}_i = \begin{cases} 0 & , i \in \mathcal{F} \\ \argmax_{u_i} W_m^{(i)} (y_0^{n-1}, \hat{u}_0^{i - 1} | u_i) & , i \not\in \mathcal{F} \end{cases}\)
\ENDFOR
\end{algorithmic}
\end{enalgo}
#+end_export
- Если предыдущие решения были правильными, то \(\hat{u}_0^{i - 1} = u_0^{i - 1}\)
Если ранее была допущена ошибка, алгоритм ПИ все равно не сможет ее исправить. Вероятность ошибки \(P \le \sum_{i \not\in \mathcal{F}} Z_{m, i} \le 2^{-n^\beta}, \beta < 0.5\)

** Сложность кодирования
\[ u_0^{n - 1} A_m = \begin{pmatrix} u_0^{n / 2 - 1} & u_{n/2}^{n - 1} \end{pmatrix} \begin{pmatrix} A_{m - 1} & 0 \\ A_{m - 1} & A_{m - 1} \end{pmatrix} = \begin{pmatrix} (u_0^{n / 2 - 1} + u_{n / 2}^{n - 1}) A_{m - 1} & u_{n/2}^{n - 1}A_{m - 1} \end{pmatrix} \]
Сложность \(T(n) = 2T(n / 2) + n / 2 = \frac{1}{2} n \log_2 n\)

** Декодер с ЛОПП
Логарифмическое отношение правдоподобия \(L_m^{(i)} (y_0^{n - 1}, u_0^{i - 1}) = \ln \frac{W_m^{(i)} (y_0^{n - 1}, u_0^{i - 1} | 0)}{W_m^{(i)} (y_0^{n - 1}, u_0^{i - 1} | 1)}\)

#+begin_export latex
\begin{center}
\begin{align*}
L_\lambda^{2i + 1} (y_0^{n - 1}, u_0^{i - 1}) & = \log \frac{W_{\lambda - 1}^{(i)} (y_{0, {\rm even}}^{2^\lambda - 1}, u_{0, {\rm even}}^{2i - 1} + u_{0, {\rm odd}}^{2i - 1} | u_{2i} + 0) W_{\lambda - 1}^{(i)} (y_{0, {\rm odd}}^{2^\lambda - 1}, u_{0, {\rm odd}}^{2i - 1} | 0)}{W_{\lambda - 1}^{(i)} (y_{0, {\rm even}}^{2^\lambda - 1}, u_{0, {\rm even}}^{2i - 1} + u_{0, {\rm odd}}^{2i - 1} | u_{2i} + 1) W_{\lambda - 1}^{(i)} (y_{0, {\rm odd}}^{2^\lambda - 1}, u_{0, {\rm odd}}^{2i - 1} | 1)} = \\
& = (-1)^{u_{2i}} L_{\lambda - 1}(y_{0, {\rm even}}^{2^\lambda - 1}, u_{0, {\rm even}}^{2i - 1} + u_{0, {\rm odd}}^{2i - 1}) + L_{\lambda - 1}(y_{0, {\rm odd}}^{2^\lambda - 1}, u_{0, {\rm odd}}^{2i - 1})
\end{align*}
\end{center}
Пусть
\begin{align*}
& p_s = W_\lambda^{(2i)} (s | y_0^{2^\lambda - 1}, u_0^{2i - 1}) = \frac{W_\lambda^{(2i)} (y_0^{2^\lambda - 1}, u_0^{2i - 1} | s) P\{u_{2i} = s\}}{W_\lambda^{(2i)} (y_0^{2^\lambda - 1}, u_0^{2i - 1})} = \frac{W_\lambda^{(2i)} (y_0^{2^\lambda - 1}, u_0^{2i - 1} | s)}{2W_\lambda^{(2i)} (y_0^{2^\lambda - 1}, u_0^{2i - 1})} \\
& p_{0s} = W_{\lambda - 1}^{(i)} (s | y_{0, {\rm even}}^{2^\lambda - 1}, u_{0, {\rm even}}^{2i - 1} + u_{0, {\rm odd}}^{2i - 1}) \\
& p_{1s} = W_{\lambda - 1}^{(i)} (s | y_{0, {\rm even}}^{2^\lambda - 1}, u_{0, {\rm even}}^{2i - 1}), s \in \{0, 1\} \\
& p_0 = p_{00}p_{10} + p_{01}p_{11} \\
& p_1 = p_{01}p_{10} + p_{00}p_{11}
\end{align*}
\[ p_0 + p_1 = 1, p_{i0} + p_{i1} = 1, i \in \{0, 1\} \]
\[ \tanh \left(\frac{1}{2} \ln \frac{p_0}{p_1}\right) = \frac{\exp(\ln(p_0 / p_1)) - 1}{\exp(\ln(p_0/ p_1)) + 1} = p_0 - p_1 = 1 - 2p_1  \]
\[ 1 - 2p_1 = (1 - 2p_{01})(1 - 2p_{11}) = 1 - 2(p_{01} + p_{11} - 2 p_{11}p_{01}) = 1 - 1(p_0(1 - p_{11}) + (1 - p_{01})p_{11}) \]
\[ \tanh \left( \frac{1}{2} L_\lambda^{(2i)} (y_0^{n - 1}, u_0^{2i - 1})\right) = \tanh \left(\frac{1}{2} L_{\lambda - 1}^{(i)} (y_{0, {\rm even}}^{2^\lambda - 1}, u_{0, {\rm even}}^{2i - 1} - u_{0, {\rm odd}}^{2i - 1}) \right) \tanh \left(\frac{1}{2} L_{\lambda - 1}^{(i)} (y_{0, {\rm odd}}^{2^\lambda - 1}, u_{0, {\rm odd}}^{2i - 1}) \right) \]
\[ L_\lambda^{(2i)}(y_0^{2^\lambda - 1}, u_0^{2i - 1}) = 2 \tanh^{-1} \left(\tanh\left(\frac{1}{2} L_{\lambda - 1}^{(i)} (y_{0, {\rm even}}^{2^\lambda - 1}, u_{0, {\rm even}}^{2i - 1} + u_{0, {\rm odd}}^{2i - 1})\right) \tanh \left(\frac{1}{2} L_{\lambda - 1}^{(i)} (y_{0, {\rm odd}}^{2^\lambda - 1}, u_{0, {\rm odd}}^{2i - 1}) \right) \right) \]
\[ L_\lambda^{(2i+ 1)}(y_0^{n - 1}, u_0^{2i}) = (-1)^{u_{2i}} L_{\lambda - 1}(y_{0, {\rm even}}^{2^\lambda - 1}, u_{0, {\rm even}}^{2i - 1} + u_{0, {\rm odd}}^{2i - 1}) + L_{\lambda - 1}(y_{0, {\rm odd}}^{2^\lambda - 1}, u_{0, {\rm odd}}^{2i - 1}) \]

\begin{enalgo}[H]
\caption{Алгоритм последовательного исключения}
\begin{algorithmic}[1]
\FOR{\(i = 0, 1, \dots, 2^m\)}
  \STATE \(\hat{u}_i = \begin{cases} 0 & , i \in \mathcal{F} \\ 0 & , L_m^{(i)} (y_0^{n-1}, \hat{u}_0^{i - 1}) > 0, i \not\in \mathcal{F} \\ 1 & ,  L_m^{(i)} (y_0^{n-1}, \hat{u}_0^{i - 1}) \le 0, i \not\in \mathcal{F} \end{cases}\)
\ENDFOR
\end{algorithmic}
\end{enalgo}
#+end_export


** Другой вариант алгоритма последовательного исключения
\[ W_m^{(i)} (u_0^i | y_0^{n - 1} d \frac{W_m^{(i)} (y_0^{n - 1}, \hat{u}_0^{i - 1}}}{2W(y_0^{n - 1})} = \omega \sum_{u_{i+1}^{n -1}} \prod_{j = 0}^{n - 1} W((u_0^{n - 1} A_m)| y_j) \]
\[ \color{red} W_\lambda^{(2i)} (u_0^{2i} | y_0^{n - 1}) = \omega \sum_{u_{2i + 1}} W_{\lambda - 1}^{(i)} ({\color{blue} u_{2t} + u_{2t + 1}, 0 \le t \le i} | {\color{green} y_{0, {\rm even}^{n - 1}}}) W_{\lambda - 1} ({\color{blue} u_{2t + 1} , 0 \le t \le i} | {\color{green} y_{0, {\rm odd}}^{n - 1}}}) \]
\[ \color{magenta} W_\lambda^{(2i + 1)} (u_0^{2i - 1} | y_0^{n - 1}) = \omega  \color{green} W_{\lambda - 1}^{(i)} (u_{2t} + u_{2t + 1}, 0 \le t \le i | y_{0, {\rm even}^{n - 1}}) W_{\lambda - 1} (u_{2t + 1} , 0 \le t \le i | y_{0, {\rm odd}}^{n - 1}}) \]

\todo Картинка:
зеленый -- принятый вектор

Переиспользование на фазе \(2i + 1\) сомножителей \(W_{\mu - 1}^{(i)}\), вычисленных на фазе \(2i\). При обновлени на слое \(\lambda\) вычисляют \(2^{m - \lambda}\) ЛОПП. Сложность \(C = \sum_{\lambda = 1}^m 2^\lambda \cdot 2^{m - \lambda} = m2^m = n\log_2 n\). Сложность \(O(n \log_2 n)\). Размер памяти \(O(n)\).

** Построение \((2^m, k)\) полярного кода
Замораживанию подлежат \(2^m - k\) наименее надежных символов (например, с наибольшим \(Z_{m, i}\). Двоичный стирающий канал
\[ Z_{m, 2i} = 2Z_{m - 1, i} - Z_{m - 1, i}^2 \]
\[ Z_{m, 2i + 1} = Z_{m - 1, i}^2 \]
Сложность вычисления \(Z_{m, i} = O(n)\). В общем случае выходной алфавит канала \(W_m^{(i)} (y_0^{n -1} , u_0^{i - 1} | u_i)\) имеет мощность \(|\mathcal{Y}|^n2^i\).
Построение функции переходных вероятностей \(W_m^{(i)}\) вычислительно нереализуемо уже при небольших \(m\). Можно аппроксимировать канал \(W_m^{(i)}\) каналом с выходным алфавитом фиксированной мощности \(\mu\), который был бы чуть лучше или чуть хуже, чем истинный \(W_m^{(i)}\). \(Z_{m, i}\) могут быть вычисленны со сложностью \(O(n\mu^2 \log \mu)\).

** Гауссовская аппроксимация
Полярные коды являются линейными. Для симметричных канало вероятность ошибки не зависит от того, какое кодовое слова передавалось. Будем считать, что передавалось \(0\) слово. Рассмотрим передачу кодовых слов по аддитивному гауссовскому каналу: \\
\(y_i = (-1)^{c_i} + \eta_i, \eta_i \sim \mathcal{N}(0, \sigma^2) \implies L_0^{(0)} (y_i) = \frac{2y_i}{\sigma^2} \). Т.к. все \(c_i = 0\). \\
\( M[L_0^{(0)} (y_i)] = \mu_{00} = \frac{2}{\sigma^2}\). \(D[L_0^{(0)}(y_i)] = \frac{4}{\sigma^2} = 2M[L_0^{(0)} (y_i)] \)

Предположим, что все ЛОПП имеют нормальное распределние \(\mathcal{L}_\lambda^{(i)} \sim N(\mu_{\lambda, i}, 2\mu_{\lambda, i}), 0 \le i < 2^\lambda, 0 \le \lambda \le m\)
\[ \mu_{\lambda, 2i} = \Theta (\mu_{\lambda - 1, i}) = \phi^{-1} \left( 1 - (1 - \phi(\mu_{\lambda - 1, i}))^2\right) \]
\[ \mu_{\lambda, 2i + 1} = 2 \mu_{\lambda - 1, i} \]
\[ \phi(x) = 1 - \frac{1}{\sqrt{4\pi x}} \int_{-\infty}^\infty \tanh \frac{u}{2} e^{- \frac{(u - x)^2}{4x}} du \]
Замораживаются символы с наименьшим \(\mu_{m, i}\)

#+begin_examp org
Кусочно-квадратичная аппроксимация
\[ \Theta(x) \approx \begin{cases} 0.9861x - 2.3152 & , x > 12 \\ x(9.005 \cdot 10^{-3}x + 0.7694) - 0.9507 & , x \in (3.5, 12] \\ x(0.062883x + 0.3678) - 0.1627 & , x \in (1, 3.5) \\ x(0.2202x + 0.066448) & ,\text{иначе}  \end{cases} \]
\todo Картинка
# https://youtu.be/TV7berfUX4c?list=PLd7QXkfmSY7YEom7j8DGk8EBw5O5SZDQs&t=2804
#+end_examp


* Конструкция Плоткина и коды Рида-Маллера
#+begin_theorem org
Пусть даны \((n, k_i, d_i)\) коды \(C_i, i=0,1\). \(C = \{(c_1 + c_0, c_1)| c_i \in C_i\}\) -- код \((2n, k_1 + k_0, \min(2d_1, d_0))\)
#+end_theorem

#+begin_definition org
Код Рида-Маллера \(RM(r, m)\) длины \(2^m\) порядка \(r\) -- полярный код с \(\mathcal{F} = \{i | 0 \le i < 2^m , wt(i) < m - r\}\)
#+end_definition

Размерность \(k = \sum_{i=m-r}^m C_m^i = \sum_{i = 1}^r C_m^i\). Минимальное расстояние \(d = 2^{m - r}\)

#+begin_theorem org
Минимальное расстояние \(d\) полярного кода длины \(n = 2^m\) с замороженным множеством \(\mathcal{F}\) равно \(\min_{i \not\in \mathcal{F}} 2^{wt(i)} = \min_{i \not\in \mathcal{F}} wt(A_m^{(i)})\), где вес целого числа -- число его ненулевых битов, \(A_m^{(i)}\) -- \(i\)-ая строка \(A_m\)
#+end_theorem

* Минимальное расстояние кодов Рида-Маллера, БЧХ и полярных
\todo Таблица

#+begin_rem org
Полярные коды не фонтан
#+end_rem
