#+setupfile: setup.org
#+TITLE: Лекция 9
#+date: 27 октября
#+LATEX_HEADER: \newcommand{\F}{\mathbb{F}}
#+LATEX_HEADER: \newcommand{\Z}{\mathbb{Z}}
#+LATEX_HEADER: \DeclareMathAlphabet{\mymathbb}{U}{BOONDOX-ds}{m}{n}
#+LATEX_HEADER: \newcommand{\One}{\mymathbb{1}}
#+LATEX_HEADER: \newcommand{\Zero}{\mymathbb{0}}

* Группы
#+begin_definition org
Группа \(\mathcal{G}\) -- алгебра \((G, \cdot)\).
- Операция \(\cdot\) ассоциативна, т.е. \(\forall a, b, c \in G: (a \cdot b) \cdot c = a \cdot (b \cdot c)\)
- Существует нейтральный элемент \(\One \in G : \forall x \in G : \One \cdot x = x \cdot \One = x\)
- Существует обратный элемент \(\forall x \in G \exists y : x \cdot y = y \cdot x = \One\)
#+end_definition

#+begin_remark org
Если \(\cdot\) коммутативна, т.е. \(a \cdot b = b \cdot a\), то группу называют коммутативной или абелевой. Далее все группы будем
считать коммутативными
#+end_remark

#+begin_definition org
Аддитивное задание группы: \(\cdot \to +, 1 \to 0\). Если вышеперечисленные свойства выполняются для некоторого \(H \subset G\),
замкнутого относительно операции \(\cdot\), то \(\mathcal{H} = (H, \cdot)\) называют подгруппой \(\mathca{G}\).
#+end_definition

#+begin_definition org
Группы \(\mathcal{G} = (G, \cdot)\) называется циклической, если \(\exists a \in G: \forall x \in G \exists n \in \mathcal{Z}:x = a^n\)
#+end_definition


#+begin_definition org
\-
- Порядок конечной группы -- число элементов в ней, т.е. \(|G|\)
- Порядок элемента \(a \in G\) -- наименьшее положительное \(n : a^n = \One\)
- Порядок образующего элемента конечной циклической группы равен порядку самой группы
#+end_definition

#+begin_theorem org
Пусть \(\mathcal{G} = (G, \cdot)\) -- конечная группы и элементы \(g, h \in G\) имеют порядок \(r, s\) соответственно, при чем \(\gcd(r, s) = 1\). Тогда элемент \(gh\) имеет порядок \(rs\).
#+end_theorem
#+begin_proof org
То, что \((gh)^{rs} = \One\), очевидно. Следовательно, порядок \(p\) элемента \(gh\) -- делитель числа \(rs\). Пусть \(p | (rs)\) и \((gh)^p = 1\). Тогда \((gh)^{pr} = h^{pr} = \One\).
Следоваельно, \(s | (pr)\), откуда \(s | p\). Аналогично можно показать, что \(r | p\). Т.к. \(gcd (r, s) = 1\), получаем \((rs) | p\), что означает \(p = rs\)
#+end_proof

** Подгруппы и смежные классы
#+begin_definition org
Смежный класс по подгруппе \(\mathcal{H}\): \(g\mathcal{H} = \{g \cdot h | h \in G\}, g \in G\)
#+end_definition

#+begin_definition org
Отношение эквивалентности \(\sim_{\mathcal{H}} = \{(a, b) \in G^2 | a\mathcal{H} = b\mathcal{H}\}\). Класс эквивалентности \([a]_{\sim_{\mathcal{H}}} = a\mathcal{H}\)
#+end_definition

#+begin_lemma org
Всякий смежный класс подгруппы \(\mathcal{H} = (H, \cdot)\) коммутативной группы \(\mathcal{G} = (G, \cdot)\) равномощен \(H\)
#+end_lemma
#+begin_proof org
Для \(a \in G\) зададим отображение \(\phi_a : H \to a\mathcal{H}\) как \(\phi_a(h) = ah\). Это сюрьекция, т.к. \(x \in \mathcal{H} \implies \exists h \in H : x = ah = \phi_a(h)\). Это инъекция, т.к. в группе \(ah_1 = a h_1 \implies h_1 = h_2\). Следовательно, \(\phi_a(h)\) -- биекция и \(|a \mathcal{H}| = |H|\)
#+end_proof

#+ATTR_LATEX: :options [Лагранжа]
#+begin_theorem org
Порядок конечной группы \(\mathcal{G} = (G, \cdot)\) делится на порядок любой ее подгруппы
#+end_theorem

#+begin_proof org
Смежные классы \(a \mathcal{H}\) подгруппы \(\mathcal{H}\) группы \(\mathcal{G}\) образуют разбиение \(G\) на равномощные подмножества
#+end_proof


* Конечные поля
#+begin_definition org
Полем называется алгебра \((\F, \{+, -, \cdot, /\})\), удовлетворяющая следующим аксиомам
- \(a + (b + c) = (a + b) + c\)
- \(a + b = b + a\)
- (\exists \Zero \in \F : a + \Zero = a\)
- \(\forall a \in F : \exists a' = - a \in \F : a + a' = \Zero\)
- \(a \cdot (b \cdot c) = (a \cdot b) \cdot c\)
- \(a \cdot b = b \cdot a\)
- \(a \cdot (b + c) + a \cdot b + a \cdot c, (b + c) \cdot a = b \cdot a + c \cdot a\)
- \(\exists \One \in \F \setminus \{\Zero\} : \forall a : a \cdot \One = \One \cdot a = a\)
- \(\forall a \neq \Zero \exists a^{-1} = \One / a \in \F : a \cdot a^{-1} = a^{-1} \cdot a = \One\)
  - Поля, содержащие конечное число \(q\) элементов -- конечные поля или поля Галуа \(GF(q))
  - Бесконечные поля называются полями характеристики нуль
  - Поле является областью целостности, т.к. если допустить, что \(\exists a, b \neq 0 : ab = \Zero\), то \(\Zero = (((ab)b^{-1})a^{-1}) = \One\)) = \One\)
  - Простое поле \(GF(p)\):
    - \(p\) -- простое
    - арифметика по модулю \(p\)
#+end_definition



** Идеалы
#+begin_definition org
Подмножество \(I\) кольца \(R\) называется правым (или левым) идеалом, если
- \((I, \{+\})\) является подгруппой \((R, \{ + \})\)
- \(\forall r \in R, \forall x \in I : xr \in I\) (или \(rx \in I\))
#+end_definition

В коммутативных кольцах все идеалы являются двусторонними.

#+begin_definition org
Если \(A \subset R\), то идеалом, порождаемым \(A\), называется
нименьший идеал, содержащий \(A\):
\[ \pair{A} = \sum_i r_i a_i, a_i \in A, r_i \in R \]
#+end_definition


#+begin_definition org
Идеал \(I\) конечно порожден, если существует конечное множество \(A : I = \pair{A}\)
#+end_definition
#+begin_definition org
Идеал называется главным, если он порождается единственным элементом
#+end_definition

#+begin_examp org
\-
- Множество четных чисел является идеалом в кольце \(\Z\), порожденным элементов \(2\)
- Множество многочленов с вещественными коэффицентами, делащихся на \(x ^ 2 + 1\), является идеалом \(\R[x]\)
- Множество квадратных матриц, у которых последний столбец является нулевым, является левым идеалом в кольце квадратных матриц, но не является правым идеалом
- Кольцо непрерывных функций вещественного аргумента \(C(\R)\) содержит идеал непрерывных функций, таких что \(f(1) = 0\)
- \(\{\Zero\}\) и \(R\) являются идеалами в любом кольце \(R\)
- \(\pair{x, y}\) является идеалом, содержащим все многочлены от двух переменных с нулевым свободным членом
#+end_examp

** Максимальные идеалы
Область целостности, в которой все идеалы являются главными, называется кольцом главных идеалов
#+begin_definition org
Идеал \(I\) кольца \(R\) называется максимальным, если \(I \neq R\) и всякий идеал \(J\), содержащий его, равен или \(I\), или \(R\)
#+end_definition

Идеал является максимальным, если он отличен от своего кольца и не содержится ни в каком ином идеале

Если \(f_1, f_2, \dots, f_n\) -- система образующих масимального идеала \(I\), то добавление в нее \(f_0 \not\in I\) приведет к \(\pair{f_0, \dots, f_n} = R\).

#+begin_examp org
Идеал \(\pair{7} \subset \Z\) является максимальным, т.к. числа, кратные 7, невозможно получить иначе как умножением 7 на целые числа
#+end_examp

** Факторкольца
Пусть дана полугруппа \(\mathcal{G} = (G, \cdot)\). Бинарное отношение \(\sim\subset G^2\) называется отношением конгруэнтности, если оно является эквивалентностью на \(G\) и \(\forall a, b, c \in G : (a \sim b) \implies a\cdot c \sim b \cdot c\)
#+begin_examp org
\(x \equiv y \mod n \Leftrightarrow x = qn + y\)
#+end_examp

Пусть дано кольцо \(R\) и идеал \(I \subset R\). Бинарное отношение \(\sim\equiv \{(a, b) \in R^2 | b - a \in I\}\) является
отношением конгруэнтности. Разбиение на классы эквивалентности \([a] = a + I = a \mod I = \{a + r | r \in I\}\). Множество
классов эквивалентности по отношению \(\sim\) называется факторкольцом или кольцом вычетов \(R\) по модулю \(I\) и обозначается \(R \setminus I\).
Факторкольцо является кольцом, если на нем определить  операции следующим образом:
- \((a + I) + (b + I) = \underbrace{(a + b)}_{\in R} + I\)
- \(-(a + I) = (-a) + I\)
- \((a + I)\cdot (b + I) = ab + I\)
- Нулевой элемент \(\Zero + I = I\), единичный элемент \(\One + I\)

Если \(R\) -- кольцо главных идеалов, и \(\pair{a} \in R\), то соответствующее факторкольцо обозначают \(R / aR\)
#+begin_theorem org
Если \(I \subset R\) является максимальным идеалом, то \(R/I\) является полем
#+end_theorem

#+begin_proof org
Надо показать, что для всякого ненулевого \(a + I \in R / I\) существует \(b + I : (a + I)(b + I) = \One + I\). Если \(a + I \neq \Zero\),
то \(a \not\in I\) \\
Множество \(J = \{ax + m | x \in R, m \in I\}\) является идеалом, т.к. \((a x_1 + m_1) \pm (ax_2 + m_2) = a(x_1 \pm x_2) + (m_1 \pm m_2), (x_1 \pm x_2) \in R, (m_1 \pm m_2) \in I\) и \((ax+ m)y = a(xy) + (my), xy \in R, my \in I\) при любом \(y \in R\). \\
Полагая \(x = 0\) можно получить все элементы \(I \implies I \subset J\). \\
Т.к. \(a \in J, a \not\in I\), а \(I\) -- максимальный идеал, \(J = R \implies \One \in J \implies \forall a \not\in \Zero \exists b, m : \One = ab + m\), откуда
\(ab - 1 \in I\), т.е. \((a + I)(b + I) = \One + I\). Т.е. для каждого ненулевого элемента факторкольца по модулю максимального идеала существует обратный элемент, т.е. оно является полем
#+end_proof

#+begin_theorem org
Пусть \(R\) -- кольцо главных идеалов и \(p\) -- его неприводимый элемент. Тогда факторкольцо \(R / pR\) является полем
#+end_theorem
#+begin_proof org
Докажем, что \(I = \pair{p}\) является масимальным. Предположим, что сущесвтует идеал \(J \neq R: I \subset J\). Т.к. \(R\) -- КГИ,
\(J\) является главным и \(\exists q \in R : J = \pair{q}\). Если \(q\) -- обратимый элемент кольца, то \(J = R\). Если \(J \neq R\),
то \(p \in J \implies \exists s \in R : p = qs\). Но \(p\) -- неприводимый элемент \(\implies s\) -- обратимый элемент кольца \(\implies s^{-1} \in R \implies q = s^{-1} p \implies J \subset I = J\).
Таким образом \(\pair{p} = pR\) является масимальным и \(R / pR\) является полем.
#+end_proof

#+begin_sym org
В дальшейшем подобные поля будут обозначаться просто \(R/p\)
#+end_sym

#+begin_examp org
- Пусть \(p\) -- простое число. \(\Z\) является КГИ. Тогда \(\Z / p\) является полем и обозначается \(GF(p)\)
- \(x^2 + 1\) неприводим над \(\R\). \(\R[x]\) является КГИ. Следовательно \(\R[x] / \pair{x^2 + 1}\) является полем (комплексным чисел \(\C\)).
  \[ (a + bx) (c + dx) = ac + (ab + bc)x + bdx^2 \equiv (ac - bd) + (ad + bc) x \mod (x^2 + 1) \]
  что соответсвует произведению комплексных чисел \(a + ib\) и \(c + id\), где \(i = [x]_{\equiv_{x^2 + 1}}\). Видно, что \(i \cdot i = x^2 \equiv -1 \mod (x^2 + 1)\)
- \(x^2 + x + 1\) неприводим над \(GF(2)\). \(GF(2)[x]\) является КГИ. Следовательно, \(GF(2) / \pair{x^2 + x + 1}\) является полем
  и обозначается \(GF(2^2)\) или \(GF(4)\). Элементами \(GF(4)\). Элементами \(GF(4)\) являются классы вычетов многочленов \(0, 1, x, x + 1\) по модулю \(x^2 + x + 1\).
  Все операции выполняются по модулю \(x^2 + x + 1\). Например, \(x \cdot (x + 1) = x^2 + x \equiv 1 \mod (x^2 + x + 1)\). Аналогично \(\C\), можно ввести \(\beta \in GF(2^2)\), такой что \(\beta^2 + \beta + 1 = 0\).
#+end_examp

** Характеристика поля
Если поле кончено, то не могут быть различными все элементы \(\One, \One + \One, \One + \One + \One, \dots\). Следовательно, существует наименьшее число \(p: \underbrace{\One + \One + \dots + \One}_{p \text{ раз}} = \Zero\). \(p\) -- характеристика поля

\(p\) -- простое число. Если это не так, т.е. \( p = st\), то
#+begin_export latex
\begin{center}
\begin{align*}
\Zero & = \underbrace{\One + \One + \dots + \One}_{st\text{ раз}} = \underbrace{\underbrace{\One + \One + \dots + \One}_{s\text{ раз}} + \dots + \underbrace{\One + \One + \dots + \One}_{s\text{ раз}}}_{t\text{ раз}} = \\
& = (\underbrace{\One + \One + \dots + \One}_{s\text{ раз}}) (\underbrace{\One + \One + \dots + \One}_{t\text{ раз}}) \implies s = p \lor t = p
\end{align*}
\end{center}
#+end_export


#+begin_theorem org
Пест \(\F\) -- поле из \(q\) элементов. Тогда \(q = p^m\), где \(p\) -- простое, а \(m \in \N\)
#+end_theorem
#+begin_proof org
Элемент \(\One \in \F\) образует аддитивную циклическую подгруппу простого порядка \(p\) оля \(\F \implies p | q \implies GF(p) \subset \F\).
Будем называть элементы \(\alpha_1, \dots, \alpha_m\) линейно независимыми с коэффициентами из \(GF(p)\), если \(\{(x_1, x_2, \dots, x_m) \in GF(p)^m | \sum_{i + 1}^m x_i \alpha_i = 0\} = \{(0, \dots, 0)\}\). Среди всех ЛНЗ
подмножеств \(\F\) выделим подмножество \(\{\alpha_1, \dots, \alpha_m\} \subset \F\) с максимальным числом элементов \(\implies \forall \alpha_0 \in \F \exists x_1, \dots, x_m \in GF(p) : \alpha_0 = \sum_{i=1}^m x_i \alpha_i\). Различные \(x_1, \dots, x_m \in GF(p)\) приводят к различным \(\alpha_0 \in \F \implies |\F| = p^m\) 
#+end_proof

#+begin_rem org
\-
- Поле \(GF(q^m)\) образует \(m\)-мерное линейное пространство над полем \(GF(q)\)
- \(GF(p^m), m > 1\) -- расширенное конечное поле. \(m\) -- степень расширения
- \(GF(p^m), m > 1\) не имеет ничего общего с кольцом \(\Z_{p^m}\) целых чисел по модулю \(p^m\), которое полем не является
#+end_rem

#+begin_theorem org
Ненулевые элементы \(GF(q)\) образует конечную циклическую группу по умножению
#+end_theorem

#+begin_proof org
\-
- асиомы поля \(\implies \F \setminus \{0\}\) образует конечную группу по умножению
- Выберем в \(\F \setminus \{0\}\) элемента \(\alpha\) (примитивный) с наибольшим порядком \(r\). Пуст \(l\) -- порядок
  некоторого другого элемента \(\beta \neq 0\). Пусть \(\pi\) -- простое число, такое что \(r = \pi^a r'\) и \(l = \pi^b l'\) и \(\gcd(r', \pi) = \gcd(l', \pi) = 1\)
- \(\alpha^{\pi^a}\) имеет порядок \(r'\), а \(\beta^{l'}\) имеет порядок \(\pi^b\). Порядок \(\gamma = \alpha^{\pi^a} \beta^{l'}\) равен \(\pi^b r'\)
- Т.к. \(r\) -- наибольший порядок, \(\pi^br' \le \pi^ar'\) и \(b \le a\). Это верно для всех простых \(\pi \implies\) если некоторая
  степень простого числа является делителем \(l\), то она является и делителем \(r\). Следовательно, \(l|r \implies\) все ненулевые элементы конечного поля удовлетворяет соотношению \(x^r = 1\)
- \(x^r - \One\) принадлежит Евклидову кольцу \(GF(q)[x]\) и разлагается на множители единственным образом \(\implies \forall \beta \in GF(q) \setminus \{0\} : (x - \beta) | (x^n - 1)\), откуда \(r \ge q - 1\)
- Порядок элемента не может превышать порядка самой группы \(\implies r = q - 1\)
#+end_proof

** Свойства конечных полей
- Для всякого ненулевого \(\beta \in GF(q)\) выполняется \(\beta^{q - 1} = 1\)
- Все элементы поля \(GF(q)\) удовлетворяют уравнению \(x^q - x = 0\)
- Порядок любого ненулевого \(\beta \in GF(q)\) делит \(q - 1\)
- В поле характеристики \(p > 1\) справедливо
  \[ (x+y)^p = x^p + y^p \]
\[ (x + y)^p = \sum_{i=0}^p C_p^i x^i y^{p - 1} ; C_p^i = \frac{p!}{i!(p-i)!} \equiv 0 \mod p, 0 < i < p \]

