#+LATEX_CLASS: general
#+TITLE: Лекция 13
#+AUTHOR: Ilya Yaroshevskiy

* Машина Тьюринга
\label{13_mt}
Рассмотрим мгновенной описание МТ с односторонней бесконечной
лентой. Назовем строку до головки \(\alpha\), в строку вместе с
текущим символом \(\beta\). \(q\) --- состояние.
#+begin_symb org
\(\alpha \#_q \beta\)
#+end_symb

* Стековые машины
Обобщим понятие автомата с магазинной памятью с одним стеков на большее число стеков. \(k\)-стековая машина.
#+begin_theorem org
Автомат с двумя стеками --- 2-стековая машина \(\equiv\) МТ
#+end_theorem
#+begin_proof org
Будем хранить в одном стеке \(\alpha\) в другом \(\beta\) из \ref{13_mt}
#+end_proof
#+begin_remark org
Добавление стеков не увеличивает мощность
#+end_remark
* Счетчиковые машины
#+begin_definition org
\(k\)-счетчиковая машина, машина с \(k\) счетчиками, хранящими
натуральные числа, переход только по условию равен ли счетчик нулю
#+end_definition
\(k\)-стековая машина \(\mapsto\) \((k + 1)\)-счетчиковая машина \\
\(k\)-счетчиковая машина \(\mapsto\) 2-счетчиковая машина
#+begin_theorem org
\(k\)-стековая машина \(\subset\) \((k + 1)\)-счетчиковая машина
#+end_theorem
#+begin_proof org
Запишем один стек так:
\[ A_0 + A_1b + A_2b^2 + \dots + A_tb^t \]
, где \(A_i\) символ на стеке, так что \(A_0\) лежит на самом верху --- один счетчик (число в \(b\)-ичной системе счисления) для каждого стека. Другой счетчик. Можем сделать операции: деление с остатком, умножение, прибавление константы
\todo
#+end_proof
#+begin_theorem org
\(k\)-счетчиковая машина \(\subset\) 2-счетчиковая машина
#+end_theorem
#+begin_proof org
\todo
#+end_proof
* Нормальные алгорифмы Маркова
\todo
* Грамматики нулевого класса
Контекстно свободные грамматики --- грамматики второго класса, правила вида \(A \to \alpha\). В грамматике нулевого класса правила вида \(\alpha \to \beta\), где в обоих случаях \(\alpha, \beta\) --- состоят из терминалов и нетерминалов, т.е. \(\alpha \in (\Sigma \cup N)^*\), \(\alpha\) содержит \(N\), \(\beta \in (\Sigma \cup N)^*\)
#+begin_definition org
\(\xi \Rightarrow \eta\), если
- \(\xi = \xi_1 \alpha \xi_2\)
- \(\eta = \eta_1 \beta \eta_2\)
- \(\xi_1 = \eta_1\)
- \(\xi_2 = \eta_2\)
- \(\alpha \to \beta \in \Gamma\)
#+end_definition
\[ L(\Gamma) = \{w | S \Rightarrow^* w\} \]
#+begin_theorem org
\(L = L(\Gamma)\) для грамматики 0 класса \(\Leftrightarrow\) \(L\) --- перечислимый
- \((\Rightarrow)\) ::  Запустим BFS по \(\Rightarrow\)
  - \(x \in L \implies\) рано или поздно найдем
  - \(x \not\in L \implies\) зависнем
- \((\Leftarrow)\) :: \(L\) перечислим \(\implies\) \(L\) полуразрешается МТ
  - \(S \to B U \#_Y U E\)
  - \(U \to cU\)
  - \(U \to \varepsilon\)
  - \(B\#_S  \to Z\)
  - \(\forall c \in \Sigma\quad Zc \to cZ\)
#+end_theorem
* Клеточный автомат
Есть лента с ячейками, каждая ячейка раскрашена в один из двух цветов. За один шаг каждая ячейка на \(d\) ячеек слева и справа, происходит переход в новое состояние.
- \(\delta: Q^{2d + 1} \to Q\), где \(Q\) --- множество клеток
