#+LATEX_CLASS: general
#+TITLE: Лекция 10
#+AUTHOR: Ilya Yaroshevskiy


* Разреженный формат
** Строчно столбцовый формат
1. Вещественный массив \(di[n]\) --- диагональные элементы
2. Вещественный массив \(al, au\) --- по строкам и стобцам соответсвенно
3. Целочисленный массив \(ja\) --- содержит номера столбцов (строк)
   хранимых внедиагональных элементов нижнего(верхнего) треугольника
   матрицы. \(j \le m\), где \(m\) --- размерность массивов \(ja, al, au\), \(ja[j]\) --- номер столбца для \(al[j]\), или номер строки для \(au[j]\)
4. Целочисленный массив \(ia\), \(ia[k]\) --- равен индексу(в нумерации с 1) с которого начинается \(k\)-той строки(столбца)
Размерность \(ja, al, au\): \(ia[n + 1] - 1\). \(ia[i + 1] - ia[i]\) --- количество хранимых внедиагональных элементов \(i\)-той строки(столбца) нижнего(верхнего) треугольника. \(ia\) и \(ja\) --- портрет матрицы.

#+begin_examp org
\-
\[ \begin{matrix}
a_{11} & & & & & & & & \\
0 & a_{22} & a_{23} & a_{24} & & &  \text{\huge0}& &  \\
0 & a_{32} & a_{33} & 0 & a_{35} & a_{36} & & &  \\
0 & a_{42} & 0 & a_{44} & a_{45} & 0 & a_{47} & &  \\
& & a_{53} & a_{54} & a_{55} & a_{56} & 0 & a_{58} & a_{59} \\
& & a_{63} & 0 & a_{65} & a_{66} & 0 & a_{68} & 0 \\
& & & a_{74} & 0 & 0 & a_{77} & 0 & a_{79} \\
& \text{\huge0}& &  & a_{85} & a_{86} & 0 & a_{88} & 0 \\
& & &  & a_{95} & 0 & a_{97} & 0 & a_{99}
\end{matrix} \]

\[ di = [a_{11}, a_{22}, a_{33}, a_{44}, a_{55}, a_{66}, a_{77}, a_{88}, a_{99}] \]
\[ ia = [1, 1, 1, 2, 3, 5, 7, 8, 10, 12] \]
\[ ja = [2, 2, 3, 4, 3, 5, 4, 5, 6, 5, 7] \]
\[ al = [a_{32}, a_{42}, a_{53}, a_{54}, a_{63}, a_{65}, a_{74}, a_{85}, a_{86}, a_{95}, a_{97}] \]
\[ au = [a_{23}, a_{24}, a_{35}, a_{45}, a_{36}, a_{56}, a_{47}, a_{58}, a_{68}, a_{59}, a_{79}] \]
Для шестой строчки: \(ia[6] = 5\) --- начало шестой строчки в массиве \(ja\) и \(al\). \(ia[6 + 1] - ia[6] = 7 - 5 = 2\) --- количество элементов.
1. \(ja[ia[6]] = ja[5] = 3\)
2. \(ja[ia[6] + 1] = ja[6] = 5\)
#+end_examp
** Решение СЛАУ. Метод Гаусса
\[ \begin{cases}
a_{11}x_1 + a_{12} x_2 + \dots + a_{1n}x_n = b_1 \\
a_{21}x_1 + a_{22} x_2 + \dots + a_{2n}x_n = b_2 \\
\vdots \\
a_{n1}x_1 + a_{n2} x_2 + \dots + a_{nn}x_n = b_n
\end{cases} \]

\[ Ax = b \]
- \( A = (a_{ij})_{i,j = 1}^n \) --- вещественные числа
- \(b = (b_1, b_2, \dots, b_n)^T\)
- \(x = (x_1, x_2, \dots, x_n)^T\)
\(-\frac{a_{21}}{a_{11}}, -\frac{a_{31}}{a_{11}}, \dots, -\frac{a_{n1}}{a_{11}}\)
Верхний индекс обозначает этап.
\[ \begin{cases}
a_{11}x_1 + a_{12} x_2 + \dots + a_{1n}x_n = b_1 \\
a_{22}^{(1)}x_2 + a_{23}^{(1)}x_3 + \dots + a_{2n}^{(1)}x_n = b_2^{(1)} \\
a_{32}^{(1)}x_2 + a_{33}^{(1)}x_3 + \dots + a_{3n}^{(1)}x_n = b_3^{(1)} \\
\vdots \\
a_{n2}^{(1)}x_2 + a_{n3}^{(1)}x_3 + \dots + a_{nn}^{(1)}x_n = b_n^{(1)}
\end{cases} \]
\[ a_{ij}^{(1)} = a_{ij} - \frac{a_{i1}}{a_{11}}a_{1j} \quad b_i^{(1)} = b_i - \frac{a_{i1}}{a_{11}}b_1 \quad i,j = \overline{2, n}\]
#+begin_remark org
\(a_{11} \neq 0\)
#+end_remark

\[ \begin{cases}
a_{11}x_1 + a_{12} x_2 + \dots + a_{1n}x_n = b_1 \\
a_{22}^{(1)}x_2 + a_{23}^{(1)}x_3 + \dots + a_{2n}^{(1)}x_n = b_2^{(1)} \\
a_{33}^{(2)}x_3 + a_{34}^{(2)}x_4 + \dots + a_{3n}^{(2)}x_n = b_3^{(2)} \\
\vdots \\
a_{n3}^{(2)}x_3 + a_{n4}^{(2)}x_4 + \dots + a_{nn}^{(2)}x_n = b_n^{(2)}
\end{cases} \]
\[ a_{ij}^{(2)} = a_{ij}^{(1)} - \frac{a_{i2}^{(1)}}{a_{22}^{(1)}}a_{2j}^{(1)} \quad b_i^{(2)} = b_i^{(1)} - \frac{a_{i2}^{(1)}}{a_{22}^{(1)}}b_2^{(1)} \]

\(n - 1\) этап:

\[ \begin{cases}
a_{11}x_1 + a_{12} x_2 + \dots + a_{1n}x_n = b_1 \\
a_{22}^{(1)}x_2 + a_{23}^{(1)}x_3 + \dots + a_{2n}^{(1)}x_n = b_2^{(1)} \\
a_{33}^{(2)}x_3 + a_{34}^{(2)}x_4 + \dots + a_{3n}^{(2)}x_n = b_3^{(2)} \\
\vdots \\
a_{nn}^{(n - 1)}x_n = b_n^{(n - 1)}
\end{cases} \]

\[ a_{ij}^{(k)} = a_{ij}^{(k - 1)} - \frac{a_{ik}^{(k - 1)}}{a_{kk}^{(k - 1)}}a_{kj}^{(k - 1)} \quad b_i^{(k)} = b_i^{(k - 1)} - \frac{a_{ik}^{(k - 1)}}{a_{kk}^{(k - 1)}}b_k^{(k - 1)} \quad \ k \in \overline{1, n};\ i,j \in \overline{k + 1, n}\]
** Обратный ход Гаусса
\[ x_n = \frac{b_n^{(n - 1)}}{a_{nn}^{(n - 1)}} \]
\[ \vdots \]
\[ x_2 = \frac{b_2^{(1)} - a_{23}^{(1)} x_3 - \dots - a_{2n}^{(1)}x_n}{a_{22}^{(1)}} \]
\[ x_1 = \frac{b_1 - a_{12} x_2 - \dots - a_{1n} x_n}{a_{11}} \]
\[ x_k = \frac{b_k^{(k - 1)} - \sum_{i = k + 1}^n a_{ki}^{(k - 1)} x_i}{a_{kk}^{(k - 1)}} \quad k \in \overline{n, 1}\]
\(\sum_j^n = 0\), если \(j > n\)
#+begin_export latex
\begin{rualgo}[H]
\caption{метод Гаусса}
\begin{algorithmic}[1]
\FOR{\(k = 1,\dots, n - 1\)}
  \FOR{\(i = k+1,\dots,n\)}
    \STATE \(t_{ik} = \frac{a_{ik}}{a_{kk}}\)
    \STATE \(b_i = b_i - t_{ik}b_k\)
    \FOR{\(j = k + 1,\dots,n\)}
      \STATE \(a_{ij} = a_{ij} - t_{ik}a_{kj}\)
    \ENDFOR
  \ENDFOR
\ENDFOR
\STATE \(x_n = \frac{b_n}{a_{nn}}\)
\FOR{\(k = n - 1,\dots, 1\)}
  \STATE \(x_k = \frac{(b_k - \sum_{j = k + 1}^n a_{kj} x_j)}{a_{kk}}\)
\ENDFOR
\end{algorithmic}
\end{rualgo}
#+end_export

Модификация с постолбцовым выбором глваного элемента
#+begin_export latex
\begin{rualgo}[h]
\caption{модификация алгоритма гаусса}
\begin{algorithmic}[1]
\state \(m:\ m \ge k,\ |a_{mk}| = \max_{i \ge k}\{|a_{ik}|\}\)
\if{\(a_{mk} = 0\)}
\state нет однозначного решения. завершить алгоритм
\else
\for{\(j = k,\dots,n\)}
\state поменять местами \(b_x\) и \(b_m\)
\state поменять местами \(a_{kj}\) и \(a_{mj}\)
\endfor
\endif
\end{algorithmic}
\end{rualgo}
#+end_export
