#+LATEX_CLASS: general
#+TITLE: Лекция 5
#+AUTHOR: Ilya Yaroshevskiy


* Метод Ньютона(продолжение). Вывод через ряд Тейлора
- $x_k$ --- текущая оценка решения $x^*$
\[ f(x_k + p) = f(x_k) + pf'(x_k) + \frac{1}{2!}p^2f''(x_k) + \dots \]
\[ f(x^*) = \min_x f(x) = \min_p f(x_k + p) = \min_p [ f(x_k) + pf'(x_k) + \frac{1}{2}p^2 f''(x_k)  + \dots ] \approx \]
\[ \approx \min_p[f(x_k) + pf'(x_k) + \frac{1}{2}p^2 f''(x_k)] \]
\[ f'(x_k) + pf''(x_k) = 0 \]
\[ p = -\frac{f'(x_k)}{f''(x_k)} \]
$p$ --- аппроксимация шага: от $x_k \to x^*$. $x^* \approx x_k + p$
\[ x_{k + 1} = x_k + p = x_k - \frac{f'(x_k)}{f''(x_k)} \label{nuton_1_5}\addtag \]
Главное преимущество метода Ньютона:
- высокая(квадратичная) скорость сходимости
  - если $x_k$ достаточно близка $x^*$ и если $f''(x^*) > 0$, то:
    \[ |x_{k+1} - x^*| \le \beta|x_k - x^*|^2\quad, \beta = \const > 0 \]
    
\noindentНеудачи в методе Ньютона:
1. $f(x)$ плохо аппроксимируется первыми тремя членами в ряде Тейлора. $x_{k+1}$ может быть хуже $x_k$
2. $p=-\frac{f'(x_k)}{f''(x_k)}$ определено только тогда, когда $f''(x_k)\neq0$ \\
   $f''(x_k) > 0$ --- условие минимума квадратичной аппроксимации \\
   Если $f''(x_k) < 0$ --- алгоритм сходится к максимуму
3. Кроме $f(x)$ нужно вычислять $f'(x)$ и $f''(x)$, что в реальных задачах затруднительно
** Аппроксимация производных
Правая разностная схема:
\[ f'(x_k) \approx \frac{f(x_k + h) - f(x_k)}{h}\quad ,h \sim \varepsilon \]
Центральная разностная схема:
\[ f'(x_k) \approx \frac{f(x_k + h) - f(x_k - h)}{2h} \]
порядок точности --- $O(h^2)$
** Метод Ньютона(продолжение)
Если $f(x)$ --- квадратичная функция, то $f'(x)$ --- линейная \\
В \ref{nuton_1_5} точное равенство, и следовательно метод Ньютона
сходится за один шаг, при любом выборе $x$ \\
Пусть $x^* \in [a, b]$ и $f(x)$ --- трижды непрерывно дифференцируемая и выпуклая на $[a, b]$ функция. \\
$\{x_k\}$ будет сходится к пределе $x^*$ монотонно, если:
\[ 0<\frac{x^* - x_{k+1}}{x^* - x_k} < 1 \]
\[ f'(x^*) = 0 = f'(x_k) + f''(x_k(x^* - x_k)) + \frac{f'''(x_k)}{2}(x^* - x_k)^2 \]
\[ \frac{x^* - x_{k + 1}}{x^* - x_k} = \frac{x^* - x_k + \frac{f'(x_k)}{f''(x_k)}}{x^* - x_k} = 1 - \frac{2}{2 + \frac{f'''(x)(x^* - x_k)^2}{f'(x_k)}}\]
Итерационная поледовательность \(\{x_k\}\) монотонна, если \(\frac{f'''(x)}{f'(x_k)} > 0\),
то есть достаточное условие монотонной сходимости метода Ньютона: постоянство \(x\ in [x^*, x_0]\) занка \(f'''(x)\) и совпадение его со сзнаком \(f'(x^0)\) 
#+begin_examp org
\[ f(x) = x\cdot\arctg(x) - \frac{1}{2}\ln(1 + x^2) \]
, пусть \(|f'(x)| \le 10^{-7}\)
\[ f'''(x) = -\frac{2x}{(1 + x^2)^2} \]
\[ f'(x)\cdotf''(x) < 0 \]
Выбор начального приближение \( x_0 = 1\)
\[ x_{k + 1} = x_k - \frac{f'(x_k)}{f''(x_k)} \]
| \(k\) | \(x_k\)            |       \(f'(x_k)\) | \(f''(x_k)\)    |
|-------+--------------------+-------------------+-----------------|
|     / | <                  |                   | >               |
|     0 | 1                  |             0.785 | \(\frac{1}{2}\) |
|     1 | -0.57              |            -0.518 | 0.754           |
|     2 | 0.117              |             0.116 | \dots           |
|     3 | \dots              |             \dots | \dots           |
|     4 | \(9\cdot 10^{-8}\) | \(9\cdot10^{-8}\) | \dots           |
Выолнилось условие \(|f'(x_k)| \le 10^{-7}\) --- окончание итерационного процесса. \(x \approx 9\cdot 10^{-8} \approx 0\)
#+end_examp
** Модификации метода Ньютона
*** Метод Ньютона-Рафсона
\[ x_{k + 1} = x_k - \tau_k\frac{f'(x_k)}{f''(x_k)}\quad, 0 < \tau_k \le 1 \]
\(\tau_k = \tau = \const \) (\(\tau = 1\) --- метод Ньютона)
\[ \varphi(\tau) = f(x_k - \tau\frac{f'(x_k)}{f''(x_k)}) \to \min \]
\[ \tau_k = \frac{(f'(x_k))^2}{(f'(x_k))^2 + (f'(\tilde{x}_k))^2} \]
, где \(\tilde{x} = x_k - \frac{f'(x_k)}{f''(x_k)}\)
*** Метод Маркрафта
\[ x_{k + 1} = x_k - \frac{f'(x_k)}{f''(x_k) + \mu_k}\quad,\mu_k > 0 \]
\(\mu_0\) рекомендуется выбирать на порядок больше значения второй произвдной в \(x_0\) \\
\(\mu_{k + 1}\): \(\mu_{k + 1} = \frac{\mu_k}{2}\), если \(f(x_{k + 1}) < f(x_k)\), иначе \(\mu_{k + 1} = 2\cdot\mu_k\)
** Метод минимизации многомодальных функций
*** Метод ломанных
Условие Липшица: \(f(x),\ x\in [a, b]\) будет удовлетворять условию, если:
\[ |f(x_1) - f(x_2)| \le L|x_1 - x_2|\quad,\forall x_1, x_2 \in [a, b] \]
\(\forall x_1, x_2 \in [a, b]\)
\[ \left.\begin{matrix} x_1^* = \frac{1}{2L} [f(a) - f(b) + L(a + b)] \\
   p_1^* = \frac{1}{2} [f(a) + f(b) + L(a - b)] \end{matrix}\right\} \text{--- схема} \]
1. вместо \((x_1^*, p_1^*)\)
   - \((x_1', p_1)\)
     \[ x_1' = x_1^* - \Delta_1 \]
   - \((x_1'', p_1)\)
     \[ x_1'' = x_1^* + \Delta_1 \]
   \[ p_1 = \frac{1}{2}[f(x_1^*) + p_1^*] \]
   \[ \Delta_1 = \frac{1}{2L} [f(x_1^* - p_1^*)] \]
2. Из пар \((x_1', p_1), (x_1'', p_1)\), выбрать ту, у которой вторая компонента \(p\) минимальна и обозначить ее \((x_2^*, p_2^*)\) и исключить из рассматриваемого множесвта. Переход к шагу 1
В результате множество пар \((x, p)\).  \(x^* \approx x_n^*\), \(f^* \approx f(x^*_n)\)
#+begin_examp org
\[ f(x) = \frac{\sin(x)}{x} \quad [10, 15] \quad \varepsilon = 0.01 \]
\[ |f'(x)) = \left|\frac{x\cos x - \sin x}{x^2}\right| < \frac{x|\cos x| + \sin |x|}{x^2} < \frac{x + 1}{x^2} \le 0.11\ x \in [10, 15] \]
\[ L = 0.11 \]
\[ x_1^* = 12.056 \quad p_1^* = -0.281 \]
#+end_examp

