#+title: HW 7

* Statements
Реализуйте указанные запросы, представления, проверки и триггеры на языке SQL.

1. Напишите запросы, удаляющие студентов
   1. Учащихся в группе, заданной идентификатором (GroupId).
   2. Учащихся в группе, заданной названием (GroupName).
   3. Без оценок.
   4. Имеющих 3 и более оценки.
   5. Имеющих 3 и менее оценки.
   6. Студентов, c долгами (здесь и далее — по отсутствию оценки).
   7. Студентов, имеющих 2 и более долга.
   8. Студентов, имеющих не более 2 долгов.
2. Напишите запросы, обновляющие данные студентов
   1. Изменение имени студента (StudentId, StudentName).
   2. Перевод студента из группы в группу по индентификаторам (StudentId, GroupId, FromGroupId).
   3. Перевод всех студентов из группы в группу по идентификаторам (GroupId, FromGroupId).
   4. Перевод всех студентов из группы в группу по названиям (GroupName, FromGroupName).
   5. Перевод всех студентов из группы в группу, только если целевая группа существует (GroupName, FromGroupName).
3. Напишите запросы, подсчитывающие статистику по студентам
   1. Число оценок студента (столбец Students.Marks) (StudentId).
   2. Число оценок каждого студента (столбец Students.Marks).
   3. Пересчет числа оценок каждого студента, с учётом новых оценок из таблицы NewMarks, структура которой такая же как у таблицы Marks (столбец Students.Marks).
   4. Число сданных дисциплин каждого студента (столбец Students.Marks).
   5. Число долгов студента (столбец Students.Debts) (StudentId).
   6. Число долгов каждого студента (столбец Students.Debts).
   7. Число долгов каждого студента группы (столбец Students.Debts) (GroupName).
   8. Число оценок и долгов каждого студента (столбцы Students.Marks, Students.Debts).
4. Напишите запросы, обновляющие оценки, с учетом данных из таблицы NewMarks, имеющей такую же структуру, как таблица Marks
   1. Проставляющий новую оценку только если ранее оценки не было.
   2. Проставляющий новую оценку только если ранее оценка была.
   3. Проставляющий максимум из старой и новой оценки только если ранее оценка была.
   4. Проставляющий максимум из старой и новой оценки (если ранее оценки не было, то новую оценку).
5. Работа с представлениями
   1. Создайте представление StudentMarks в котором для каждого студента указано число оценок (StudentId, Marks).
   2. Создайте представление AllMarks в котором для каждого студента указано число оценок, включая оценки из таблицы NewMarks (StudentId, Marks).
   3. Создайте представление Debts в котором для каждого студента, имеющего долги указано их число (StudentId, Debts).
   4. Создайте представление StudentDebts в котором для каждого студента указано число долгов (StudentId, Debts).
6. Целостность данных.
   Обратите внимание, что задания из этого раздела надо посылать в PCMS, но они будут проверяться только вручную после окончания сдачи. То есть в PCMS вы получите + за любое решение.

   В комментарии перед каждым запросом укажите версию использованной СУБД.

   1. Добавьте проверку того, что у студентов есть оценки только по дисциплинам из их плана (NoExtraMarks).
   2. Добавьте проверку того, что все студенты каждой группы имеют оценку по одному и тому же набору дисциплин (SameMarks).
   3. Создайте триггер PreserveMarks, не позволяющий уменьшить оценку студента по дисциплине. При попытке такого изменения оценка изменяться не должна.

* Comments
- 1.1
- 1.2
- 1.3
- 1.4
- 1.5
- 1.6
- 1.7
- 1.8
- 2.1
- 2.2
- 2.3
- 2.4
- 2.5
- 3.1
- 3.2
- 3.3
- 3.4
- 3.5
  - SQL: Слишком много соединений: 2
- 3.6
  - SQL: Слишком много соединений: 2
- 3.7
  - SQL: Слишком много соединений: 2
- 3.8
  - SQL: Слишком много соединений: 2
- 4.1
- 4.2
  - SQL: Использование select * (игнорируется): 1
- 4.3
  - SQL: Использование select * (игнорируется): 1
  - SQL: Слишком много кореллированных подзапросов: 1
- 4.4
  - SQL: Использование select * (игнорируется): 1
  - SQL: Слишком много кореллированных подзапросов: 1
- 5.1
- 5.2
- 5.3
- 5.4
- 6.1
  - Лишний on insert для: Students
- 6.2
  - Нет решения
- 6.3
  - Триггер возвращает ошибку
  - Плохо: 2 IF с одинаковым возвращаемым значением
