#+LATEX_CLASS: general
#+TITLE: Вторая мировая война
#+AUTHOR: Ilya Yaroshevskiy

* Отношения европейских государст

Причины:

1. ...
2. ...
3. Ход политики

1 сентября - Германия напала на Польшу. На самом деле гораздо раньше
20е-30е годы - млитаризция Японии.
31й год - Озеро Хасан, Манчжоу-Го, Япония отобрала у Китая, военные действия
Идея колективной безопасности - защита от нацистского режима. Европа не подержала комунистов.
38й год - Объединение Гремании и Австрии - нарушение версальского договора
Конфереция в Мюнхене.

Воссоединение немецкого народа:
1. В польше
2. В чехословакии

Главная задача - чтобы Германия вступила в войну с СССР.

...

Парад советских и германских войск в честь попеды в Польше.

3го сентября - Фрнция, Великобритания объявила войну Гремании, но не начала ее.
40й год - Латвия, Литва, ?Эстония вошли в СССР

Барбаросса - план нападения на СССР
Морской лев - на Великобританию
22е июля - нападение германии на СССР

22е июня - Великобритания объявляет о поддержке СССР
Анигитлеровская коалиция. Сталин, Черчель, Рузвельд
 
